package defpackage;

/* JADX INFO: loaded from: classes3.dex */
public final class a8k implements tac {
    public static final a8k a = new a8k();
    public static final mh7 b = new mh7("systemInfo", ebh.t(fsh.s(vrj.class, new uqj(1))));
    public static final mh7 c = new mh7("eventName", ebh.t(fsh.s(vrj.class, new uqj(2))));
    public static final mh7 d = new mh7("isThickClient", ebh.t(fsh.s(vrj.class, new uqj(37))));
    public static final mh7 e = new mh7("clientType", ebh.t(fsh.s(vrj.class, new uqj(61))));
    public static final mh7 f = new mh7("modelDownloadLogEvent", ebh.t(fsh.s(vrj.class, new uqj(3))));
    public static final mh7 g = new mh7("customModelLoadLogEvent", ebh.t(fsh.s(vrj.class, new uqj(20))));
    public static final mh7 h = new mh7("customModelInferenceLogEvent", ebh.t(fsh.s(vrj.class, new uqj(4))));
    public static final mh7 i = new mh7("customModelCreateLogEvent", ebh.t(fsh.s(vrj.class, new uqj(29))));
    public static final mh7 j = new mh7("onDeviceFaceDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(5))));
    public static final mh7 k = new mh7("onDeviceFaceLoadLogEvent", ebh.t(fsh.s(vrj.class, new uqj(59))));
    public static final mh7 l = new mh7("onDeviceTextDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(6))));
    public static final mh7 m = new mh7("onDeviceTextDetectionLoadLogEvent", ebh.t(fsh.s(vrj.class, new uqj(79))));
    public static final mh7 n = new mh7("onDeviceBarcodeDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(7))));
    public static final mh7 o = new mh7("onDeviceBarcodeLoadLogEvent", ebh.t(fsh.s(vrj.class, new uqj(58))));
    public static final mh7 p = new mh7("onDeviceImageLabelCreateLogEvent", ebh.t(fsh.s(vrj.class, new uqj(48))));
    public static final mh7 q = new mh7("onDeviceImageLabelLoadLogEvent", ebh.t(fsh.s(vrj.class, new uqj(49))));
    public static final mh7 r = new mh7("onDeviceImageLabelDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(18))));
    public static final mh7 s = new mh7("onDeviceObjectCreateLogEvent", ebh.t(fsh.s(vrj.class, new uqj(26))));
    public static final mh7 t = new mh7("onDeviceObjectLoadLogEvent", ebh.t(fsh.s(vrj.class, new uqj(27))));
    public static final mh7 u = new mh7("onDeviceObjectInferenceLogEvent", ebh.t(fsh.s(vrj.class, new uqj(28))));
    public static final mh7 v = new mh7("onDevicePoseDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(44))));
    public static final mh7 w = new mh7("onDeviceSegmentationLogEvent", ebh.t(fsh.s(vrj.class, new uqj(45))));
    public static final mh7 x = new mh7("onDeviceSmartReplyLogEvent", ebh.t(fsh.s(vrj.class, new uqj(19))));
    public static final mh7 y = new mh7("onDeviceLanguageIdentificationLogEvent", ebh.t(fsh.s(vrj.class, new uqj(21))));
    public static final mh7 z = new mh7("onDeviceTranslationLogEvent", ebh.t(fsh.s(vrj.class, new uqj(22))));
    public static final mh7 A = new mh7("cloudFaceDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(8))));
    public static final mh7 B = new mh7("cloudCropHintDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(9))));
    public static final mh7 C = new mh7("cloudDocumentTextDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(10))));
    public static final mh7 D = new mh7("cloudImagePropertiesDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(11))));
    public static final mh7 E = new mh7("cloudImageLabelDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(12))));
    public static final mh7 F = new mh7("cloudLandmarkDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(13))));
    public static final mh7 G = new mh7("cloudLogoDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(14))));
    public static final mh7 H = new mh7("cloudSafeSearchDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(15))));
    public static final mh7 I = new mh7("cloudTextDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(16))));
    public static final mh7 J = new mh7("cloudWebSearchDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(17))));
    public static final mh7 K = new mh7("automlImageLabelingCreateLogEvent", ebh.t(fsh.s(vrj.class, new uqj(23))));
    public static final mh7 L = new mh7("automlImageLabelingLoadLogEvent", ebh.t(fsh.s(vrj.class, new uqj(24))));
    public static final mh7 M = new mh7("automlImageLabelingInferenceLogEvent", ebh.t(fsh.s(vrj.class, new uqj(25))));
    public static final mh7 N = new mh7("isModelDownloadedLogEvent", ebh.t(fsh.s(vrj.class, new uqj(39))));
    public static final mh7 O = new mh7("deleteModelLogEvent", ebh.t(fsh.s(vrj.class, new uqj(40))));
    public static final mh7 P = new mh7("aggregatedAutomlImageLabelingInferenceLogEvent", ebh.t(fsh.s(vrj.class, new uqj(30))));
    public static final mh7 Q = new mh7("aggregatedCustomModelInferenceLogEvent", ebh.t(fsh.s(vrj.class, new uqj(31))));
    public static final mh7 R = new mh7("aggregatedOnDeviceFaceDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(32))));
    public static final mh7 S = new mh7("aggregatedOnDeviceBarcodeDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(33))));
    public static final mh7 T = new mh7("aggregatedOnDeviceImageLabelDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(34))));
    public static final mh7 U = new mh7("aggregatedOnDeviceObjectInferenceLogEvent", ebh.t(fsh.s(vrj.class, new uqj(35))));
    public static final mh7 V = new mh7("aggregatedOnDeviceTextDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(36))));
    public static final mh7 W = new mh7("aggregatedOnDevicePoseDetectionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(46))));
    public static final mh7 X = new mh7("aggregatedOnDeviceSegmentationLogEvent", ebh.t(fsh.s(vrj.class, new uqj(47))));
    public static final mh7 Y = new mh7("pipelineAccelerationInferenceEvents", ebh.t(fsh.s(vrj.class, new uqj(69))));
    public static final mh7 Z = new mh7("remoteConfigLogEvent", ebh.t(fsh.s(vrj.class, new uqj(42))));
    public static final mh7 a0 = new mh7("inputImageConstructionLogEvent", ebh.t(fsh.s(vrj.class, new uqj(50))));
    public static final mh7 b0 = new mh7("leakedHandleEvent", ebh.t(fsh.s(vrj.class, new uqj(51))));
    public static final mh7 c0 = new mh7("cameraSourceLogEvent", ebh.t(fsh.s(vrj.class, new uqj(52))));
    public static final mh7 d0 = new mh7("imageLabelOptionalModuleLogEvent", ebh.t(fsh.s(vrj.class, new uqj(53))));
    public static final mh7 e0 = new mh7("languageIdentificationOptionalModuleLogEvent", ebh.t(fsh.s(vrj.class, new uqj(54))));
    public static final mh7 f0 = new mh7("faceDetectionOptionalModuleLogEvent", ebh.t(fsh.s(vrj.class, new uqj(60))));
    public static final mh7 g0 = new mh7("nlClassifierOptionalModuleLogEvent", ebh.t(fsh.s(vrj.class, new uqj(55))));
    public static final mh7 h0 = new mh7("nlClassifierClientLibraryLogEvent", ebh.t(fsh.s(vrj.class, new uqj(56))));
    public static final mh7 i0 = new mh7("accelerationAllowlistLogEvent", ebh.t(fsh.s(vrj.class, new uqj(57))));
    public static final mh7 j0 = new mh7("toxicityDetectionCreateEvent", ebh.t(fsh.s(vrj.class, new uqj(62))));
    public static final mh7 k0 = new mh7("toxicityDetectionLoadEvent", ebh.t(fsh.s(vrj.class, new uqj(63))));
    public static final mh7 l0 = new mh7("toxicityDetectionInferenceEvent", ebh.t(fsh.s(vrj.class, new uqj(64))));
    public static final mh7 m0 = new mh7("barcodeDetectionOptionalModuleLogEvent", ebh.t(fsh.s(vrj.class, new uqj(65))));
    public static final mh7 n0 = new mh7("customImageLabelOptionalModuleLogEvent", ebh.t(fsh.s(vrj.class, new uqj(66))));
    public static final mh7 o0 = new mh7("codeScannerScanApiEvent", ebh.t(fsh.s(vrj.class, new uqj(67))));
    public static final mh7 p0 = new mh7("codeScannerOptionalModuleEvent", ebh.t(fsh.s(vrj.class, new uqj(68))));
    public static final mh7 q0 = new mh7("onDeviceExplicitContentCreateLogEvent", ebh.t(fsh.s(vrj.class, new uqj(70))));
    public static final mh7 r0 = new mh7("onDeviceExplicitContentLoadLogEvent", ebh.t(fsh.s(vrj.class, new uqj(71))));
    public static final mh7 s0 = new mh7("onDeviceExplicitContentInferenceLogEvent", ebh.t(fsh.s(vrj.class, new uqj(72))));
    public static final mh7 t0 = new mh7("aggregatedOnDeviceExplicitContentLogEvent", ebh.t(fsh.s(vrj.class, new uqj(73))));
    public static final mh7 u0 = new mh7("onDeviceSelfieFaceCreateLogEvent", ebh.t(fsh.s(vrj.class, new uqj(74))));
    public static final mh7 v0 = new mh7("onDeviceSelfieFaceLoadLogEvent", ebh.t(fsh.s(vrj.class, new uqj(75))));
    public static final mh7 w0 = new mh7("onDeviceSelfieFaceLogEvent", ebh.t(fsh.s(vrj.class, new uqj(76))));
    public static final mh7 x0 = new mh7("aggregatedOnDeviceSelfieFaceLogEvent", ebh.t(fsh.s(vrj.class, new uqj(77))));
    public static final mh7 y0 = new mh7("smartReplyOptionalModuleLogEvent", ebh.t(fsh.s(vrj.class, new uqj(78))));

    @Override // defpackage.cn6
    public final void a(Object obj, Object obj2) {
        qnk qnkVar = (qnk) obj;
        uac uacVar = (uac) obj2;
        uacVar.a(b, qnkVar.a);
        uacVar.a(c, qnkVar.b);
        uacVar.a(d, null);
        uacVar.a(e, qnkVar.c);
        uacVar.a(f, null);
        uacVar.a(g, null);
        uacVar.a(h, null);
        uacVar.a(i, null);
        uacVar.a(j, null);
        uacVar.a(k, null);
        uacVar.a(l, null);
        uacVar.a(m, null);
        uacVar.a(n, null);
        uacVar.a(o, null);
        uacVar.a(p, null);
        uacVar.a(q, null);
        uacVar.a(r, null);
        uacVar.a(s, null);
        uacVar.a(t, null);
        uacVar.a(u, null);
        uacVar.a(v, null);
        uacVar.a(w, null);
        uacVar.a(x, null);
        uacVar.a(y, qnkVar.d);
        uacVar.a(z, null);
        uacVar.a(A, null);
        uacVar.a(B, null);
        uacVar.a(C, null);
        uacVar.a(D, null);
        uacVar.a(E, null);
        uacVar.a(F, null);
        uacVar.a(G, null);
        uacVar.a(H, null);
        uacVar.a(I, null);
        uacVar.a(J, null);
        uacVar.a(K, null);
        uacVar.a(L, null);
        uacVar.a(M, null);
        uacVar.a(N, null);
        uacVar.a(O, null);
        uacVar.a(P, null);
        uacVar.a(Q, null);
        uacVar.a(R, null);
        uacVar.a(S, null);
        uacVar.a(T, null);
        uacVar.a(U, null);
        uacVar.a(V, null);
        uacVar.a(W, null);
        uacVar.a(X, null);
        uacVar.a(Y, null);
        uacVar.a(Z, null);
        uacVar.a(a0, null);
        uacVar.a(b0, null);
        uacVar.a(c0, null);
        uacVar.a(d0, null);
        uacVar.a(e0, null);
        uacVar.a(f0, null);
        uacVar.a(g0, null);
        uacVar.a(h0, null);
        uacVar.a(i0, null);
        uacVar.a(j0, null);
        uacVar.a(k0, null);
        uacVar.a(l0, null);
        uacVar.a(m0, null);
        uacVar.a(n0, null);
        uacVar.a(o0, null);
        uacVar.a(p0, null);
        uacVar.a(q0, null);
        uacVar.a(r0, null);
        uacVar.a(s0, null);
        uacVar.a(t0, null);
        uacVar.a(u0, null);
        uacVar.a(v0, null);
        uacVar.a(w0, null);
        uacVar.a(x0, null);
        uacVar.a(y0, null);
    }
}
