package defpackage;

import android.health.connect.datatypes.ActiveCaloriesBurnedRecord;
import android.health.connect.datatypes.BasalMetabolicRateRecord;
import android.health.connect.datatypes.BloodPressureRecord;
import android.health.connect.datatypes.CyclingPedalingCadenceRecord;
import android.health.connect.datatypes.DistanceRecord;
import android.health.connect.datatypes.ElevationGainedRecord;
import android.health.connect.datatypes.ExerciseSessionRecord;
import android.health.connect.datatypes.FloorsClimbedRecord;
import android.health.connect.datatypes.HeartRateRecord;
import android.health.connect.datatypes.HeightRecord;
import android.health.connect.datatypes.HydrationRecord;
import android.health.connect.datatypes.NutritionRecord;
import android.health.connect.datatypes.PowerRecord;
import android.health.connect.datatypes.RestingHeartRateRecord;
import android.health.connect.datatypes.SkinTemperatureRecord;
import android.health.connect.datatypes.SleepSessionRecord;
import android.health.connect.datatypes.SpeedRecord;
import android.health.connect.datatypes.StepsCadenceRecord;
import android.health.connect.datatypes.StepsRecord;
import android.health.connect.datatypes.TotalCaloriesBurnedRecord;
import android.health.connect.datatypes.WeightRecord;
import android.health.connect.datatypes.WheelchairPushesRecord;
import android.os.ext.SdkExtensions;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Map;

/* JADX INFO: loaded from: classes2.dex */
public abstract class es {
    public static final Map a;
    public static final Map b;
    public static final Map c;
    public static final Map d;
    public static final Map e;
    public static final Map f;
    public static final Map g;
    public static final Map h;
    public static final Map i;
    public static final Map j;
    public static final Map k;
    public static final Map l;

    static {
        cpc[] cpcVarArr = SdkExtensions.getExtensionVersion(34) >= 10 ? new cpc[]{new cpc(te5.g, CyclingPedalingCadenceRecord.RPM_AVG), new cpc(te5.i, CyclingPedalingCadenceRecord.RPM_MAX), new cpc(te5.h, CyclingPedalingCadenceRecord.RPM_MIN), new cpc(mng.g, StepsCadenceRecord.STEPS_CADENCE_RATE_AVG), new cpc(mng.i, StepsCadenceRecord.STEPS_CADENCE_RATE_MAX), new cpc(mng.h, StepsCadenceRecord.STEPS_CADENCE_RATE_MIN)} : new cpc[0];
        wig wigVar = new wig(2);
        ebh.x(jp7.g, FloorsClimbedRecord.FLOORS_CLIMBED_TOTAL, wigVar);
        wigVar.b(cpcVarArr);
        ArrayList arrayList = wigVar.a;
        a = sta.h0((cpc[]) arrayList.toArray(new cpc[arrayList.size()]));
        b = sta.h0(new cpc(n67.m, ExerciseSessionRecord.EXERCISE_DURATION_TOTAL), new cpc(r9g.i, SleepSessionRecord.SLEEP_DURATION_TOTAL));
        c = sta.h0(new cpc(zb.h, ActiveCaloriesBurnedRecord.ACTIVE_CALORIES_TOTAL), new cpc(ed1.f, BasalMetabolicRateRecord.BASAL_CALORIES_TOTAL), new cpc(qac.f0, NutritionRecord.ENERGY_TOTAL), new cpc(qac.g0, NutritionRecord.ENERGY_FROM_FAT_TOTAL), new cpc(c3i.h, TotalCaloriesBurnedRecord.ENERGY_TOTAL));
        d = sta.h0(new cpc(d96.h, DistanceRecord.DISTANCE_TOTAL), new cpc(kk6.i, ElevationGainedRecord.ELEVATION_GAINED_TOTAL), new cpc(lm8.f, HeightRecord.HEIGHT_AVG), new cpc(lm8.g, HeightRecord.HEIGHT_MIN), new cpc(lm8.h, HeightRecord.HEIGHT_MAX));
        e = sta.h0(new cpc(xl8.g, HeartRateRecord.BPM_AVG), new cpc(xl8.h, HeartRateRecord.BPM_MIN), new cpc(xl8.i, HeartRateRecord.BPM_MAX), new cpc(xl8.j, HeartRateRecord.HEART_MEASUREMENTS_COUNT), new cpc(cre.e, RestingHeartRateRecord.BPM_AVG), new cpc(cre.f, RestingHeartRateRecord.BPM_MIN), new cpc(cre.g, RestingHeartRateRecord.BPM_MAX), new cpc(ong.g, StepsRecord.STEPS_COUNT_TOTAL), new cpc(u9j.g, WheelchairPushesRecord.WHEEL_CHAIR_PUSHES_COUNT_TOTAL));
        wig wigVar2 = new wig(40);
        ebh.x(qac.c0, NutritionRecord.BIOTIN_TOTAL, wigVar2);
        ebh.x(qac.d0, NutritionRecord.CAFFEINE_TOTAL, wigVar2);
        ebh.x(qac.e0, NutritionRecord.CALCIUM_TOTAL, wigVar2);
        ebh.x(qac.h0, NutritionRecord.CHLORIDE_TOTAL, wigVar2);
        ebh.x(qac.i0, NutritionRecord.CHOLESTEROL_TOTAL, wigVar2);
        ebh.x(qac.j0, NutritionRecord.CHROMIUM_TOTAL, wigVar2);
        ebh.x(qac.k0, NutritionRecord.COPPER_TOTAL, wigVar2);
        ebh.x(qac.l0, NutritionRecord.DIETARY_FIBER_TOTAL, wigVar2);
        ebh.x(qac.m0, NutritionRecord.FOLATE_TOTAL, wigVar2);
        ebh.x(qac.n0, NutritionRecord.FOLIC_ACID_TOTAL, wigVar2);
        ebh.x(qac.o0, NutritionRecord.IODINE_TOTAL, wigVar2);
        ebh.x(qac.p0, NutritionRecord.IRON_TOTAL, wigVar2);
        ebh.x(qac.q0, NutritionRecord.MAGNESIUM_TOTAL, wigVar2);
        ebh.x(qac.r0, NutritionRecord.MANGANESE_TOTAL, wigVar2);
        ebh.x(qac.s0, NutritionRecord.MOLYBDENUM_TOTAL, wigVar2);
        ebh.x(qac.t0, NutritionRecord.MONOUNSATURATED_FAT_TOTAL, wigVar2);
        ebh.x(qac.u0, NutritionRecord.NIACIN_TOTAL, wigVar2);
        ebh.x(qac.v0, NutritionRecord.PANTOTHENIC_ACID_TOTAL, wigVar2);
        ebh.x(qac.w0, NutritionRecord.PHOSPHORUS_TOTAL, wigVar2);
        ebh.x(qac.x0, NutritionRecord.POLYUNSATURATED_FAT_TOTAL, wigVar2);
        ebh.x(qac.y0, NutritionRecord.POTASSIUM_TOTAL, wigVar2);
        ebh.x(qac.z0, NutritionRecord.PROTEIN_TOTAL, wigVar2);
        ebh.x(qac.A0, NutritionRecord.RIBOFLAVIN_TOTAL, wigVar2);
        ebh.x(qac.B0, NutritionRecord.SATURATED_FAT_TOTAL, wigVar2);
        ebh.x(qac.C0, NutritionRecord.SELENIUM_TOTAL, wigVar2);
        ebh.x(qac.D0, NutritionRecord.SODIUM_TOTAL, wigVar2);
        ebh.x(qac.E0, NutritionRecord.SUGAR_TOTAL, wigVar2);
        ebh.x(qac.F0, NutritionRecord.THIAMIN_TOTAL, wigVar2);
        ebh.x(qac.G0, NutritionRecord.TOTAL_CARBOHYDRATE_TOTAL, wigVar2);
        ebh.x(qac.H0, NutritionRecord.TOTAL_FAT_TOTAL, wigVar2);
        ebh.x(qac.J0, NutritionRecord.UNSATURATED_FAT_TOTAL, wigVar2);
        ebh.x(qac.K0, NutritionRecord.VITAMIN_A_TOTAL, wigVar2);
        ebh.x(qac.L0, NutritionRecord.VITAMIN_B12_TOTAL, wigVar2);
        ebh.x(qac.M0, NutritionRecord.VITAMIN_B6_TOTAL, wigVar2);
        ebh.x(qac.N0, NutritionRecord.VITAMIN_C_TOTAL, wigVar2);
        ebh.x(qac.O0, NutritionRecord.VITAMIN_D_TOTAL, wigVar2);
        ebh.x(qac.P0, NutritionRecord.VITAMIN_E_TOTAL, wigVar2);
        ebh.x(qac.Q0, NutritionRecord.VITAMIN_K_TOTAL, wigVar2);
        wigVar2.a(new cpc(qac.R0, NutritionRecord.ZINC_TOTAL));
        wigVar2.b(SdkExtensions.getExtensionVersion(34) >= 10 ? new cpc[]{new cpc(qac.I0, NutritionRecord.TRANS_FAT_TOTAL)} : new cpc[0]);
        ArrayList arrayList2 = wigVar2.a;
        f = sta.h0((cpc[]) arrayList2.toArray(new cpc[arrayList2.size()]));
        g = sta.h0(new cpc(g9j.f, WeightRecord.WEIGHT_AVG), new cpc(g9j.g, WeightRecord.WEIGHT_MIN), new cpc(g9j.h, WeightRecord.WEIGHT_MAX));
        h = sta.h0(new cpc(mad.h, PowerRecord.POWER_AVG), new cpc(mad.j, PowerRecord.POWER_MAX), new cpc(mad.i, PowerRecord.POWER_MIN));
        i = sta.r0(SdkExtensions.getExtensionVersion(34) >= 10 ? new cpc[]{new cpc(ys1.q, BloodPressureRecord.DIASTOLIC_AVG), new cpc(ys1.s, BloodPressureRecord.DIASTOLIC_MAX), new cpc(ys1.r, BloodPressureRecord.DIASTOLIC_MIN), new cpc(ys1.n, BloodPressureRecord.SYSTOLIC_AVG), new cpc(ys1.p, BloodPressureRecord.SYSTOLIC_MAX), new cpc(ys1.o, BloodPressureRecord.SYSTOLIC_MIN)} : new cpc[0]);
        j = sta.r0(SdkExtensions.getExtensionVersion(34) >= 13 ? new cpc[]{new cpc(f9g.k, SkinTemperatureRecord.SKIN_TEMPERATURE_DELTA_AVG), new cpc(f9g.m, SkinTemperatureRecord.SKIN_TEMPERATURE_DELTA_MAX), new cpc(f9g.l, SkinTemperatureRecord.SKIN_TEMPERATURE_DELTA_MIN)} : new cpc[0]);
        k = sta.r0(SdkExtensions.getExtensionVersion(34) >= 10 ? new cpc[]{new cpc(dig.h, SpeedRecord.SPEED_AVG), new cpc(dig.j, SpeedRecord.SPEED_MAX), new cpc(dig.i, SpeedRecord.SPEED_MIN)} : new cpc[0]);
        Map mapSingletonMap = Collections.singletonMap(dt8.h, HydrationRecord.VOLUME_TOTAL);
        mapSingletonMap.getClass();
        l = mapSingletonMap;
    }
}
