package defpackage;

/* JADX INFO: loaded from: classes.dex */
public abstract class i54 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = epc.o;
        a = j2;
        b = epc.c;
        c = epc.d;
        d = epc.m;
        long j3 = epc.x;
        e = j3;
        f = epc.h;
        long j4 = epc.f;
        g = j4;
        h = epc.b;
        i = epc.a;
        j = epc.u;
        long j5 = epc.t;
        k = j5;
        l = j5;
        m = epc.v;
        n = epc.A;
        long j6 = epc.z;
        o = j6;
        p = j6;
        q = epc.B;
        r = j4;
        s = epc.p;
        t = epc.G;
        long j7 = epc.F;
        u = j7;
        v = j7;
        w = epc.H;
        x = epc.q;
        y = epc.r;
        z = epc.w;
        long j8 = epc.y;
        A = j8;
        B = j8;
        C = j3;
        D = epc.e;
        E = epc.C;
        long j9 = epc.E;
        F = j9;
        G = j9;
        H = epc.D;
        I = j2;
        J = j2;
        K = epc.l;
        L = epc.k;
        M = epc.j;
        N = epc.n;
        O = epc.g;
        P = epc.i;
        Q = epc.s;
        R = epc.I;
        long j10 = epc.K;
        S = j10;
        T = j10;
        U = epc.J;
    }
}
