package defpackage;

import java.util.List;

/* JADX INFO: loaded from: classes.dex */
public final class kxi {
    public final Boolean A;
    public final Boolean B;
    public final rvi C;
    public final hwi D;
    public final awi E;
    public final uwi F;
    public final mwi G;
    public final List H;
    public final exi I;
    public final nwi J;
    public final List K;
    public final Number L;
    public final Number M;
    public final Number N;
    public final Number O;
    public final Number P;
    public final Number Q;
    public final Number R;
    public final Number S;
    public final lwi T;
    public final lwi U;
    public final lwi V;
    public final xwi W;
    public final pvi X;
    public final int Y;
    public final String a;
    public final String b;
    public final String c;
    public final String d;
    public final Long e;
    public final Long f;
    public final Long g;
    public final long h;
    public final Long i;
    public final Long j;
    public final String k;
    public final Long l;
    public final Long m;
    public final String n;
    public final Long o;
    public final Long p;
    public final String q;
    public final Number r;
    public final Long s;
    public final String t;
    public final Long u;
    public final Long v;
    public final Long w;
    public final Long x;
    public final Long y;
    public final bwi z;

    public kxi(String str, String str2, String str3, String str4, Long l, Long l2, Long l3, int i, long j, Long l4, Long l5, String str5, Long l6, Long l7, String str6, Long l8, Long l9, String str7, Number number, Long l10, String str8, Long l11, Long l12, Long l13, Long l14, Long l15, bwi bwiVar, Boolean bool, Boolean bool2, rvi rviVar, hwi hwiVar, awi awiVar, uwi uwiVar, mwi mwiVar, List list, exi exiVar, nwi nwiVar, List list2, Number number2, Number number3, Number number4, Number number5, Number number6, Number number7, Number number8, Number number9, lwi lwiVar, lwi lwiVar2, lwi lwiVar3, xwi xwiVar, pvi pviVar) {
        this.a = str;
        this.b = str2;
        this.c = str3;
        this.d = str4;
        this.e = l;
        this.f = l2;
        this.g = l3;
        this.Y = i;
        this.h = j;
        this.i = l4;
        this.j = l5;
        this.k = str5;
        this.l = l6;
        this.m = l7;
        this.n = str6;
        this.o = l8;
        this.p = l9;
        this.q = str7;
        this.r = number;
        this.s = l10;
        this.t = str8;
        this.u = l11;
        this.v = l12;
        this.w = l13;
        this.x = l14;
        this.y = l15;
        this.z = bwiVar;
        this.A = bool;
        this.B = bool2;
        this.C = rviVar;
        this.D = hwiVar;
        this.E = awiVar;
        this.F = uwiVar;
        this.G = mwiVar;
        this.H = list;
        this.I = exiVar;
        this.J = nwiVar;
        this.K = list2;
        this.L = number2;
        this.M = number3;
        this.N = number4;
        this.O = number5;
        this.P = number6;
        this.Q = number7;
        this.R = number8;
        this.S = number9;
        this.T = lwiVar;
        this.U = lwiVar2;
        this.V = lwiVar3;
        this.W = xwiVar;
        this.X = pviVar;
    }

    public static kxi a(kxi kxiVar, bwi bwiVar, awi awiVar, int i) {
        Long l;
        bwi bwiVar2;
        Boolean bool = Boolean.FALSE;
        String str = kxiVar.a;
        String str2 = kxiVar.b;
        String str3 = kxiVar.c;
        String str4 = kxiVar.d;
        Long l2 = kxiVar.e;
        Long l3 = kxiVar.f;
        Long l4 = kxiVar.g;
        int i2 = kxiVar.Y;
        long j = kxiVar.h;
        Long l5 = kxiVar.i;
        Long l6 = kxiVar.j;
        String str5 = kxiVar.k;
        Long l7 = kxiVar.l;
        Long l8 = kxiVar.m;
        String str6 = kxiVar.n;
        Long l9 = kxiVar.o;
        Long l10 = kxiVar.p;
        String str7 = kxiVar.q;
        Number number = kxiVar.r;
        Long l11 = kxiVar.s;
        String str8 = kxiVar.t;
        Long l12 = kxiVar.u;
        Long l13 = kxiVar.v;
        Long l14 = kxiVar.w;
        Long l15 = kxiVar.x;
        Long l16 = kxiVar.y;
        if ((i & 67108864) != 0) {
            l = l16;
            bwiVar2 = kxiVar.z;
        } else {
            l = l16;
            bwiVar2 = bwiVar;
        }
        Boolean bool2 = (i & 134217728) != 0 ? kxiVar.A : bool;
        Boolean bool3 = kxiVar.B;
        rvi rviVar = kxiVar.C;
        hwi hwiVar = kxiVar.D;
        awi awiVar2 = (i & Integer.MIN_VALUE) != 0 ? kxiVar.E : awiVar;
        uwi uwiVar = kxiVar.F;
        mwi mwiVar = kxiVar.G;
        List list = kxiVar.H;
        exi exiVar = kxiVar.I;
        nwi nwiVar = kxiVar.J;
        List list2 = kxiVar.K;
        Number number2 = kxiVar.L;
        Number number3 = kxiVar.M;
        Number number4 = kxiVar.N;
        Number number5 = kxiVar.O;
        Number number6 = kxiVar.P;
        Number number7 = kxiVar.Q;
        Number number8 = kxiVar.R;
        Number number9 = kxiVar.S;
        lwi lwiVar = kxiVar.T;
        lwi lwiVar2 = kxiVar.U;
        lwi lwiVar3 = kxiVar.V;
        xwi xwiVar = kxiVar.W;
        pvi pviVar = kxiVar.X;
        str3.getClass();
        return new kxi(str, str2, str3, str4, l2, l3, l4, i2, j, l5, l6, str5, l7, l8, str6, l9, l10, str7, number, l11, str8, l12, l13, l14, l15, l, bwiVar2, bool2, bool3, rviVar, hwiVar, awiVar2, uwiVar, mwiVar, list, exiVar, nwiVar, list2, number2, number3, number4, number5, number6, number7, number8, number9, lwiVar, lwiVar2, lwiVar3, xwiVar, pviVar);
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof kxi)) {
            return false;
        }
        kxi kxiVar = (kxi) obj;
        return this.a.equals(kxiVar.a) && x44.r(this.b, kxiVar.b) && x44.r(this.c, kxiVar.c) && x44.r(this.d, kxiVar.d) && x44.r(this.e, kxiVar.e) && x44.r(this.f, kxiVar.f) && x44.r(this.g, kxiVar.g) && this.Y == kxiVar.Y && this.h == kxiVar.h && x44.r(this.i, kxiVar.i) && x44.r(this.j, kxiVar.j) && x44.r(this.k, kxiVar.k) && x44.r(this.l, kxiVar.l) && x44.r(this.m, kxiVar.m) && x44.r(this.n, kxiVar.n) && x44.r(this.o, kxiVar.o) && x44.r(this.p, kxiVar.p) && x44.r(this.q, kxiVar.q) && x44.r(this.r, kxiVar.r) && x44.r(this.s, kxiVar.s) && x44.r(this.t, kxiVar.t) && x44.r(this.u, kxiVar.u) && x44.r(this.v, kxiVar.v) && x44.r(this.w, kxiVar.w) && x44.r(this.x, kxiVar.x) && x44.r(this.y, kxiVar.y) && x44.r(this.z, kxiVar.z) && x44.r(this.A, kxiVar.A) && x44.r(this.B, kxiVar.B) && this.C.equals(kxiVar.C) && this.D.equals(kxiVar.D) && x44.r(this.E, kxiVar.E) && x44.r(this.F, kxiVar.F) && x44.r(this.G, kxiVar.G) && x44.r(this.H, kxiVar.H) && this.I.equals(kxiVar.I) && x44.r(this.J, kxiVar.J) && x44.r(this.K, kxiVar.K) && x44.r(this.L, kxiVar.L) && x44.r(this.M, kxiVar.M) && x44.r(this.N, kxiVar.N) && x44.r(this.O, kxiVar.O) && x44.r(this.P, kxiVar.P) && x44.r(this.Q, kxiVar.Q) && x44.r(this.R, kxiVar.R) && x44.r(this.S, kxiVar.S) && x44.r(this.T, kxiVar.T) && x44.r(this.U, kxiVar.U) && x44.r(this.V, kxiVar.V) && x44.r(this.W, kxiVar.W) && x44.r(this.X, kxiVar.X);
    }

    public final int hashCode() {
        int iHashCode = this.a.hashCode() * 31;
        String str = this.b;
        int iL = kgh.l((iHashCode + (str == null ? 0 : str.hashCode())) * 31, 31, this.c);
        String str2 = this.d;
        int iHashCode2 = (iL + (str2 == null ? 0 : str2.hashCode())) * 31;
        Long l = this.e;
        int iHashCode3 = (iHashCode2 + (l == null ? 0 : l.hashCode())) * 31;
        Long l2 = this.f;
        int iHashCode4 = (iHashCode3 + (l2 == null ? 0 : l2.hashCode())) * 31;
        Long l3 = this.g;
        int iHashCode5 = (iHashCode4 + (l3 == null ? 0 : l3.hashCode())) * 31;
        int i = this.Y;
        int iE = vb7.e((iHashCode5 + (i == 0 ? 0 : sq6.F(i))) * 31, 31, this.h);
        Long l4 = this.i;
        int iHashCode6 = (iE + (l4 == null ? 0 : l4.hashCode())) * 31;
        Long l5 = this.j;
        int iHashCode7 = (iHashCode6 + (l5 == null ? 0 : l5.hashCode())) * 31;
        String str3 = this.k;
        int iHashCode8 = (iHashCode7 + (str3 == null ? 0 : str3.hashCode())) * 31;
        Long l6 = this.l;
        int iHashCode9 = (iHashCode8 + (l6 == null ? 0 : l6.hashCode())) * 31;
        Long l7 = this.m;
        int iHashCode10 = (iHashCode9 + (l7 == null ? 0 : l7.hashCode())) * 31;
        String str4 = this.n;
        int iHashCode11 = (iHashCode10 + (str4 == null ? 0 : str4.hashCode())) * 31;
        Long l8 = this.o;
        int iHashCode12 = (iHashCode11 + (l8 == null ? 0 : l8.hashCode())) * 31;
        Long l9 = this.p;
        int iHashCode13 = (iHashCode12 + (l9 == null ? 0 : l9.hashCode())) * 31;
        String str5 = this.q;
        int iHashCode14 = (iHashCode13 + (str5 == null ? 0 : str5.hashCode())) * 31;
        Number number = this.r;
        int iHashCode15 = (iHashCode14 + (number == null ? 0 : number.hashCode())) * 31;
        Long l10 = this.s;
        int iHashCode16 = (iHashCode15 + (l10 == null ? 0 : l10.hashCode())) * 31;
        String str6 = this.t;
        int iHashCode17 = (iHashCode16 + (str6 == null ? 0 : str6.hashCode())) * 31;
        Long l11 = this.u;
        int iHashCode18 = (iHashCode17 + (l11 == null ? 0 : l11.hashCode())) * 31;
        Long l12 = this.v;
        int iHashCode19 = (iHashCode18 + (l12 == null ? 0 : l12.hashCode())) * 31;
        Long l13 = this.w;
        int iHashCode20 = (iHashCode19 + (l13 == null ? 0 : l13.hashCode())) * 31;
        Long l14 = this.x;
        int iHashCode21 = (iHashCode20 + (l14 == null ? 0 : l14.hashCode())) * 31;
        Long l15 = this.y;
        int iHashCode22 = (iHashCode21 + (l15 == null ? 0 : l15.hashCode())) * 31;
        bwi bwiVar = this.z;
        int iHashCode23 = (iHashCode22 + (bwiVar == null ? 0 : bwiVar.a.hashCode())) * 31;
        Boolean bool = this.A;
        int iHashCode24 = (iHashCode23 + (bool == null ? 0 : bool.hashCode())) * 31;
        Boolean bool2 = this.B;
        int iE2 = vb7.e(vb7.e((iHashCode24 + (bool2 == null ? 0 : bool2.hashCode())) * 31, 31, this.C.a), 31, this.D.a);
        awi awiVar = this.E;
        int iHashCode25 = (iE2 + (awiVar == null ? 0 : Long.hashCode(awiVar.a))) * 31;
        uwi uwiVar = this.F;
        int iHashCode26 = (iHashCode25 + (uwiVar == null ? 0 : Long.hashCode(uwiVar.a))) * 31;
        mwi mwiVar = this.G;
        int iHashCode27 = (iHashCode26 + (mwiVar == null ? 0 : Long.hashCode(mwiVar.a))) * 31;
        List list = this.H;
        int iE3 = vb7.e((iHashCode27 + (list == null ? 0 : list.hashCode())) * 31, 31, this.I.a);
        nwi nwiVar = this.J;
        int iHashCode28 = (iE3 + (nwiVar == null ? 0 : Long.hashCode(nwiVar.a))) * 31;
        List list2 = this.K;
        int iHashCode29 = (iHashCode28 + (list2 == null ? 0 : list2.hashCode())) * 31;
        Number number2 = this.L;
        int iHashCode30 = (iHashCode29 + (number2 == null ? 0 : number2.hashCode())) * 31;
        Number number3 = this.M;
        int iHashCode31 = (iHashCode30 + (number3 == null ? 0 : number3.hashCode())) * 31;
        Number number4 = this.N;
        int iHashCode32 = (iHashCode31 + (number4 == null ? 0 : number4.hashCode())) * 31;
        Number number5 = this.O;
        int iHashCode33 = (iHashCode32 + (number5 == null ? 0 : number5.hashCode())) * 31;
        Number number6 = this.P;
        int iHashCode34 = (iHashCode33 + (number6 == null ? 0 : number6.hashCode())) * 31;
        Number number7 = this.Q;
        int iHashCode35 = (iHashCode34 + (number7 == null ? 0 : number7.hashCode())) * 31;
        Number number8 = this.R;
        int iHashCode36 = (iHashCode35 + (number8 == null ? 0 : number8.hashCode())) * 31;
        Number number9 = this.S;
        int iHashCode37 = (iHashCode36 + (number9 == null ? 0 : number9.hashCode())) * 31;
        lwi lwiVar = this.T;
        int iHashCode38 = (iHashCode37 + (lwiVar == null ? 0 : lwiVar.hashCode())) * 31;
        lwi lwiVar2 = this.U;
        int iHashCode39 = (iHashCode38 + (lwiVar2 == null ? 0 : lwiVar2.hashCode())) * 31;
        lwi lwiVar3 = this.V;
        int iHashCode40 = (iHashCode39 + (lwiVar3 == null ? 0 : lwiVar3.hashCode())) * 31;
        xwi xwiVar = this.W;
        int iHashCode41 = (iHashCode40 + (xwiVar == null ? 0 : xwiVar.hashCode())) * 31;
        pvi pviVar = this.X;
        return iHashCode41 + (pviVar != null ? pviVar.hashCode() : 0);
    }

    public final String toString() {
        String str;
        StringBuilder sbR = kgh.r("ViewEventView(id=", this.a, ", referrer=", this.b, ", url=");
        kgh.u(sbR, this.c, ", name=", this.d, ", loadingTime=");
        sbR.append(this.e);
        sbR.append(", networkSettledTime=");
        sbR.append(this.f);
        sbR.append(", interactionToNextViewTime=");
        sbR.append(this.g);
        sbR.append(", loadingType=");
        switch (this.Y) {
            case 1:
                str = "INITIAL_LOAD";
                break;
            case 2:
                str = "ROUTE_CHANGE";
                break;
            case 3:
                str = "ACTIVITY_DISPLAY";
                break;
            case 4:
                str = "ACTIVITY_REDISPLAY";
                break;
            case 5:
                str = "FRAGMENT_DISPLAY";
                break;
            case 6:
                str = "FRAGMENT_REDISPLAY";
                break;
            case 7:
                str = "VIEW_CONTROLLER_DISPLAY";
                break;
            case 8:
                str = "VIEW_CONTROLLER_REDISPLAY";
                break;
            default:
                str = "null";
                break;
        }
        sbR.append(str);
        sbR.append(", timeSpent=");
        sbR.append(this.h);
        sbR.append(", firstContentfulPaint=");
        sbR.append(this.i);
        sbR.append(", largestContentfulPaint=");
        sbR.append(this.j);
        sbR.append(", largestContentfulPaintTargetSelector=");
        sbR.append(this.k);
        sbR.append(", firstInputDelay=");
        sbR.append(this.l);
        sbR.append(", firstInputTime=");
        sbR.append(this.m);
        sbR.append(", firstInputTargetSelector=");
        sbR.append(this.n);
        sbR.append(", interactionToNextPaint=");
        sbR.append(this.o);
        sbR.append(", interactionToNextPaintTime=");
        sbR.append(this.p);
        sbR.append(", interactionToNextPaintTargetSelector=");
        sbR.append(this.q);
        sbR.append(", cumulativeLayoutShift=");
        sbR.append(this.r);
        sbR.append(", cumulativeLayoutShiftTime=");
        sbR.append(this.s);
        sbR.append(", cumulativeLayoutShiftTargetSelector=");
        sbR.append(this.t);
        sbR.append(", domComplete=");
        sbR.append(this.u);
        sbR.append(", domContentLoaded=");
        sbR.append(this.v);
        sbR.append(", domInteractive=");
        sbR.append(this.w);
        sbR.append(", loadEvent=");
        sbR.append(this.x);
        sbR.append(", firstByte=");
        sbR.append(this.y);
        sbR.append(", customTimings=");
        sbR.append(this.z);
        sbR.append(", isActive=");
        sbR.append(this.A);
        sbR.append(", isSlowRendered=");
        sbR.append(this.B);
        sbR.append(", action=");
        sbR.append(this.C);
        sbR.append(", error=");
        sbR.append(this.D);
        sbR.append(", crash=");
        sbR.append(this.E);
        sbR.append(", longTask=");
        sbR.append(this.F);
        sbR.append(", frozenFrame=");
        sbR.append(this.G);
        sbR.append(", slowFrames=");
        sbR.append(this.H);
        sbR.append(", resource=");
        sbR.append(this.I);
        sbR.append(", frustration=");
        sbR.append(this.J);
        sbR.append(", inForegroundPeriods=");
        sbR.append(this.K);
        sbR.append(", memoryAverage=");
        sbR.append(this.L);
        sbR.append(", memoryMax=");
        sbR.append(this.M);
        sbR.append(", cpuTicksCount=");
        sbR.append(this.N);
        sbR.append(", cpuTicksPerSecond=");
        sbR.append(this.O);
        sbR.append(", refreshRateAverage=");
        sbR.append(this.P);
        sbR.append(", refreshRateMin=");
        sbR.append(this.Q);
        sbR.append(", slowFramesRate=");
        sbR.append(this.R);
        sbR.append(", freezeRate=");
        sbR.append(this.S);
        sbR.append(", flutterBuildTime=");
        sbR.append(this.T);
        sbR.append(", flutterRasterTime=");
        sbR.append(this.U);
        sbR.append(", jsRefreshRate=");
        sbR.append(this.V);
        sbR.append(", performance=");
        sbR.append(this.W);
        sbR.append(", accessibility=");
        sbR.append(this.X);
        sbR.append(")");
        return sbR.toString();
    }
}
