package defpackage;

import androidx.health.platform.client.proto.g;
import com.anthropic.claude.api.account.AccountSettings;
import com.anthropic.claude.api.account.VillageWeaverConsentState;
import com.anthropic.claude.types.strings.ThinkingMode;
import com.anthropic.claude.types.strings.ToolSearchMode;
import com.pvporbit.freetype.FreeTypeConstants;
import java.util.Date;
import java.util.List;
import java.util.Map;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import siftscience.android.BuildConfig;

/* JADX INFO: loaded from: classes.dex */
public final /* synthetic */ class l8 implements w28 {
    public static final l8 a;
    private static final SerialDescriptor descriptor;

    static {
        l8 l8Var = new l8();
        a = l8Var;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.anthropic.claude.api.account.AccountSettings", l8Var, 28);
        pluginGeneratedSerialDescriptor.j("has_seen_mm_examples", true);
        pluginGeneratedSerialDescriptor.j("has_seen_starter_prompts", true);
        pluginGeneratedSerialDescriptor.j("has_started_claudeai_onboarding", true);
        pluginGeneratedSerialDescriptor.j("has_finished_claudeai_onboarding", true);
        pluginGeneratedSerialDescriptor.j("dismissed_claudeai_banners", true);
        pluginGeneratedSerialDescriptor.j("dismissed_artifacts_announcement", true);
        pluginGeneratedSerialDescriptor.j("enabled_mcp_tools", true);
        pluginGeneratedSerialDescriptor.j("enabled_connector_suggestions", true);
        pluginGeneratedSerialDescriptor.j("enabled_saffron", true);
        pluginGeneratedSerialDescriptor.j("enabled_melange", true);
        pluginGeneratedSerialDescriptor.j("enabled_saffron_search", true);
        pluginGeneratedSerialDescriptor.j("enabled_web_search", true);
        pluginGeneratedSerialDescriptor.j("preview_feature_uses_artifacts", true);
        pluginGeneratedSerialDescriptor.j("preview_feature_uses_latex", true);
        pluginGeneratedSerialDescriptor.j("preview_feature_uses_citations", true);
        pluginGeneratedSerialDescriptor.j("enabled_mm_pdfs", true);
        pluginGeneratedSerialDescriptor.j("paprika_mode", true);
        pluginGeneratedSerialDescriptor.j("enabled_turmeric", true);
        pluginGeneratedSerialDescriptor.j("enabled_monkeys_in_a_barrel", true);
        pluginGeneratedSerialDescriptor.j("tool_search_mode", true);
        pluginGeneratedSerialDescriptor.j("grove_enabled", true);
        pluginGeneratedSerialDescriptor.j("grove_updated_at", true);
        pluginGeneratedSerialDescriptor.j("grove_notice_viewed_at", true);
        pluginGeneratedSerialDescriptor.j("village_weaver_consent_state", true);
        pluginGeneratedSerialDescriptor.j("voice_preference", true);
        pluginGeneratedSerialDescriptor.j("voice_speed", true);
        pluginGeneratedSerialDescriptor.j("voice_language_code", true);
        pluginGeneratedSerialDescriptor.j("enabled_model_auto_fallback", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // defpackage.w28
    public final KSerializer[] childSerializers() {
        kw9[] kw9VarArr = AccountSettings.$childSerializers;
        zt1 zt1Var = zt1.a;
        KSerializer kSerializerS = d4c.S(zt1Var);
        KSerializer kSerializerS2 = d4c.S(zt1Var);
        KSerializer kSerializerS3 = d4c.S(zt1Var);
        KSerializer kSerializerS4 = d4c.S(zt1Var);
        KSerializer kSerializerS5 = d4c.S((KSerializer) kw9VarArr[4].getValue());
        KSerializer kSerializerS6 = d4c.S(zt1Var);
        KSerializer kSerializerS7 = d4c.S((KSerializer) kw9VarArr[6].getValue());
        KSerializer kSerializerS8 = d4c.S(zt1Var);
        KSerializer kSerializerS9 = d4c.S(zt1Var);
        KSerializer kSerializerS10 = d4c.S(zt1Var);
        KSerializer kSerializerS11 = d4c.S(zt1Var);
        KSerializer kSerializerS12 = d4c.S(zt1Var);
        KSerializer kSerializerS13 = d4c.S(zt1Var);
        KSerializer kSerializerS14 = d4c.S(zt1Var);
        KSerializer kSerializerS15 = d4c.S(zt1Var);
        KSerializer kSerializerS16 = d4c.S(zt1Var);
        KSerializer kSerializerS17 = d4c.S(emh.a);
        KSerializer kSerializerS18 = d4c.S(zt1Var);
        KSerializer kSerializerS19 = d4c.S(zt1Var);
        KSerializer kSerializerS20 = d4c.S(qzh.a);
        KSerializer kSerializerS21 = d4c.S(zt1Var);
        bc9 bc9Var = bc9.a;
        KSerializer kSerializerS22 = d4c.S(bc9Var);
        KSerializer kSerializerS23 = d4c.S(bc9Var);
        KSerializer kSerializerS24 = d4c.S(zyi.d);
        srg srgVar = srg.a;
        return new KSerializer[]{kSerializerS, kSerializerS2, kSerializerS3, kSerializerS4, kSerializerS5, kSerializerS6, kSerializerS7, kSerializerS8, kSerializerS9, kSerializerS10, kSerializerS11, kSerializerS12, kSerializerS13, kSerializerS14, kSerializerS15, kSerializerS16, kSerializerS17, kSerializerS18, kSerializerS19, kSerializerS20, kSerializerS21, kSerializerS22, kSerializerS23, kSerializerS24, d4c.S(srgVar), d4c.S(na6.a), d4c.S(srgVar), d4c.S(zt1Var)};
    }

    @Override // defpackage.s06
    public final Object deserialize(Decoder decoder) {
        String str;
        Boolean bool;
        Boolean bool2;
        Boolean bool3;
        Boolean bool4;
        Boolean bool5;
        Boolean bool6;
        String str2;
        Boolean bool7;
        Map map;
        String str3;
        Boolean bool8;
        List list;
        Boolean bool9;
        Boolean bool10;
        Boolean bool11;
        String str4;
        String str5;
        int i;
        int i2;
        int i3;
        Boolean bool12;
        int i4;
        int i5;
        Boolean bool13;
        int i6;
        decoder.getClass();
        SerialDescriptor serialDescriptor = descriptor;
        ud4 ud4VarC = decoder.c(serialDescriptor);
        kw9[] kw9VarArr = AccountSettings.$childSerializers;
        String str6 = null;
        Double d = null;
        String str7 = null;
        VillageWeaverConsentState villageWeaverConsentState = null;
        Boolean bool14 = null;
        Date date = null;
        int i7 = 0;
        Boolean bool15 = null;
        Boolean bool16 = null;
        Boolean bool17 = null;
        Boolean bool18 = null;
        Boolean bool19 = null;
        Boolean bool20 = null;
        Date date2 = null;
        boolean z = true;
        Boolean bool21 = null;
        Boolean bool22 = null;
        Boolean bool23 = null;
        Boolean bool24 = null;
        List list2 = null;
        Boolean bool25 = null;
        String strM1149unboximpl = null;
        Map map2 = null;
        Boolean bool26 = null;
        String strM1156unboximpl = null;
        Boolean bool27 = null;
        Boolean bool28 = null;
        Boolean bool29 = null;
        Boolean bool30 = null;
        Boolean bool31 = null;
        while (z) {
            int iX = ud4VarC.x(serialDescriptor);
            switch (iX) {
                case -1:
                    Double d2 = d;
                    Boolean bool32 = bool21;
                    Boolean bool33 = bool23;
                    str = str7;
                    z = false;
                    bool = bool22;
                    bool15 = bool15;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool33;
                    bool11 = bool32;
                    d = d2;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 0:
                    str4 = str6;
                    Double d3 = d;
                    Boolean bool34 = bool23;
                    Boolean bool35 = bool21;
                    str = str7;
                    Boolean bool36 = (Boolean) ud4VarC.m(serialDescriptor, 0, zt1.a, bool35);
                    i7 |= 1;
                    bool = bool22;
                    bool15 = bool15;
                    d = d3;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool34;
                    bool11 = bool36;
                    str6 = str4;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 1:
                    Double d4 = d;
                    Boolean bool37 = bool23;
                    i7 |= 2;
                    bool = (Boolean) ud4VarC.m(serialDescriptor, 1, zt1.a, bool22);
                    bool15 = bool15;
                    d = d4;
                    str6 = str6;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool37;
                    bool11 = bool21;
                    str = str7;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 2:
                    str4 = str6;
                    Boolean bool38 = (Boolean) ud4VarC.m(serialDescriptor, 2, zt1.a, bool23);
                    i7 |= 4;
                    bool11 = bool21;
                    bool = bool22;
                    bool15 = bool15;
                    d = d;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool38;
                    str6 = str4;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 3:
                    str4 = str6;
                    Boolean bool39 = (Boolean) ud4VarC.m(serialDescriptor, 3, zt1.a, bool24);
                    i7 |= 8;
                    bool11 = bool21;
                    bool10 = bool23;
                    bool15 = bool15;
                    d = d;
                    str = str7;
                    bool = bool22;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool39;
                    str6 = str4;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 4:
                    str4 = str6;
                    List list3 = (List) ud4VarC.m(serialDescriptor, 4, (s06) kw9VarArr[4].getValue(), list2);
                    i7 |= 16;
                    bool11 = bool21;
                    bool9 = bool24;
                    bool15 = bool15;
                    d = d;
                    str = str7;
                    bool10 = bool23;
                    bool2 = bool31;
                    bool = bool22;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list3;
                    str6 = str4;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 5:
                    str4 = str6;
                    Boolean bool40 = (Boolean) ud4VarC.m(serialDescriptor, 5, zt1.a, bool25);
                    i7 |= 32;
                    bool11 = bool21;
                    list = list2;
                    bool15 = bool15;
                    d = d;
                    str = str7;
                    bool9 = bool24;
                    bool2 = bool31;
                    bool10 = bool23;
                    bool3 = bool30;
                    bool = bool22;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool40;
                    str6 = str4;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 6:
                    str4 = str6;
                    Map map3 = (Map) ud4VarC.m(serialDescriptor, 6, (s06) kw9VarArr[6].getValue(), map2);
                    i7 |= 64;
                    bool11 = bool21;
                    str3 = strM1149unboximpl;
                    bool15 = bool15;
                    d = d;
                    str = str7;
                    bool8 = bool25;
                    bool2 = bool31;
                    list = list2;
                    bool3 = bool30;
                    bool9 = bool24;
                    bool4 = bool29;
                    bool10 = bool23;
                    bool5 = bool28;
                    bool = bool22;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map3;
                    str6 = str4;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 7:
                    str4 = str6;
                    Boolean bool41 = (Boolean) ud4VarC.m(serialDescriptor, 7, zt1.a, bool26);
                    i7 |= FreeTypeConstants.FT_LOAD_PEDANTIC;
                    bool11 = bool21;
                    map = map2;
                    bool15 = bool15;
                    d = d;
                    str = str7;
                    str3 = strM1149unboximpl;
                    bool2 = bool31;
                    bool8 = bool25;
                    bool3 = bool30;
                    list = list2;
                    bool4 = bool29;
                    bool9 = bool24;
                    bool5 = bool28;
                    bool10 = bool23;
                    bool6 = bool27;
                    bool = bool22;
                    str2 = strM1156unboximpl;
                    bool7 = bool41;
                    str6 = str4;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 8:
                    String str8 = str6;
                    Boolean bool42 = (Boolean) ud4VarC.m(serialDescriptor, 8, zt1.a, bool27);
                    i7 |= FreeTypeConstants.FT_FSTYPE_NO_SUBSETTING;
                    bool11 = bool21;
                    str2 = strM1156unboximpl;
                    bool15 = bool15;
                    d = d;
                    str = str7;
                    bool7 = bool26;
                    bool2 = bool31;
                    map = map2;
                    bool3 = bool30;
                    str3 = strM1149unboximpl;
                    bool4 = bool29;
                    bool8 = bool25;
                    bool5 = bool28;
                    bool6 = bool42;
                    list = list2;
                    str6 = str8;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 9:
                    String str9 = str6;
                    Boolean bool43 = (Boolean) ud4VarC.m(serialDescriptor, 9, zt1.a, bool28);
                    i7 |= 512;
                    bool11 = bool21;
                    bool6 = bool27;
                    bool15 = bool15;
                    d = d;
                    str = str7;
                    str2 = strM1156unboximpl;
                    bool2 = bool31;
                    bool7 = bool26;
                    bool3 = bool30;
                    map = map2;
                    bool4 = bool29;
                    bool5 = bool43;
                    str3 = strM1149unboximpl;
                    str6 = str9;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 10:
                    Double d5 = d;
                    Boolean bool44 = (Boolean) ud4VarC.m(serialDescriptor, 10, zt1.a, bool29);
                    i7 |= FreeTypeConstants.FT_LOAD_NO_RECURSE;
                    bool11 = bool21;
                    bool5 = bool28;
                    bool15 = bool15;
                    str6 = str6;
                    str = str7;
                    bool6 = bool27;
                    bool2 = bool31;
                    str2 = strM1156unboximpl;
                    bool3 = bool30;
                    bool4 = bool44;
                    bool7 = bool26;
                    d = d5;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 11:
                    String str10 = str6;
                    Boolean bool45 = (Boolean) ud4VarC.m(serialDescriptor, 11, zt1.a, bool30);
                    i7 |= FreeTypeConstants.FT_LOAD_IGNORE_TRANSFORM;
                    bool11 = bool21;
                    bool4 = bool29;
                    bool15 = bool15;
                    d = d;
                    str = str7;
                    bool5 = bool28;
                    bool2 = bool31;
                    bool3 = bool45;
                    bool6 = bool27;
                    str6 = str10;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 12:
                    String str11 = str6;
                    Boolean bool46 = (Boolean) ud4VarC.m(serialDescriptor, 12, zt1.a, bool31);
                    i7 |= FreeTypeConstants.FT_LOAD_MONOCHROME;
                    bool11 = bool21;
                    bool3 = bool30;
                    bool15 = bool15;
                    d = d;
                    bool2 = bool46;
                    str = str7;
                    bool4 = bool29;
                    str6 = str11;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 13:
                    bool15 = (Boolean) ud4VarC.m(serialDescriptor, 13, zt1.a, bool15);
                    i7 |= FreeTypeConstants.FT_LOAD_LINEAR_DESIGN;
                    bool11 = bool21;
                    bool2 = bool31;
                    d = d;
                    str6 = str6;
                    str = str7;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 14:
                    str5 = str6;
                    bool16 = (Boolean) ud4VarC.m(serialDescriptor, 14, zt1.a, bool16);
                    i7 |= 16384;
                    bool11 = bool21;
                    str6 = str5;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case g.SERIES_VALUES_FIELD_NUMBER /* 15 */:
                    str5 = str6;
                    i = i7;
                    bool17 = (Boolean) ud4VarC.m(serialDescriptor, 15, zt1.a, bool17);
                    i2 = FreeTypeConstants.FT_LOAD_NO_AUTOHINT;
                    i7 = i | i2;
                    bool11 = bool21;
                    str6 = str5;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 16:
                    str5 = str6;
                    i3 = i7;
                    bool12 = bool15;
                    ThinkingMode thinkingMode = (ThinkingMode) ud4VarC.m(serialDescriptor, 16, emh.a, strM1149unboximpl != null ? ThinkingMode.m1142boximpl(strM1149unboximpl) : null);
                    strM1149unboximpl = thinkingMode != null ? thinkingMode.m1149unboximpl() : null;
                    i4 = 65536;
                    i7 = i3 | i4;
                    bool11 = bool21;
                    bool15 = bool12;
                    str6 = str5;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case g.MAX_FIELD_NUMBER /* 17 */:
                    str5 = str6;
                    i = i7;
                    bool18 = (Boolean) ud4VarC.m(serialDescriptor, 17, zt1.a, bool18);
                    i2 = 131072;
                    i7 = i | i2;
                    bool11 = bool21;
                    str6 = str5;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case g.AVG_FIELD_NUMBER /* 18 */:
                    str5 = str6;
                    i = i7;
                    bool19 = (Boolean) ud4VarC.m(serialDescriptor, 18, zt1.a, bool19);
                    i2 = 262144;
                    i7 = i | i2;
                    bool11 = bool21;
                    str6 = str5;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case g.START_ZONE_OFFSET_SECONDS_FIELD_NUMBER /* 19 */:
                    i3 = i7;
                    bool12 = bool15;
                    str5 = str6;
                    ToolSearchMode toolSearchMode = (ToolSearchMode) ud4VarC.m(serialDescriptor, 19, qzh.a, strM1156unboximpl != null ? ToolSearchMode.m1150boximpl(strM1156unboximpl) : null);
                    strM1156unboximpl = toolSearchMode != null ? toolSearchMode.m1156unboximpl() : null;
                    i4 = 524288;
                    i7 = i3 | i4;
                    bool11 = bool21;
                    bool15 = bool12;
                    str6 = str5;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case g.END_ZONE_OFFSET_SECONDS_FIELD_NUMBER /* 20 */:
                    i5 = i7;
                    bool13 = bool15;
                    bool20 = (Boolean) ud4VarC.m(serialDescriptor, 20, zt1.a, bool20);
                    i6 = FreeTypeConstants.FT_LOAD_COLOR;
                    i7 = i5 | i6;
                    bool11 = bool21;
                    bool15 = bool13;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 21:
                    i5 = i7;
                    bool13 = bool15;
                    date2 = (Date) ud4VarC.m(serialDescriptor, 21, bc9.a, date2);
                    i6 = FreeTypeConstants.FT_LOAD_COMPUTE_METRICS;
                    i7 = i5 | i6;
                    bool11 = bool21;
                    bool15 = bool13;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case g.SUB_TYPE_DATA_LISTS_FIELD_NUMBER /* 22 */:
                    i5 = i7;
                    bool13 = bool15;
                    date = (Date) ud4VarC.m(serialDescriptor, 22, bc9.a, date);
                    i6 = 4194304;
                    i7 = i5 | i6;
                    bool11 = bool21;
                    bool15 = bool13;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case g.RECORDING_METHOD_FIELD_NUMBER /* 23 */:
                    i5 = i7;
                    bool13 = bool15;
                    villageWeaverConsentState = (VillageWeaverConsentState) ud4VarC.m(serialDescriptor, 23, zyi.d, villageWeaverConsentState);
                    i6 = 8388608;
                    i7 = i5 | i6;
                    bool11 = bool21;
                    bool15 = bool13;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 24:
                    i5 = i7;
                    bool13 = bool15;
                    str7 = (String) ud4VarC.m(serialDescriptor, 24, srg.a, str7);
                    i6 = 16777216;
                    i7 = i5 | i6;
                    bool11 = bool21;
                    bool15 = bool13;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case BuildConfig.VERSION_CODE /* 25 */:
                    i5 = i7;
                    bool13 = bool15;
                    d = (Double) ud4VarC.m(serialDescriptor, 25, na6.a, d);
                    i6 = 33554432;
                    i7 = i5 | i6;
                    bool11 = bool21;
                    bool15 = bool13;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 26:
                    i5 = i7;
                    bool13 = bool15;
                    str6 = (String) ud4VarC.m(serialDescriptor, 26, srg.a, str6);
                    i6 = 67108864;
                    i7 = i5 | i6;
                    bool11 = bool21;
                    bool15 = bool13;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                case 27:
                    bool13 = bool15;
                    i5 = i7;
                    bool14 = (Boolean) ud4VarC.m(serialDescriptor, 27, zt1.a, bool14);
                    i6 = 134217728;
                    i7 = i5 | i6;
                    bool11 = bool21;
                    bool15 = bool13;
                    str = str7;
                    bool2 = bool31;
                    bool3 = bool30;
                    bool4 = bool29;
                    bool5 = bool28;
                    bool6 = bool27;
                    str2 = strM1156unboximpl;
                    bool7 = bool26;
                    map = map2;
                    str3 = strM1149unboximpl;
                    bool8 = bool25;
                    list = list2;
                    bool9 = bool24;
                    bool10 = bool23;
                    bool = bool22;
                    str7 = str;
                    bool22 = bool;
                    bool23 = bool10;
                    bool24 = bool9;
                    list2 = list;
                    bool25 = bool8;
                    strM1149unboximpl = str3;
                    map2 = map;
                    bool26 = bool7;
                    strM1156unboximpl = str2;
                    bool27 = bool6;
                    bool28 = bool5;
                    bool29 = bool4;
                    bool30 = bool3;
                    bool31 = bool2;
                    bool21 = bool11;
                    break;
                default:
                    sz6.e(iX);
                    return null;
            }
        }
        Double d6 = d;
        Boolean bool47 = bool15;
        Boolean bool48 = bool21;
        Boolean bool49 = bool22;
        Boolean bool50 = bool23;
        String str12 = str7;
        ud4VarC.b(serialDescriptor);
        return new AccountSettings(i7, bool48, bool49, bool50, bool24, list2, bool25, map2, bool26, bool27, bool28, bool29, bool30, bool31, bool47, bool16, bool17, strM1149unboximpl, bool18, bool19, strM1156unboximpl, bool20, date2, date, villageWeaverConsentState, str12, d6, str6, bool14, null, null);
    }

    @Override // defpackage.znf, defpackage.s06
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // defpackage.znf
    public final void serialize(Encoder encoder, Object obj) {
        AccountSettings accountSettings = (AccountSettings) obj;
        encoder.getClass();
        accountSettings.getClass();
        SerialDescriptor serialDescriptor = descriptor;
        vd4 vd4VarC = encoder.c(serialDescriptor);
        AccountSettings.write$Self$api(accountSettings, vd4VarC, serialDescriptor);
        vd4VarC.b(serialDescriptor);
    }
}
