package defpackage;

/* JADX INFO: loaded from: classes.dex */
public abstract class llh {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = w54.a;
        a = j2;
        b = w54.b;
        c = j2;
        d = j2;
        e = d54.b;
        f = w54.S;
        long j3 = w54.T;
        g = j3;
        h = j3;
        i = w54.W;
        j = w54.L;
        long j4 = w54.N;
        k = j4;
        l = j4;
        m = w54.Q;
        long j5 = w54.n;
        n = j5;
        long j6 = w54.o;
        o = j6;
        p = w54.q;
        q = w54.r;
        long j7 = w54.t;
        r = j7;
        s = j7;
        long j8 = w54.h;
        t = d54.b(0.4f, j8);
        u = d54.b(0.3f, j8);
        v = d54.b(0.15f, j8);
        w = d54.b(0.15f, j8);
        x = w54.v;
        long j9 = w54.w;
        y = j9;
        z = j9;
        A = w54.z;
        B = w54.c;
        long j10 = w54.d;
        C = d54.b(0.75f, j10);
        D = d54.b(0.5f, j10);
        E = w54.l;
        F = w54.m;
        G = j5;
        H = j6;
        I = w54.F;
        long j11 = w54.G;
        J = j11;
        K = j11;
        L = w54.J;
        M = j10;
        N = w54.i;
        O = w54.j;
    }
}
