package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class m1l {
    public static final iqk A;
    public static final iqk B;
    public static final iqk C;
    public static final iqk D;
    public static final iqk E;
    public static final iqk F;
    public static final iqk G;
    public static final iqk H;
    public static final iqk I;
    public static final iqk J;
    public static final iqk K;
    public static final iqk L;
    public static final iqk M;
    public static final iqk N;
    public static final iqk O;
    public static final iqk P;
    public static final iqk Q;
    public static final iqk R;
    public static final iqk S;
    public static final iqk T;
    public static final iqk U;
    public static final iqk V;
    public static final iqk W;
    public static final iqk X;
    public static final iqk Y;
    public static final iqk Z;
    public static final iqk a;
    public static final iqk a0;
    public static final iqk b;
    public static final iqk b0;
    public static final iqk c;
    public static final iqk c0;
    public static final iqk d;
    public static final iqk e;
    public static final iqk f;
    public static final iqk g;
    public static final iqk h;
    public static final iqk i;
    public static final iqk j;
    public static final iqk k;
    public static final iqk l;
    public static final iqk m;
    public static final iqk n;
    public static final iqk o;
    public static final iqk p;
    public static final iqk q;
    public static final iqk r;
    public static final iqk s;
    public static final iqk t;
    public static final iqk u;
    public static final iqk v;
    public static final iqk w;
    public static final iqk x;
    public static final iqk y;
    public static final iqk z;

    static {
        bm7 bm7Var = new bm7(rpk.a("com.google.android.gms.measurement"), "", "", true, true);
        a = bm7Var.e(10000L, "measurement.ad_id_cache_time");
        b = bm7Var.e(3600000L, "measurement.app_uninstalled_additional_ad_id_cache_time");
        c = bm7Var.g("measurement.config.bundle_for_all_apps_on_backgrounded", true);
        d = bm7Var.e(100L, "measurement.max_bundles_per_iteration");
        e = bm7Var.e(86400000L, "measurement.config.cache_time");
        bm7Var.f("measurement.log_tag", "FA");
        bm7Var.e(0L, "measurement.id.config.experiment_id");
        f = bm7Var.f("measurement.config.url_authority", "app-measurement.com");
        g = bm7Var.f("measurement.config.url_scheme", "https");
        h = bm7Var.e(1000L, "measurement.upload.debug_upload_interval");
        i = bm7Var.e(3600000L, "measurement.session.engagement_interval");
        j = bm7Var.f("measurement.rb.attribution.event_params", "value|currency");
        bm7Var.e(0L, "measurement.id.rb.attribution.app_allowlist");
        k = bm7Var.e(605000L, "measurement.upload.google_signal_max_queue_time");
        l = bm7Var.f("measurement.sgtm.google_signal.url", "https://app-measurement.com/s");
        m = bm7Var.e(4L, "measurement.lifetimevalue.max_currency_tracked");
        n = bm7Var.e(1L, "measurement.dma_consent.max_daily_dcu_realtime_events");
        o = bm7Var.e(100L, "measurement.upload.max_event_parameter_value_length");
        p = bm7Var.e(100000L, "measurement.store.max_stored_events_per_app");
        q = bm7Var.e(50L, "measurement.experiment.max_ids");
        r = bm7Var.e(200L, "measurement.audience.filter_result_max_count");
        s = bm7Var.e(27L, "measurement.upload.max_item_scoped_custom_parameters");
        t = bm7Var.e(7L, "measurement.rb.attribution.client.min_ad_services_version");
        u = bm7Var.e(60000L, "measurement.alarm_manager.minimum_interval");
        v = bm7Var.e(500L, "measurement.upload.minimum_delay");
        w = bm7Var.e(86400000L, "measurement.monitoring.sample_period_millis");
        x = bm7Var.g("measurement.config.notify_trigger_uris_on_backgrounded", true);
        y = bm7Var.f("measurement.rb.attribution.app_allowlist", "com.labpixies.flood,com.sofascore.results,games.spearmint.triplecrush,com.block.juggle,io.supercent.linkedcubic,com.cdtg.gunsound,com.corestudios.storemanagementidle,com.cdgames.fidget3d,io.supercent.burgeridle,io.supercent.pizzaidle,jp.ne.ibis.ibispaintx.app,com.dencreak.dlcalculator,com.ebay.kleinanzeigen,de.wetteronline.wetterapp,com.game.shape.shift,com.champion.cubes,bubbleshooter.orig,com.wolt.android,com.master.hotelmaster,com.games.bus.arrival,com.playstrom.dop2,com.huuuge.casino.slots,com.ig.spider.fighting,com.jura.coloring.page,com.rikkogame.ragdoll2,com.ludo.king,com.sigma.prank.sound.haircut,com.crazy.block.robo.monster.cliffs.craft,com.fugo.wow,com.maps.locator.gps.gpstracker.phone,com.gamovation.tileclub,com.pronetis.ironball2,com.meesho.supply,pdf.pdfreader.viewer.editor.free,com.dino.race.master,com.ig.moto.racing,ai.photo.enhancer.photoclear,com.duolingo,com.candle.magic_piano,com.free.vpn.super.hotspot.open,sg.bigo.live,com.cdg.tictactoe,com.zhiliaoapp.musically.go,com.wildspike.wormszone,com.mast.status.video.edit,com.vyroai.photoeditorone,com.pujiagames.deeeersimulator,com.superbinogo.jungleboyadventure,com.trustedapp.pdfreaderpdfviewer,com.artimind.aiart.artgenerator.artavatar,de.cellular.ottohybrid,com.zeptolab.cats.google,in.crossy.daily_crossword");
        z = bm7Var.e(10000L, "measurement.upload.realtime_upload_interval");
        A = bm7Var.e(604800000L, "measurement.upload.refresh_blacklisted_config_interval");
        bm7Var.e(3600000L, "measurement.config.cache_time.service");
        B = bm7Var.e(5000L, "measurement.service_client.idle_disconnect_millis");
        bm7Var.f("measurement.log_tag.service", "FA-SVC");
        C = bm7Var.f("measurement.sgtm.app_allowlist", "de.zalando.mobile.internal,de.zalando.mobile.internal.debug,de.zalando.lounge.dev,grit.storytel.app,com.rbc.mobile.android,com.rbc.mobile.android,com.dylvian.mango.activities,com.home24.android,com.home24.android.staging,se.lf.mobile.android,se.lf.mobile.android.beta,se.lf.mobile.android.rc,se.lf.mobile.android.test,se.lf.mobile.android.test.debug,com.boots.flagship.android,com.boots.flagshiproi.android,de.zalando.mobile,com.trivago,com.getyourguide.android,es.mobail.meliarewards,se.nansen.coop.debug,se.nansen.coop,se.coop.coop.qa,com.booking,com.google.firebaseengage,com.mse.mseapp.dev,com.mse.mseapp,pl.eobuwie.eobuwieapp,br.com.eventim.mobile.app.Android,ch.ticketcorner.mobile.app.Android,de.eventim.mobile.app.Android,dk.billetlugen.mobile.app.Android,nl.eventim.mobile.app.Android,com.asos.app,com.blueshieldca.prod,dk.magnetix.tivoliapp,matas.matas.internal,nl.omoda,com.thetrainline,com.simo.androidtest,de.aboutyou.mobile.app,com.hometogo,de.casamundo.casamundomobile,it.casevacanz,eu.coolblue.shop,com.stihl.app,com.indeed.android.jobsearch,com.homeretailgroup.argos.android,com.dylvian.mango.activities.pre,se.nansen.coop.qa");
        D = bm7Var.e(86400000L, "measurement.upload.stale_data_deletion_interval");
        E = bm7Var.f("measurement.rb.attribution.uri_authority", "google-analytics.com");
        F = bm7Var.e(1209600000L, "measurement.rb.attribution.max_queue_time");
        G = bm7Var.f("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion");
        H = bm7Var.f("measurement.rb.attribution.query_parameters_to_remove", "");
        I = bm7Var.f("measurement.rb.attribution.uri_scheme", "https");
        J = bm7Var.e(604800000L, "measurement.sdk.attribution.cache.ttl");
        K = bm7Var.e(7200000L, "measurement.redaction.app_instance_id.ttl");
        L = bm7Var.e(43200000L, "measurement.upload.backoff_period");
        M = bm7Var.e(15000L, "measurement.upload.initial_upload_delay_time");
        N = bm7Var.e(3600000L, "measurement.upload.interval");
        O = bm7Var.e(65536L, "measurement.upload.max_bundle_size");
        P = bm7Var.e(100L, "measurement.upload.max_bundles");
        Q = bm7Var.e(500L, "measurement.upload.max_conversions_per_day");
        R = bm7Var.e(1000L, "measurement.upload.max_error_events_per_day");
        S = bm7Var.e(1000L, "measurement.upload.max_events_per_bundle");
        T = bm7Var.e(100000L, "measurement.upload.max_events_per_day");
        U = bm7Var.e(50000L, "measurement.upload.max_public_events_per_day");
        V = bm7Var.e(2419200000L, "measurement.upload.max_queue_time");
        W = bm7Var.e(10L, "measurement.upload.max_realtime_events_per_day");
        X = bm7Var.e(65536L, "measurement.upload.max_batch_size");
        Y = bm7Var.e(6L, "measurement.upload.retry_count");
        Z = bm7Var.e(1800000L, "measurement.upload.retry_time");
        a0 = bm7Var.f("measurement.upload.url", "https://app-measurement.com/a");
        b0 = bm7Var.e(3600000L, "measurement.upload.window_interval");
        c0 = bm7Var.f("measurement.rb.attribution.user_properties", "_npa,npa");
    }
}
