package defpackage;

/* JADX INFO: loaded from: classes.dex */
public abstract class mlh {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = w54.a;
        a = j2;
        long j3 = w54.b;
        b = j3;
        c = j3;
        d = j2;
        e = d54.b;
        f = w54.V;
        long j4 = w54.U;
        g = j4;
        h = j4;
        i = w54.R;
        j = w54.P;
        long j5 = w54.O;
        k = j5;
        l = j5;
        m = w54.K;
        long j6 = w54.c;
        n = j6;
        long j7 = w54.d;
        o = j7;
        p = w54.e;
        q = w54.f;
        long j8 = w54.g;
        r = j8;
        s = j8;
        long j9 = w54.p;
        t = d54.b(0.4f, j9);
        u = d54.b(0.3f, j9);
        v = d54.b(0.15f, j9);
        w = d54.b(0.15f, j9);
        x = w54.y;
        long j10 = w54.x;
        y = j10;
        z = j10;
        A = w54.u;
        B = j6;
        C = d54.b(0.75f, j7);
        D = d54.b(0.5f, j7);
        E = j8;
        F = w54.h;
        G = j6;
        H = j7;
        I = w54.I;
        long j11 = w54.H;
        J = j11;
        K = j11;
        L = w54.E;
        M = w54.r;
        N = w54.m;
        O = w54.k;
    }
}
