package defpackage;

import com.pvporbit.freetype.FreeTypeConstants;

/* JADX INFO: loaded from: classes.dex */
public final class n54 {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public final long K;
    public final long L;
    public final long M;
    public final long N;
    public final long O;
    public final long P;
    public final long Q;
    public final long R;
    public final long S;
    public final long T;
    public final long U;
    public final long V;
    public n02 W;
    public n02 X;
    public n02 Y;
    public nc2 Z;
    public final long a;
    public pgf a0;
    public final long b;
    public uc6 b0;
    public final long c;
    public m2i c0;
    public final long d;
    public ce3 d0;
    public final long e;
    public wl5 e0;
    public final long f;
    public wu8 f0;
    public final long g;
    public wu8 g0;
    public final long h;
    public wu8 h0;
    public final long i;
    public ycb i0;
    public final long j;
    public kyb j0;
    public final long k;
    public x0e k0;
    public final long l;
    public v9g l0;
    public final long m;
    public p0h m0;
    public final long n;
    public ffh n0;
    public final long o;
    public ffh o0;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public n54(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
        this.K = j37;
        this.L = j38;
        this.M = j39;
        this.N = j40;
        this.O = j41;
        this.P = j42;
        this.Q = j43;
        this.R = j44;
        this.S = j45;
        this.T = j46;
        this.U = j47;
        this.V = j48;
    }

    public static n54 a(n54 n54Var, long j, long j2, int i) {
        long j3 = n54Var.a;
        long j4 = n54Var.b;
        long j5 = n54Var.c;
        long j6 = n54Var.d;
        long j7 = n54Var.e;
        long j8 = n54Var.f;
        long j9 = n54Var.g;
        long j10 = n54Var.h;
        long j11 = n54Var.i;
        long j12 = n54Var.j;
        long j13 = n54Var.k;
        if ((i & FreeTypeConstants.FT_LOAD_IGNORE_TRANSFORM) != 0) {
            j = n54Var.l;
        }
        return new n54(j3, j4, j5, j6, j7, j8, j9, j10, j11, j12, j13, j, n54Var.m, (i & FreeTypeConstants.FT_LOAD_LINEAR_DESIGN) != 0 ? n54Var.n : j2, n54Var.o, n54Var.p, n54Var.q, n54Var.r, n54Var.s, n54Var.t, n54Var.u, n54Var.v, n54Var.w, n54Var.x, n54Var.y, n54Var.z, n54Var.A, n54Var.B, n54Var.C, n54Var.D, n54Var.E, n54Var.F, n54Var.G, n54Var.H, n54Var.I, n54Var.J, n54Var.K, n54Var.L, n54Var.M, n54Var.N, n54Var.O, n54Var.P, n54Var.Q, n54Var.R, n54Var.S, n54Var.T, n54Var.U, n54Var.V);
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        y6a.q(this.a, "onPrimary=", sb);
        y6a.q(this.b, "primaryContainer=", sb);
        y6a.q(this.c, "onPrimaryContainer=", sb);
        long j = this.d;
        y6a.q(j, "inversePrimary=", sb);
        y6a.q(this.e, "secondary=", sb);
        y6a.q(this.f, "onSecondary=", sb);
        y6a.q(this.g, "secondaryContainer=", sb);
        y6a.q(this.h, "onSecondaryContainer=", sb);
        y6a.q(this.i, "tertiary=", sb);
        y6a.q(this.j, "onTertiary=", sb);
        y6a.q(this.k, "tertiaryContainer=", sb);
        y6a.q(this.l, "onTertiaryContainer=", sb);
        y6a.q(this.m, "background=", sb);
        y6a.q(this.n, "onBackground=", sb);
        y6a.q(this.o, "surface=", sb);
        y6a.q(this.p, "onSurface=", sb);
        y6a.q(this.q, "surfaceVariant=", sb);
        y6a.q(this.r, "onSurfaceVariant=", sb);
        y6a.q(this.s, "surfaceTint=", sb);
        y6a.q(this.t, "inverseSurface=", sb);
        y6a.q(this.u, "inverseOnSurface=", sb);
        y6a.q(this.v, "error=", sb);
        y6a.q(this.w, "onError=", sb);
        y6a.q(this.x, "errorContainer=", sb);
        y6a.q(this.y, "onErrorContainer=", sb);
        y6a.q(this.z, "outline=", sb);
        y6a.q(this.A, "outlineVariant=", sb);
        y6a.q(this.B, "scrim=", sb);
        y6a.q(this.C, "surfaceBright=", sb);
        y6a.q(this.D, "surfaceDim=", sb);
        y6a.q(this.E, "surfaceContainer=", sb);
        y6a.q(this.F, "surfaceContainerHigh=", sb);
        y6a.q(this.G, "surfaceContainerHighest=", sb);
        y6a.q(this.H, "surfaceContainerLow=", sb);
        y6a.q(this.I, "surfaceContainerLowest=", sb);
        y6a.q(this.J, "primaryFixed=", sb);
        y6a.q(this.K, "primaryFixedDim=", sb);
        y6a.q(this.L, "onPrimaryFixed=", sb);
        y6a.q(j, "onPrimaryFixedVariant=", sb);
        y6a.q(this.N, "secondaryFixed=", sb);
        y6a.q(this.O, "secondaryFixedDim=", sb);
        y6a.q(this.P, "onSecondaryFixed=", sb);
        y6a.q(this.Q, "onSecondaryFixedVariant=", sb);
        y6a.q(this.R, "tertiaryFixed=", sb);
        y6a.q(this.S, "tertiaryFixedDim=", sb);
        y6a.q(this.T, "onTertiaryFixed=", sb);
        y6a.q(this.U, "onTertiaryFixedVariant=", sb);
        sb.append((Object) d54.i(this.V));
        sb.append(')');
        return sb.toString();
    }
}
