package defpackage;

import java.util.List;
import java.util.Set;

/* JADX INFO: loaded from: classes2.dex */
public abstract class px3 {
    public static final List a = x44.X(new ox3("bash", "sh", mp0.Z0(new String[]{"sh", "bash", "zsh"}), sf5.f0("shell"), true), new ox3("csharp", "cs", (Set) null, sf5.f0("c#"), 4), new ox3("css", "css", (Set) null, (Set) null, 12), new ox3("go", "go", (Set) null, (Set) null, 12), new ox3("graphql", "graphql", mp0.Z0(new String[]{"graphql", "gql"}), (Set) null, 8), new ox3("html", "html", mp0.Z0(new String[]{"html", "htm"}), (Set) null, 8), new ox3("java", "java", (Set) null, (Set) null, 12), new ox3("javascript", "js", mp0.Z0(new String[]{"js", "mjs", "cjs", "jsx"}), (Set) null, 8), new ox3("json", "json", (Set) null, (Set) null, 12), new ox3("kotlin", "kt", mp0.Z0(new String[]{"kt", "kts"}), (Set) null, 8), new ox3("less", "less", (Set) null, (Set) null, 12), new ox3("perl", "pl", mp0.Z0(new String[]{"pl", "pm"}), (Set) null, 8), new ox3("php", "php", (Set) null, (Set) null, 12), new ox3("python", "py", (Set) null, (Set) null, 12), new ox3("r", "r", (Set) null, (Set) null, 12), new ox3("ruby", "rb", (Set) null, (Set) null, 12), new ox3("rust", "rs", (Set) null, (Set) null, 12), new ox3("scss", "scss", mp0.Z0(new String[]{"scss", "sass"}), (Set) null, 8), new ox3("sql", "sql", (Set) null, (Set) null, 12), new ox3("swift", "swift", (Set) null, (Set) null, 12), new ox3("typescript", "ts", mp0.Z0(new String[]{"ts", "tsx"}), (Set) null, 8), new ox3("c", "c", mp0.Z0(new String[]{"c", "h"}), (Set) null, 24), new ox3("clojure", "clj", mp0.Z0(new String[]{"clj", "cljs"}), (Set) null, 24), new ox3("cpp", "cpp", mp0.Z0(new String[]{"cpp", "cc", "cxx", "hpp"}), sf5.f0("c++"), 16), new ox3("dart", "dart", (Set) null, (Set) null, 28), new ox3("elixir", "ex", mp0.Z0(new String[]{"ex", "exs"}), (Set) null, 24), new ox3("elm", "elm", (Set) null, (Set) null, 28), new ox3("erlang", "erl", (Set) null, (Set) null, 28), new ox3("fsharp", "fs", mp0.Z0(new String[]{"fs", "fsx"}), (Set) null, 24), new ox3("groovy", "groovy", (Set) null, (Set) null, 28), new ox3("haskell", "hs", (Set) null, (Set) null, 28), new ox3("ini", "ini", (Set) null, (Set) null, 28), new ox3("lua", "lua", (Set) null, (Set) null, 28), new ox3("markdown", "md", (Set) null, (Set) null, 28), new ox3("objectivec", "m", mp0.Z0(new String[]{"m", "mm"}), mp0.Z0(new String[]{"objective-c", "obj-c"}), 16), new ox3("ocaml", "ml", (Set) null, (Set) null, 28), new ox3("protobuf", "proto", (Set) null, (Set) null, 28), new ox3("scala", "scala", (Set) null, (Set) null, 28), new ox3("toml", "toml", (Set) null, (Set) null, 28), new ox3("xml", "xml", mp0.Z0(new String[]{"xml", "vue", "svelte"}), (Set) null, 24), new ox3("yaml", "yaml", mp0.Z0(new String[]{"yaml", "yml"}), (Set) null, 24), new ox3("zig", "zig", (Set) null, (Set) null, 28));
}
