package defpackage;

import android.R;

/* JADX INFO: loaded from: classes2.dex */
public abstract class s0e {
    public static final int[] a = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.anthropic.claude.R.attr.backgroundTint, com.anthropic.claude.R.attr.behavior_draggable, com.anthropic.claude.R.attr.behavior_expandedOffset, com.anthropic.claude.R.attr.behavior_fitToContents, com.anthropic.claude.R.attr.behavior_halfExpandedRatio, com.anthropic.claude.R.attr.behavior_hideable, com.anthropic.claude.R.attr.behavior_peekHeight, com.anthropic.claude.R.attr.behavior_saveFlags, com.anthropic.claude.R.attr.behavior_significantVelocityThreshold, com.anthropic.claude.R.attr.behavior_skipCollapsed, com.anthropic.claude.R.attr.gestureInsetBottomIgnored, com.anthropic.claude.R.attr.marginLeftSystemWindowInsets, com.anthropic.claude.R.attr.marginRightSystemWindowInsets, com.anthropic.claude.R.attr.marginTopSystemWindowInsets, com.anthropic.claude.R.attr.paddingBottomSystemWindowInsets, com.anthropic.claude.R.attr.paddingLeftSystemWindowInsets, com.anthropic.claude.R.attr.paddingRightSystemWindowInsets, com.anthropic.claude.R.attr.paddingTopSystemWindowInsets, com.anthropic.claude.R.attr.shapeAppearance, com.anthropic.claude.R.attr.shapeAppearanceOverlay, com.anthropic.claude.R.attr.shouldRemoveExpandedCorners};
    public static final int[] b = {com.anthropic.claude.R.attr.behavior_autoHide, com.anthropic.claude.R.attr.behavior_autoShrink};
    public static final int[] c = {com.anthropic.claude.R.attr.behavior_autoHide};
    public static final int[] d = {R.attr.inputType, R.attr.popupElevation, com.anthropic.claude.R.attr.simpleItemLayout, com.anthropic.claude.R.attr.simpleItemSelectedColor, com.anthropic.claude.R.attr.simpleItemSelectedRippleColor, com.anthropic.claude.R.attr.simpleItems};
    public static final int[] e = {R.attr.background, R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, R.attr.checkable, com.anthropic.claude.R.attr.backgroundTint, com.anthropic.claude.R.attr.backgroundTintMode, com.anthropic.claude.R.attr.cornerRadius, com.anthropic.claude.R.attr.elevation, com.anthropic.claude.R.attr.icon, com.anthropic.claude.R.attr.iconGravity, com.anthropic.claude.R.attr.iconPadding, com.anthropic.claude.R.attr.iconSize, com.anthropic.claude.R.attr.iconTint, com.anthropic.claude.R.attr.iconTintMode, com.anthropic.claude.R.attr.rippleColor, com.anthropic.claude.R.attr.shapeAppearance, com.anthropic.claude.R.attr.shapeAppearanceOverlay, com.anthropic.claude.R.attr.strokeColor, com.anthropic.claude.R.attr.strokeWidth, com.anthropic.claude.R.attr.toggleCheckedStateOnClick};
    public static final int[] f = {R.attr.button, com.anthropic.claude.R.attr.buttonCompat, com.anthropic.claude.R.attr.buttonIcon, com.anthropic.claude.R.attr.buttonIconTint, com.anthropic.claude.R.attr.buttonIconTintMode, com.anthropic.claude.R.attr.buttonTint, com.anthropic.claude.R.attr.centerIfNoTextEnabled, com.anthropic.claude.R.attr.checkedState, com.anthropic.claude.R.attr.errorAccessibilityLabel, com.anthropic.claude.R.attr.errorShown, com.anthropic.claude.R.attr.useMaterialThemeColors};
    public static final int[] g = {com.anthropic.claude.R.attr.buttonTint, com.anthropic.claude.R.attr.useMaterialThemeColors};
    public static final int[] h = {com.anthropic.claude.R.attr.shapeAppearance, com.anthropic.claude.R.attr.shapeAppearanceOverlay};
    public static final int[] i = {R.attr.letterSpacing, R.attr.lineHeight, com.anthropic.claude.R.attr.lineHeight};
    public static final int[] j = {R.attr.textAppearance, R.attr.lineHeight, com.anthropic.claude.R.attr.lineHeight};
    public static final int[] k = {com.anthropic.claude.R.attr.behavior_overlapTop};
    public static final int[] l = {com.anthropic.claude.R.attr.cornerFamily, com.anthropic.claude.R.attr.cornerFamilyBottomLeft, com.anthropic.claude.R.attr.cornerFamilyBottomRight, com.anthropic.claude.R.attr.cornerFamilyTopLeft, com.anthropic.claude.R.attr.cornerFamilyTopRight, com.anthropic.claude.R.attr.cornerSize, com.anthropic.claude.R.attr.cornerSizeBottomLeft, com.anthropic.claude.R.attr.cornerSizeBottomRight, com.anthropic.claude.R.attr.cornerSizeTopLeft, com.anthropic.claude.R.attr.cornerSizeTopRight};
    public static final int[] m = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.anthropic.claude.R.attr.backgroundTint, com.anthropic.claude.R.attr.behavior_draggable, com.anthropic.claude.R.attr.coplanarSiblingViewId, com.anthropic.claude.R.attr.shapeAppearance, com.anthropic.claude.R.attr.shapeAppearanceOverlay};
    public static final int[] n = {R.attr.textAppearance, com.anthropic.claude.R.attr.enforceMaterialTheme, com.anthropic.claude.R.attr.enforceTextAppearance};
}
