package defpackage;

import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.Set;
import kotlin.reflect.jvm.internal.KotlinReflectionInternalError;

/* JADX INFO: loaded from: classes.dex */
public final class sl9 extends ts9 implements zy7 {
    public final /* synthetic */ int F;
    public final /* synthetic */ xl9 G;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public sl9(xl9 xl9Var, ul9 ul9Var) {
        super(0);
        this.F = 7;
        this.G = xl9Var;
    }

    @Override // defpackage.zy7
    public final Object a() {
        qqb qqbVarT;
        int i = this.F;
        xl9 xl9Var = this.G;
        switch (i) {
            case 0:
                Collection collectionL = xl9Var.l();
                ArrayList arrayList = new ArrayList(x44.y(collectionL, 10));
                Iterator it = collectionL.iterator();
                while (it.hasNext()) {
                    arrayList.add(new lm9(xl9Var, (dm4) it.next()));
                }
                return arrayList;
            case 1:
                return xl9Var.p(xl9Var.getDescriptor().W().G(), 1);
            case 2:
                fab fabVarB0 = xl9Var.getDescriptor().b0();
                fabVarB0.getClass();
                return xl9Var.p(fabVarB0, 1);
            case 3:
                int i2 = xl9.H;
                gh3 gh3VarX = xl9Var.x();
                ece eceVar = ((ul9) xl9Var.G.a()).a;
                wn9 wn9Var = gm9.b[0];
                Object objA = eceVar.a();
                objA.getClass();
                boolean z = gh3VarX.c;
                r06 r06Var = ((hze) objA).a;
                if (z) {
                    bh3 bh3Var = r06Var.t;
                    Set set = bh3.c;
                    qqbVarT = bh3Var.a(gh3VarX, null);
                } else {
                    qqbVarT = kxk.t(r06Var.b, gh3VarX);
                }
                if (qqbVarT != null) {
                    return qqbVarT;
                }
                Class cls = xl9Var.F;
                bce bceVarR = eve.r(cls);
                pr9 pr9Var = bceVarR != null ? (pr9) bceVarR.b.d : null;
                switch (pr9Var != null ? vl9.a[pr9Var.ordinal()] : -1) {
                    case -1:
                    case 6:
                        throw new KotlinReflectionInternalError(grc.s(cls, "Unresolved class: "));
                    case 0:
                    default:
                        mr9.b();
                        return null;
                    case 1:
                    case 2:
                    case 3:
                        pmf.n(grc.s(cls, "Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: "));
                        return null;
                    case 4:
                        pmf.n(grc.s(cls, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: "));
                        return null;
                    case 5:
                        mr9.l("Unknown class: ", cls, " (kind = ", pr9Var);
                        return null;
                }
            case 4:
                return xl9Var.p(xl9Var.getDescriptor().W().G(), 2);
            case 5:
                fab fabVarB02 = xl9Var.getDescriptor().b0();
                fabVarB02.getClass();
                return xl9Var.p(fabVarB02, 2);
            case 6:
                if (xl9Var.F.isAnonymousClass()) {
                    return null;
                }
                gh3 gh3VarX2 = xl9Var.x();
                if (gh3VarX2.c) {
                    return null;
                }
                return gh3VarX2.b().b();
            case 7:
                Class cls2 = xl9Var.F;
                if (cls2.isAnonymousClass()) {
                    return null;
                }
                gh3 gh3VarX3 = xl9Var.x();
                if (!gh3VarX3.c) {
                    String strB = gh3VarX3.i().b();
                    strB.getClass();
                    return strB;
                }
                String simpleName = cls2.getSimpleName();
                Method enclosingMethod = cls2.getEnclosingMethod();
                if (enclosingMethod != null) {
                    return bsg.c1(simpleName, enclosingMethod.getName() + '$', simpleName);
                }
                Constructor<?> enclosingConstructor = cls2.getEnclosingConstructor();
                if (enclosingConstructor == null) {
                    int iF0 = bsg.F0(simpleName, '$', 0, 6);
                    return iF0 == -1 ? simpleName : simpleName.substring(iF0 + 1, simpleName.length());
                }
                return bsg.c1(simpleName, enclosingConstructor.getName() + '$', simpleName);
            default:
                return new ul9(xl9Var);
        }
    }

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public /* synthetic */ sl9(xl9 xl9Var, int i) {
        super(0);
        this.F = i;
        this.G = xl9Var;
    }
}
