package defpackage;

import com.anthropic.claude.R;
import java.util.Map;

/* JADX INFO: loaded from: classes.dex */
public final class ud0 {
    public static final ud0 A;
    public static final ud0 A0;
    public static final ud0 A1;
    public static final ud0 B;
    public static final ud0 B0;
    public static final ud0 B1;
    public static final ud0 C;
    public static final ud0 C0;
    public static final ud0 C1;
    public static final ud0 D;
    public static final ud0 D0;
    public static final ud0 D1;
    public static final ud0 E;
    public static final ud0 E0;
    public static final ud0 E1;
    public static final ud0 F;
    public static final ud0 F0;
    public static final ud0 F1;
    public static final ud0 G;
    public static final ud0 G0;
    public static final ud0 G1;
    public static final ud0 H;
    public static final ud0 H0;
    public static final ud0 H1;
    public static final ud0 I;
    public static final ud0 I0;
    public static final ud0 I1;
    public static final ud0 J;
    public static final ud0 J0;
    public static final ud0 J1;
    public static final ud0 K;
    public static final ud0 K0;
    public static final ud0 K1;
    public static final ud0 L;
    public static final ud0 L0;
    public static final ud0 L1;
    public static final ud0 M;
    public static final ud0 M0;
    public static final ud0 M1;
    public static final ud0 N;
    public static final ud0 N0;
    public static final ud0 N1;
    public static final ud0 O;
    public static final ud0 O0;
    public static final Map O1;
    public static final ud0 P;
    public static final ud0 P0;
    public static final ud0 Q;
    public static final ud0 Q0;
    public static final ud0 R;
    public static final ud0 R0;
    public static final ud0 S;
    public static final ud0 S0;
    public static final ud0 T;
    public static final ud0 T0;
    public static final ud0 U;
    public static final ud0 U0;
    public static final ud0 V;
    public static final ud0 V0;
    public static final ud0 W;
    public static final ud0 W0;
    public static final ud0 X;
    public static final ud0 X0;
    public static final ud0 Y;
    public static final ud0 Y0;
    public static final ud0 Z;
    public static final ud0 Z0;
    public static final ud0 a0;
    public static final ud0 a1;
    public static final ud0 b0;
    public static final ud0 b1;
    public static final ud0 c0;
    public static final ud0 c1;
    public static final ud0 d;
    public static final ud0 d0;
    public static final ud0 d1;
    public static final ud0 e;
    public static final ud0 e0;
    public static final ud0 e1;
    public static final ud0 f;
    public static final ud0 f0;
    public static final ud0 f1;
    public static final ud0 g;
    public static final ud0 g0;
    public static final ud0 g1;
    public static final ud0 h;
    public static final ud0 h0;
    public static final ud0 h1;
    public static final ud0 i;
    public static final ud0 i0;
    public static final ud0 i1;
    public static final ud0 j;
    public static final ud0 j0;
    public static final ud0 j1;
    public static final ud0 k;
    public static final ud0 k0;
    public static final ud0 k1;
    public static final ud0 l;
    public static final ud0 l0;
    public static final ud0 l1;
    public static final ud0 m;
    public static final ud0 m0;
    public static final ud0 m1;
    public static final ud0 n;
    public static final ud0 n0;
    public static final ud0 n1;
    public static final ud0 o;
    public static final ud0 o0;
    public static final ud0 o1;
    public static final ud0 p;
    public static final ud0 p0;
    public static final ud0 p1;
    public static final ud0 q;
    public static final ud0 q0;
    public static final ud0 q1;
    public static final ud0 r;
    public static final ud0 r0;
    public static final ud0 r1;
    public static final ud0 s;
    public static final ud0 s0;
    public static final ud0 s1;
    public static final ud0 t;
    public static final ud0 t0;
    public static final ud0 t1;
    public static final ud0 u;
    public static final ud0 u0;
    public static final ud0 u1;
    public static final ud0 v;
    public static final ud0 v0;
    public static final ud0 v1;
    public static final ud0 w;
    public static final ud0 w0;
    public static final ud0 w1;
    public static final ud0 x;
    public static final ud0 x0;
    public static final ud0 x1;
    public static final ud0 y;
    public static final ud0 y0;
    public static final ud0 y1;
    public static final ud0 z;
    public static final ud0 z0;
    public static final ud0 z1;
    public final String a;
    public final int b;
    public final boolean c;

    static {
        ud0 ud0Var = new ud0("add", R.drawable.anthropicon_add);
        d = ud0Var;
        ud0 ud0Var2 = new ud0("addCircle", R.drawable.anthropicon_add_circle);
        ud0 ud0Var3 = new ud0("addCircleFilled", R.drawable.anthropicon_add_circle_filled);
        ud0 ud0Var4 = new ud0("addSmall", R.drawable.anthropicon_add_small);
        ud0 ud0Var5 = new ud0("agent", R.drawable.anthropicon_agent);
        e = ud0Var5;
        ud0 ud0Var6 = new ud0("agentSimple", R.drawable.anthropicon_agent_simple);
        ud0 ud0Var7 = new ud0("agentsSimple", R.drawable.anthropicon_agents_simple);
        ud0 ud0Var8 = new ud0("alarm", R.drawable.anthropicon_alarm);
        ud0 ud0Var9 = new ud0("alarmSmall", R.drawable.anthropicon_alarm_small);
        ud0 ud0Var10 = new ud0("android", R.drawable.anthropicon_android);
        f = ud0Var10;
        ud0 ud0Var11 = new ud0("ant", R.drawable.anthropicon_ant);
        g = ud0Var11;
        ud0 ud0Var12 = new ud0("apple", R.drawable.anthropicon_apple);
        ud0 ud0Var13 = new ud0("appleFilled", R.drawable.anthropicon_apple_filled);
        ud0 ud0Var14 = new ud0("archive", R.drawable.anthropicon_archive);
        h = ud0Var14;
        ud0 ud0Var15 = new ud0("arrowClockwise", R.drawable.anthropicon_arrow_clockwise);
        i = ud0Var15;
        ud0 ud0Var16 = new ud0("arrowClockwiseSmall", R.drawable.anthropicon_arrow_clockwise_small);
        ud0 ud0Var17 = new ud0("arrowCounterClockwise", R.drawable.anthropicon_arrow_counter_clockwise);
        ud0 ud0Var18 = new ud0("arrowDown", R.drawable.anthropicon_arrow_down, true);
        j = ud0Var18;
        ud0 ud0Var19 = new ud0("arrowDownCircle", R.drawable.anthropicon_arrow_down_circle, true);
        ud0 ud0Var20 = new ud0("arrowDownSmall", R.drawable.anthropicon_arrow_down_small);
        ud0 ud0Var21 = new ud0("arrowInSquare", R.drawable.anthropicon_arrow_in_square);
        ud0 ud0Var22 = new ud0("arrowInSquareSmall", R.drawable.anthropicon_arrow_in_square_small);
        ud0 ud0Var23 = new ud0("arrowLeft", R.drawable.anthropicon_arrow_left, true);
        k = ud0Var23;
        ud0 ud0Var24 = new ud0("arrowLeftCircle", R.drawable.anthropicon_arrow_left_circle, true);
        ud0 ud0Var25 = new ud0("arrowLeftSmall", R.drawable.anthropicon_arrow_left_small, true);
        ud0 ud0Var26 = new ud0("arrowOutSquare", R.drawable.anthropicon_arrow_out_square, true);
        l = ud0Var26;
        ud0 ud0Var27 = new ud0("arrowOutSquareAlt", R.drawable.anthropicon_arrow_out_square_alt, true);
        ud0 ud0Var28 = new ud0("arrowOutSquareSmall", R.drawable.anthropicon_arrow_out_square_small, true);
        ud0 ud0Var29 = new ud0("arrowRight", R.drawable.anthropicon_arrow_right, true);
        m = ud0Var29;
        ud0 ud0Var30 = new ud0("arrowRightCircle", R.drawable.anthropicon_arrow_right_circle, true);
        ud0 ud0Var31 = new ud0("arrowRightSmall", R.drawable.anthropicon_arrow_right_small, true);
        ud0 ud0Var32 = new ud0("arrowSplitRight", R.drawable.anthropicon_arrow_split_right, true);
        n = ud0Var32;
        ud0 ud0Var33 = new ud0("arrowUp", R.drawable.anthropicon_arrow_up);
        o = ud0Var33;
        ud0 ud0Var34 = new ud0("arrowUpCircle", R.drawable.anthropicon_arrow_up_circle, true);
        ud0 ud0Var35 = new ud0("arrowUpSmall", R.drawable.anthropicon_arrow_up_small);
        ud0 ud0Var36 = new ud0("arrowsUpDown", R.drawable.anthropicon_arrows_up_down);
        p = ud0Var36;
        ud0 ud0Var37 = new ud0("artifactFile", R.drawable.anthropicon_artifact_file);
        q = ud0Var37;
        ud0 ud0Var38 = new ud0("artifacts", R.drawable.anthropicon_artifacts);
        r = ud0Var38;
        ud0 ud0Var39 = new ud0("asterix", R.drawable.anthropicon_asterix);
        s = ud0Var39;
        ud0 ud0Var40 = new ud0("atom", R.drawable.anthropicon_atom);
        ud0 ud0Var41 = new ud0("attachment", R.drawable.anthropicon_attachment);
        t = ud0Var41;
        ud0 ud0Var42 = new ud0("attachmentSmall", R.drawable.anthropicon_attachment_small);
        ud0 ud0Var43 = new ud0("binoculars", R.drawable.anthropicon_binoculars);
        u = ud0Var43;
        ud0 ud0Var44 = new ud0("bluetooth", R.drawable.anthropicon_bluetooth);
        v = ud0Var44;
        ud0 ud0Var45 = new ud0("bluetoothSlash", R.drawable.anthropicon_bluetooth_slash);
        ud0 ud0Var46 = new ud0("book", R.drawable.anthropicon_book);
        ud0 ud0Var47 = new ud0("bookText", R.drawable.anthropicon_book_text);
        w = ud0Var47;
        ud0 ud0Var48 = new ud0("box", R.drawable.anthropicon_box);
        ud0 ud0Var49 = new ud0("branch", R.drawable.anthropicon_branch);
        x = ud0Var49;
        ud0 ud0Var50 = new ud0("browse", R.drawable.anthropicon_browse);
        y = ud0Var50;
        ud0 ud0Var51 = new ud0("browseSmall", R.drawable.anthropicon_browse_small);
        ud0 ud0Var52 = new ud0("calendar", R.drawable.anthropicon_calendar);
        z = ud0Var52;
        ud0 ud0Var53 = new ud0("calendarSmall", R.drawable.anthropicon_calendar_small);
        ud0 ud0Var54 = new ud0("camera", R.drawable.anthropicon_camera);
        A = ud0Var54;
        ud0 ud0Var55 = new ud0("cards", R.drawable.anthropicon_cards);
        ud0 ud0Var56 = new ud0("caretDown", R.drawable.anthropicon_caret_down);
        B = ud0Var56;
        ud0 ud0Var57 = new ud0("caretLeft", R.drawable.anthropicon_caret_left, true);
        ud0 ud0Var58 = new ud0("caretLeftSmall", R.drawable.anthropicon_caret_left_small, true);
        ud0 ud0Var59 = new ud0("caretRight", R.drawable.anthropicon_caret_right, true);
        C = ud0Var59;
        ud0 ud0Var60 = new ud0("caretRightSmall", R.drawable.anthropicon_caret_right_small, true);
        ud0 ud0Var61 = new ud0("caretUp", R.drawable.anthropicon_caret_up);
        D = ud0Var61;
        ud0 ud0Var62 = new ud0("caretUpCaretDown", R.drawable.anthropicon_caret_up_caret_down);
        E = ud0Var62;
        ud0 ud0Var63 = new ud0("chart", R.drawable.anthropicon_chart);
        F = ud0Var63;
        ud0 ud0Var64 = new ud0("chartLine", R.drawable.anthropicon_chart_line);
        G = ud0Var64;
        ud0 ud0Var65 = new ud0("chat", R.drawable.anthropicon_chat);
        H = ud0Var65;
        ud0 ud0Var66 = new ud0("chatAdd", R.drawable.anthropicon_chat_add);
        I = ud0Var66;
        ud0 ud0Var67 = new ud0("chatAddFilled", R.drawable.anthropicon_chat_add_filled);
        J = ud0Var67;
        ud0 ud0Var68 = new ud0("chatSmall", R.drawable.anthropicon_chat_small);
        ud0 ud0Var69 = new ud0("chats", R.drawable.anthropicon_chats);
        K = ud0Var69;
        ud0 ud0Var70 = new ud0("chatsSmall", R.drawable.anthropicon_chats_small);
        ud0 ud0Var71 = new ud0("check", R.drawable.anthropicon_check);
        L = ud0Var71;
        ud0 ud0Var72 = new ud0("checkCircle", R.drawable.anthropicon_check_circle);
        M = ud0Var72;
        ud0 ud0Var73 = new ud0("checkCircleFilled", R.drawable.anthropicon_check_circle_filled);
        N = ud0Var73;
        ud0 ud0Var74 = new ud0("checkSmall", R.drawable.anthropicon_check_small);
        ud0 ud0Var75 = new ud0("checklist", R.drawable.anthropicon_checklist);
        O = ud0Var75;
        ud0 ud0Var76 = new ud0("circleSmall", R.drawable.anthropicon_circle_small);
        P = ud0Var76;
        ud0 ud0Var77 = new ud0("click", R.drawable.anthropicon_click);
        ud0 ud0Var78 = new ud0("clickSmall", R.drawable.anthropicon_click_small);
        ud0 ud0Var79 = new ud0("clipboard", R.drawable.anthropicon_clipboard);
        ud0 ud0Var80 = new ud0("clock", R.drawable.anthropicon_clock);
        Q = ud0Var80;
        ud0 ud0Var81 = new ud0("clockSmall", R.drawable.anthropicon_clock_small);
        ud0 ud0Var82 = new ud0("cloud", R.drawable.anthropicon_cloud);
        R = ud0Var82;
        ud0 ud0Var83 = new ud0("code", R.drawable.anthropicon_code);
        S = ud0Var83;
        ud0 ud0Var84 = new ud0("codeAlt", R.drawable.anthropicon_code_alt);
        ud0 ud0Var85 = new ud0("codeBlock", R.drawable.anthropicon_code_block);
        T = ud0Var85;
        ud0 ud0Var86 = new ud0("codeBlockSmall", R.drawable.anthropicon_code_block_small);
        ud0 ud0Var87 = new ud0("codeSmall", R.drawable.anthropicon_code_small);
        ud0 ud0Var88 = new ud0("coffeeCup", R.drawable.anthropicon_coffee_cup);
        ud0 ud0Var89 = new ud0("coffeeCupSmall", R.drawable.anthropicon_coffee_cup_small);
        ud0 ud0Var90 = new ud0("collapse", R.drawable.anthropicon_collapse);
        ud0 ud0Var91 = new ud0("computer", R.drawable.anthropicon_computer);
        U = ud0Var91;
        ud0 ud0Var92 = new ud0("computerSlashSmall", R.drawable.anthropicon_computer_slash_small);
        V = ud0Var92;
        ud0 ud0Var93 = new ud0("computerSmall", R.drawable.anthropicon_computer_small);
        W = ud0Var93;
        ud0 ud0Var94 = new ud0("connector", R.drawable.anthropicon_connector);
        X = ud0Var94;
        ud0 ud0Var95 = new ud0("connectorSmall", R.drawable.anthropicon_connector_small);
        ud0 ud0Var96 = new ud0("copy", R.drawable.anthropicon_copy);
        Y = ud0Var96;
        ud0 ud0Var97 = new ud0("copySmall", R.drawable.anthropicon_copy_small);
        ud0 ud0Var98 = new ud0("create", R.drawable.anthropicon_create);
        ud0 ud0Var99 = new ud0("disconnect", R.drawable.anthropicon_disconnect);
        Z = ud0Var99;
        ud0 ud0Var100 = new ud0("dispatch", R.drawable.anthropicon_dispatch);
        a0 = ud0Var100;
        ud0 ud0Var101 = new ud0("dollarSign", R.drawable.anthropicon_dollar_sign);
        b0 = ud0Var101;
        ud0 ud0Var102 = new ud0("dotsCircle", R.drawable.anthropicon_dots_circle);
        ud0 ud0Var103 = new ud0("dotsHorizontal", R.drawable.anthropicon_dots_horizontal);
        ud0 ud0Var104 = new ud0("dotsHorizontalSmall", R.drawable.anthropicon_dots_horizontal_small);
        ud0 ud0Var105 = new ud0("dotsVertical", R.drawable.anthropicon_dots_vertical);
        c0 = ud0Var105;
        ud0 ud0Var106 = new ud0("dotsVerticalSmall", R.drawable.anthropicon_dots_vertical_small);
        ud0 ud0Var107 = new ud0("download", R.drawable.anthropicon_download);
        d0 = ud0Var107;
        ud0 ud0Var108 = new ud0("downloadSmall", R.drawable.anthropicon_download_small);
        ud0 ud0Var109 = new ud0("edit", R.drawable.anthropicon_edit);
        e0 = ud0Var109;
        ud0 ud0Var110 = new ud0("editSmall", R.drawable.anthropicon_edit_small);
        ud0 ud0Var111 = new ud0("email", R.drawable.anthropicon_email);
        ud0 ud0Var112 = new ud0("emailSmall", R.drawable.anthropicon_email_small);
        ud0 ud0Var113 = new ud0("expand", R.drawable.anthropicon_expand);
        f0 = ud0Var113;
        ud0 ud0Var114 = new ud0("experiment", R.drawable.anthropicon_experiment);
        g0 = ud0Var114;
        ud0 ud0Var115 = new ud0("extendedThinking", R.drawable.anthropicon_extended_thinking);
        h0 = ud0Var115;
        ud0 ud0Var116 = new ud0("extendedThinkingSmall", R.drawable.anthropicon_extended_thinking_small);
        ud0 ud0Var117 = new ud0("eye", R.drawable.anthropicon_eye);
        i0 = ud0Var117;
        ud0 ud0Var118 = new ud0("eyeSlash", R.drawable.anthropicon_eye_slash);
        j0 = ud0Var118;
        ud0 ud0Var119 = new ud0("fastForward", R.drawable.anthropicon_fast_forward);
        ud0 ud0Var120 = new ud0("feedback", R.drawable.anthropicon_feedback);
        k0 = ud0Var120;
        ud0 ud0Var121 = new ud0("file", R.drawable.anthropicon_file);
        l0 = ud0Var121;
        ud0 ud0Var122 = new ud0("fileAdd", R.drawable.anthropicon_file_add);
        m0 = ud0Var122;
        ud0 ud0Var123 = new ud0("fileSmall", R.drawable.anthropicon_file_small);
        ud0 ud0Var124 = new ud0("fileUpload", R.drawable.anthropicon_file_upload);
        n0 = ud0Var124;
        ud0 ud0Var125 = new ud0("files", R.drawable.anthropicon_files);
        o0 = ud0Var125;
        ud0 ud0Var126 = new ud0("filter", R.drawable.anthropicon_filter);
        p0 = ud0Var126;
        ud0 ud0Var127 = new ud0("flag", R.drawable.anthropicon_flag);
        q0 = ud0Var127;
        ud0 ud0Var128 = new ud0("flagSmall", R.drawable.anthropicon_flag_small);
        ud0 ud0Var129 = new ud0("ghost", R.drawable.anthropicon_ghost);
        ud0 ud0Var130 = new ud0("ghostFilled", R.drawable.anthropicon_ghost_filled);
        r0 = ud0Var130;
        ud0 ud0Var131 = new ud0("ghostSmall", R.drawable.anthropicon_ghost_small);
        ud0 ud0Var132 = new ud0("gift", R.drawable.anthropicon_gift);
        s0 = ud0Var132;
        ud0 ud0Var133 = new ud0("github", R.drawable.anthropicon_github);
        t0 = ud0Var133;
        ud0 ud0Var134 = new ud0("githubSmall", R.drawable.anthropicon_github_small);
        ud0 ud0Var135 = new ud0("globe", R.drawable.anthropicon_globe);
        u0 = ud0Var135;
        ud0 ud0Var136 = new ud0("globeSmall", R.drawable.anthropicon_globe_small);
        ud0 ud0Var137 = new ud0("globeSmallAlt", R.drawable.anthropicon_globe_small_alt);
        ud0 ud0Var138 = new ud0("graduationCap", R.drawable.anthropicon_graduation_cap);
        v0 = ud0Var138;
        ud0 ud0Var139 = new ud0("grid", R.drawable.anthropicon_grid);
        w0 = ud0Var139;
        ud0 ud0Var140 = new ud0("hand", R.drawable.anthropicon_hand);
        x0 = ud0Var140;
        ud0 ud0Var141 = new ud0("handHeart", R.drawable.anthropicon_hand_heart);
        ud0 ud0Var142 = new ud0("haptics", R.drawable.anthropicon_haptics);
        y0 = ud0Var142;
        ud0 ud0Var143 = new ud0("help", R.drawable.anthropicon_help);
        z0 = ud0Var143;
        ud0 ud0Var144 = new ud0("helpSmall", R.drawable.anthropicon_help_small);
        ud0 ud0Var145 = new ud0("history", R.drawable.anthropicon_history);
        ud0 ud0Var146 = new ud0("home", R.drawable.anthropicon_home);
        A0 = ud0Var146;
        ud0 ud0Var147 = new ud0("image", R.drawable.anthropicon_image);
        B0 = ud0Var147;
        ud0 ud0Var148 = new ud0("imageSmall", R.drawable.anthropicon_image_small);
        ud0 ud0Var149 = new ud0("images", R.drawable.anthropicon_images);
        ud0 ud0Var150 = new ud0("info", R.drawable.anthropicon_info);
        ud0 ud0Var151 = new ud0("infoCircle", R.drawable.anthropicon_info_circle);
        C0 = ud0Var151;
        ud0 ud0Var152 = new ud0("infoFilled", R.drawable.anthropicon_info_filled);
        D0 = ud0Var152;
        ud0 ud0Var153 = new ud0("infoSmall", R.drawable.anthropicon_info_small);
        ud0 ud0Var154 = new ud0("infoSmallFilled", R.drawable.anthropicon_info_small_filled);
        ud0 ud0Var155 = new ud0("keyboard", R.drawable.anthropicon_keyboard);
        ud0 ud0Var156 = new ud0("knowledge", R.drawable.anthropicon_knowledge);
        ud0 ud0Var157 = new ud0("lightbulb", R.drawable.anthropicon_lightbulb);
        ud0 ud0Var158 = new ud0("lightning", R.drawable.anthropicon_lightning);
        E0 = ud0Var158;
        ud0 ud0Var159 = new ud0("linkSimple", R.drawable.anthropicon_link_simple);
        F0 = ud0Var159;
        ud0 ud0Var160 = new ud0("location", R.drawable.anthropicon_location);
        G0 = ud0Var160;
        ud0 ud0Var161 = new ud0("locationQuestionMark", R.drawable.anthropicon_location_question_mark);
        ud0 ud0Var162 = new ud0("locationSlash", R.drawable.anthropicon_location_slash);
        ud0 ud0Var163 = new ud0("locationSmall", R.drawable.anthropicon_location_small);
        ud0 ud0Var164 = new ud0("lock", R.drawable.anthropicon_lock);
        H0 = ud0Var164;
        ud0 ud0Var165 = new ud0("lockOpen", R.drawable.anthropicon_lock_open);
        ud0 ud0Var166 = new ud0("lockShield", R.drawable.anthropicon_lock_shield);
        I0 = ud0Var166;
        ud0 ud0Var167 = new ud0("lockShieldAlt", R.drawable.anthropicon_lock_shield_alt);
        ud0 ud0Var168 = new ud0("lockSmall", R.drawable.anthropicon_lock_small);
        ud0 ud0Var169 = new ud0("logout", R.drawable.anthropicon_logout, true);
        J0 = ud0Var169;
        ud0 ud0Var170 = new ud0("mailbox", R.drawable.anthropicon_mailbox);
        K0 = ud0Var170;
        ud0 ud0Var171 = new ud0("map", R.drawable.anthropicon_map);
        L0 = ud0Var171;
        ud0 ud0Var172 = new ud0("memory", R.drawable.anthropicon_memory);
        ud0 ud0Var173 = new ud0("mention", R.drawable.anthropicon_mention);
        ud0 ud0Var174 = new ud0("menu", R.drawable.anthropicon_menu);
        M0 = ud0Var174;
        ud0 ud0Var175 = new ud0("microphone", R.drawable.anthropicon_microphone);
        N0 = ud0Var175;
        ud0 ud0Var176 = new ud0("microphoneSlash", R.drawable.anthropicon_microphone_slash);
        O0 = ud0Var176;
        ud0 ud0Var177 = new ud0("minimizeBottomRight", R.drawable.anthropicon_minimize_bottom_right);
        ud0 ud0Var178 = new ud0("minus", R.drawable.anthropicon_minus);
        P0 = ud0Var178;
        ud0 ud0Var179 = new ud0("mobilePhone", R.drawable.anthropicon_mobile_phone);
        Q0 = ud0Var179;
        ud0 ud0Var180 = new ud0("moon", R.drawable.anthropicon_moon);
        R0 = ud0Var180;
        ud0 ud0Var181 = new ud0("note", R.drawable.anthropicon_note);
        ud0 ud0Var182 = new ud0("notification", R.drawable.anthropicon_notification);
        S0 = ud0Var182;
        ud0 ud0Var183 = new ud0("notificationSmall", R.drawable.anthropicon_notification_small);
        ud0 ud0Var184 = new ud0("orbit", R.drawable.anthropicon_orbit);
        ud0 ud0Var185 = new ud0("organization", R.drawable.anthropicon_organization);
        T0 = ud0Var185;
        ud0 ud0Var186 = new ud0("owl", R.drawable.anthropicon_owl);
        ud0 ud0Var187 = new ud0("paperPlane", R.drawable.anthropicon_paper_plane, true);
        U0 = ud0Var187;
        ud0 ud0Var188 = new ud0("pause", R.drawable.anthropicon_pause);
        V0 = ud0Var188;
        ud0 ud0Var189 = new ud0("pauseSmall", R.drawable.anthropicon_pause_small);
        ud0 ud0Var190 = new ud0("phone", R.drawable.anthropicon_phone);
        W0 = ud0Var190;
        ud0 ud0Var191 = new ud0("phoneSmall", R.drawable.anthropicon_phone_small);
        ud0 ud0Var192 = new ud0("placeholder", R.drawable.anthropicon_placeholder);
        X0 = ud0Var192;
        ud0 ud0Var193 = new ud0("placeholderSmall", R.drawable.anthropicon_placeholder_small);
        ud0 ud0Var194 = new ud0("play", R.drawable.anthropicon_play);
        Y0 = ud0Var194;
        ud0 ud0Var195 = new ud0("playCircle", R.drawable.anthropicon_play_circle);
        ud0 ud0Var196 = new ud0("playCircleFilled", R.drawable.anthropicon_play_circle_filled);
        Z0 = ud0Var196;
        ud0 ud0Var197 = new ud0("playCircleFilledSmall", R.drawable.anthropicon_play_circle_filled_small);
        ud0 ud0Var198 = new ud0("playCircleSmall", R.drawable.anthropicon_play_circle_small);
        ud0 ud0Var199 = new ud0("playSmall", R.drawable.anthropicon_play_small);
        ud0 ud0Var200 = new ud0("prClosed", R.drawable.anthropicon_pr_closed);
        a1 = ud0Var200;
        ud0 ud0Var201 = new ud0("prDraft", R.drawable.anthropicon_pr_draft);
        b1 = ud0Var201;
        ud0 ud0Var202 = new ud0("prDraftSmall", R.drawable.anthropicon_pr_draft_small);
        ud0 ud0Var203 = new ud0("prMerged", R.drawable.anthropicon_pr_merged);
        c1 = ud0Var203;
        ud0 ud0Var204 = new ud0("prOpen", R.drawable.anthropicon_pr_open);
        d1 = ud0Var204;
        ud0 ud0Var205 = new ud0("prOpenSmall", R.drawable.anthropicon_pr_open_small);
        ud0 ud0Var206 = new ud0("projects", R.drawable.anthropicon_projects);
        e1 = ud0Var206;
        ud0 ud0Var207 = new ud0("projectsSmall", R.drawable.anthropicon_projects_small);
        ud0 ud0Var208 = new ud0("projectsX", R.drawable.anthropicon_projects_x);
        f1 = ud0Var208;
        ud0 ud0Var209 = new ud0("prompt", R.drawable.anthropicon_prompt);
        g1 = ud0Var209;
        ud0 ud0Var210 = new ud0("reorder", R.drawable.anthropicon_reorder);
        h1 = ud0Var210;
        ud0 ud0Var211 = new ud0("research", R.drawable.anthropicon_research);
        i1 = ud0Var211;
        ud0 ud0Var212 = new ud0("scroll", R.drawable.anthropicon_scroll);
        j1 = ud0Var212;
        ud0 ud0Var213 = new ud0("search", R.drawable.anthropicon_search);
        k1 = ud0Var213;
        ud0 ud0Var214 = new ud0("searchCircle", R.drawable.anthropicon_search_circle);
        l1 = ud0Var214;
        ud0 ud0Var215 = new ud0("searchCircleSmall", R.drawable.anthropicon_search_circle_small);
        ud0 ud0Var216 = new ud0("searchSmall", R.drawable.anthropicon_search_small);
        ud0 ud0Var217 = new ud0("select", R.drawable.anthropicon_select);
        m1 = ud0Var217;
        ud0 ud0Var218 = new ud0("settings", R.drawable.anthropicon_settings);
        n1 = ud0Var218;
        ud0 ud0Var219 = new ud0("settingsSmall", R.drawable.anthropicon_settings_small);
        ud0 ud0Var220 = new ud0("shapes", R.drawable.anthropicon_shapes);
        ud0 ud0Var221 = new ud0("share", R.drawable.anthropicon_share);
        o1 = ud0Var221;
        ud0 ud0Var222 = new ud0("shareSmall", R.drawable.anthropicon_share_small);
        ud0 ud0Var223 = new ud0("shuffle", R.drawable.anthropicon_shuffle);
        p1 = ud0Var223;
        ud0 ud0Var224 = new ud0("shuffleSmall", R.drawable.anthropicon_shuffle_small);
        ud0 ud0Var225 = new ud0("signPost", R.drawable.anthropicon_sign_post);
        ud0 ud0Var226 = new ud0("slides", R.drawable.anthropicon_slides);
        ud0 ud0Var227 = new ud0("speaker", R.drawable.anthropicon_speaker);
        q1 = ud0Var227;
        ud0 ud0Var228 = new ud0("speakerSmall", R.drawable.anthropicon_speaker_small);
        ud0 ud0Var229 = new ud0("spinner", R.drawable.anthropicon_spinner);
        ud0 ud0Var230 = new ud0("spinnerSmall", R.drawable.anthropicon_spinner_small);
        ud0 ud0Var231 = new ud0("spreadsheet", R.drawable.anthropicon_spreadsheet);
        ud0 ud0Var232 = new ud0("star", R.drawable.anthropicon_star);
        r1 = ud0Var232;
        ud0 ud0Var233 = new ud0("starFilled", R.drawable.anthropicon_star_filled);
        s1 = ud0Var233;
        ud0 ud0Var234 = new ud0("starSlash", R.drawable.anthropicon_star_slash);
        ud0 ud0Var235 = new ud0("starSmall", R.drawable.anthropicon_star_small);
        ud0 ud0Var236 = new ud0("starSmallFilled", R.drawable.anthropicon_star_small_filled);
        ud0 ud0Var237 = new ud0("stop", R.drawable.anthropicon_stop);
        t1 = ud0Var237;
        ud0 ud0Var238 = new ud0("stopCircle", R.drawable.anthropicon_stop_circle);
        ud0 ud0Var239 = new ud0("stopCircleSmall", R.drawable.anthropicon_stop_circle_small);
        ud0 ud0Var240 = new ud0("stopFilled", R.drawable.anthropicon_stop_filled);
        u1 = ud0Var240;
        ud0 ud0Var241 = new ud0("stopSmall", R.drawable.anthropicon_stop_small);
        ud0 ud0Var242 = new ud0("stopSmallFilled", R.drawable.anthropicon_stop_small_filled);
        ud0 ud0Var243 = new ud0("sun", R.drawable.anthropicon_sun);
        v1 = ud0Var243;
        ud0 ud0Var244 = new ud0("sunHorizon", R.drawable.anthropicon_sun_horizon);
        ud0 ud0Var245 = new ud0("tasks", R.drawable.anthropicon_tasks);
        w1 = ud0Var245;
        ud0 ud0Var246 = new ud0("team", R.drawable.anthropicon_team);
        x1 = ud0Var246;
        ud0 ud0Var247 = new ud0("textAa", R.drawable.anthropicon_text_aa);
        y1 = ud0Var247;
        ud0 ud0Var248 = new ud0("thumbsDown", R.drawable.anthropicon_thumbs_down);
        z1 = ud0Var248;
        ud0 ud0Var249 = new ud0("thumbsDownFilled", R.drawable.anthropicon_thumbs_down_filled);
        ud0 ud0Var250 = new ud0("thumbsDownFilledSmall", R.drawable.anthropicon_thumbs_down_filled_small);
        ud0 ud0Var251 = new ud0("thumbsDownSmall", R.drawable.anthropicon_thumbs_down_small);
        ud0 ud0Var252 = new ud0("thumbsUp", R.drawable.anthropicon_thumbs_up);
        A1 = ud0Var252;
        ud0 ud0Var253 = new ud0("thumbsUpFilled", R.drawable.anthropicon_thumbs_up_filled);
        ud0 ud0Var254 = new ud0("thumbsUpFilledSmall", R.drawable.anthropicon_thumbs_up_filled_small);
        ud0 ud0Var255 = new ud0("thumbsUpSmall", R.drawable.anthropicon_thumbs_up_small);
        ud0 ud0Var256 = new ud0("timer", R.drawable.anthropicon_timer);
        ud0 ud0Var257 = new ud0("timerSmall", R.drawable.anthropicon_timer_small);
        ud0 ud0Var258 = new ud0("toggles", R.drawable.anthropicon_toggles);
        ud0 ud0Var259 = new ud0("tool", R.drawable.anthropicon_tool);
        B1 = ud0Var259;
        ud0 ud0Var260 = new ud0("toolSmall", R.drawable.anthropicon_tool_small);
        ud0 ud0Var261 = new ud0("trash", R.drawable.anthropicon_trash);
        C1 = ud0Var261;
        ud0 ud0Var262 = new ud0("trashSmall", R.drawable.anthropicon_trash_small);
        ud0 ud0Var263 = new ud0("trust", R.drawable.anthropicon_trust);
        ud0 ud0Var264 = new ud0("trustSmall", R.drawable.anthropicon_trust_small);
        ud0 ud0Var265 = new ud0("upload", R.drawable.anthropicon_upload);
        D1 = ud0Var265;
        ud0 ud0Var266 = new ud0("uploadSmall", R.drawable.anthropicon_upload_small);
        ud0 ud0Var267 = new ud0("user", R.drawable.anthropicon_user);
        E1 = ud0Var267;
        ud0 ud0Var268 = new ud0("userCircle", R.drawable.anthropicon_user_circle);
        F1 = ud0Var268;
        ud0 ud0Var269 = new ud0("voice", R.drawable.anthropicon_voice);
        G1 = ud0Var269;
        ud0 ud0Var270 = new ud0("walkieTalkie", R.drawable.anthropicon_walkie_talkie);
        ud0 ud0Var271 = new ud0("walkieTalkieFilled", R.drawable.anthropicon_walkie_talkie_filled);
        ud0 ud0Var272 = new ud0("warning", R.drawable.anthropicon_warning);
        H1 = ud0Var272;
        ud0 ud0Var273 = new ud0("warningCircle", R.drawable.anthropicon_warning_circle);
        I1 = ud0Var273;
        ud0 ud0Var274 = new ud0("warningCircleFilledSmall", R.drawable.anthropicon_warning_circle_filled_small);
        J1 = ud0Var274;
        ud0 ud0Var275 = new ud0("warningCircleSmall", R.drawable.anthropicon_warning_circle_small);
        ud0 ud0Var276 = new ud0("warningFilled", R.drawable.anthropicon_warning_filled);
        K1 = ud0Var276;
        ud0 ud0Var277 = new ud0("warningFilledSmall", R.drawable.anthropicon_warning_filled_small);
        ud0 ud0Var278 = new ud0("warningShield", R.drawable.anthropicon_warning_shield);
        ud0 ud0Var279 = new ud0("warningShieldSmall", R.drawable.anthropicon_warning_shield_small);
        ud0 ud0Var280 = new ud0("warningSmall", R.drawable.anthropicon_warning_small);
        ud0 ud0Var281 = new ud0("wrench", R.drawable.anthropicon_wrench);
        L1 = ud0Var281;
        ud0 ud0Var282 = new ud0("wrenchSmall", R.drawable.anthropicon_wrench_small);
        ud0 ud0Var283 = new ud0("x", R.drawable.anthropicon_x);
        M1 = ud0Var283;
        ud0 ud0Var284 = new ud0("xCircle", R.drawable.anthropicon_x_circle);
        N1 = ud0Var284;
        O1 = sta.h0(zh4.x("add", ud0Var), zh4.x("addCircle", ud0Var2), zh4.x("addCircleFilled", ud0Var3), zh4.x("addSmall", ud0Var4), zh4.x("agent", ud0Var5), zh4.x("agentSimple", ud0Var6), zh4.x("agentsSimple", ud0Var7), zh4.x("alarm", ud0Var8), zh4.x("alarmSmall", ud0Var9), zh4.x("android", ud0Var10), zh4.x("ant", ud0Var11), zh4.x("apple", ud0Var12), zh4.x("appleFilled", ud0Var13), zh4.x("archive", ud0Var14), zh4.x("arrowClockwise", ud0Var15), zh4.x("arrowClockwiseSmall", ud0Var16), zh4.x("arrowCounterClockwise", ud0Var17), zh4.x("arrowDown", ud0Var18), zh4.x("arrowDownCircle", ud0Var19), zh4.x("arrowDownSmall", ud0Var20), zh4.x("arrowInSquare", ud0Var21), zh4.x("arrowInSquareSmall", ud0Var22), zh4.x("arrowLeft", ud0Var23), zh4.x("arrowLeftCircle", ud0Var24), zh4.x("arrowLeftSmall", ud0Var25), zh4.x("arrowOutSquare", ud0Var26), zh4.x("arrowOutSquareAlt", ud0Var27), zh4.x("arrowOutSquareSmall", ud0Var28), zh4.x("arrowRight", ud0Var29), zh4.x("arrowRightCircle", ud0Var30), zh4.x("arrowRightSmall", ud0Var31), zh4.x("arrowSplitRight", ud0Var32), zh4.x("arrowUp", ud0Var33), zh4.x("arrowUpCircle", ud0Var34), zh4.x("arrowUpSmall", ud0Var35), zh4.x("arrowsUpDown", ud0Var36), zh4.x("artifactFile", ud0Var37), zh4.x("artifacts", ud0Var38), zh4.x("asterix", ud0Var39), zh4.x("atom", ud0Var40), zh4.x("attachment", ud0Var41), zh4.x("attachmentSmall", ud0Var42), zh4.x("binoculars", ud0Var43), zh4.x("bluetooth", ud0Var44), zh4.x("bluetoothSlash", ud0Var45), zh4.x("book", ud0Var46), zh4.x("bookText", ud0Var47), zh4.x("box", ud0Var48), zh4.x("branch", ud0Var49), zh4.x("browse", ud0Var50), zh4.x("browseSmall", ud0Var51), zh4.x("calendar", ud0Var52), zh4.x("calendarSmall", ud0Var53), zh4.x("camera", ud0Var54), zh4.x("cards", ud0Var55), zh4.x("caretDown", ud0Var56), zh4.x("caretLeft", ud0Var57), zh4.x("caretLeftSmall", ud0Var58), zh4.x("caretRight", ud0Var59), zh4.x("caretRightSmall", ud0Var60), zh4.x("caretUp", ud0Var61), zh4.x("caretUpCaretDown", ud0Var62), zh4.x("chart", ud0Var63), zh4.x("chartLine", ud0Var64), zh4.x("chat", ud0Var65), zh4.x("chatAdd", ud0Var66), zh4.x("chatAddFilled", ud0Var67), zh4.x("chatSmall", ud0Var68), zh4.x("chats", ud0Var69), zh4.x("chatsSmall", ud0Var70), zh4.x("check", ud0Var71), zh4.x("checkCircle", ud0Var72), zh4.x("checkCircleFilled", ud0Var73), zh4.x("checkSmall", ud0Var74), zh4.x("checklist", ud0Var75), zh4.x("circleSmall", ud0Var76), zh4.x("click", ud0Var77), zh4.x("clickSmall", ud0Var78), zh4.x("clipboard", ud0Var79), zh4.x("clock", ud0Var80), zh4.x("clockSmall", ud0Var81), zh4.x("cloud", ud0Var82), zh4.x("code", ud0Var83), zh4.x("codeAlt", ud0Var84), zh4.x("codeBlock", ud0Var85), zh4.x("codeBlockSmall", ud0Var86), zh4.x("codeSmall", ud0Var87), zh4.x("coffeeCup", ud0Var88), zh4.x("coffeeCupSmall", ud0Var89), zh4.x("collapse", ud0Var90), zh4.x("computer", ud0Var91), zh4.x("computerSlashSmall", ud0Var92), zh4.x("computerSmall", ud0Var93), zh4.x("connector", ud0Var94), zh4.x("connectorSmall", ud0Var95), zh4.x("copy", ud0Var96), zh4.x("copySmall", ud0Var97), zh4.x("create", ud0Var98), zh4.x("disconnect", ud0Var99), zh4.x("dispatch", ud0Var100), zh4.x("dollarSign", ud0Var101), zh4.x("dotsCircle", ud0Var102), zh4.x("dotsHorizontal", ud0Var103), zh4.x("dotsHorizontalSmall", ud0Var104), zh4.x("dotsVertical", ud0Var105), zh4.x("dotsVerticalSmall", ud0Var106), zh4.x("download", ud0Var107), zh4.x("downloadSmall", ud0Var108), zh4.x("edit", ud0Var109), zh4.x("editSmall", ud0Var110), zh4.x("email", ud0Var111), zh4.x("emailSmall", ud0Var112), zh4.x("expand", ud0Var113), zh4.x("experiment", ud0Var114), zh4.x("extendedThinking", ud0Var115), zh4.x("extendedThinkingSmall", ud0Var116), zh4.x("eye", ud0Var117), zh4.x("eyeSlash", ud0Var118), zh4.x("fastForward", ud0Var119), zh4.x("feedback", ud0Var120), zh4.x("file", ud0Var121), zh4.x("fileAdd", ud0Var122), zh4.x("fileSmall", ud0Var123), zh4.x("fileUpload", ud0Var124), zh4.x("files", ud0Var125), zh4.x("filter", ud0Var126), zh4.x("flag", ud0Var127), zh4.x("flagSmall", ud0Var128), zh4.x("ghost", ud0Var129), zh4.x("ghostFilled", ud0Var130), zh4.x("ghostSmall", ud0Var131), zh4.x("gift", ud0Var132), zh4.x("github", ud0Var133), zh4.x("githubSmall", ud0Var134), zh4.x("globe", ud0Var135), zh4.x("globeSmall", ud0Var136), zh4.x("globeSmallAlt", ud0Var137), zh4.x("graduationCap", ud0Var138), zh4.x("grid", ud0Var139), zh4.x("hand", ud0Var140), zh4.x("handHeart", ud0Var141), zh4.x("haptics", ud0Var142), zh4.x("help", ud0Var143), zh4.x("helpSmall", ud0Var144), zh4.x("history", ud0Var145), zh4.x("home", ud0Var146), zh4.x("image", ud0Var147), zh4.x("imageSmall", ud0Var148), zh4.x("images", ud0Var149), zh4.x("info", ud0Var150), zh4.x("infoCircle", ud0Var151), zh4.x("infoFilled", ud0Var152), zh4.x("infoSmall", ud0Var153), zh4.x("infoSmallFilled", ud0Var154), zh4.x("keyboard", ud0Var155), zh4.x("knowledge", ud0Var156), zh4.x("lightbulb", ud0Var157), zh4.x("lightning", ud0Var158), zh4.x("linkSimple", ud0Var159), zh4.x("location", ud0Var160), zh4.x("locationQuestionMark", ud0Var161), zh4.x("locationSlash", ud0Var162), zh4.x("locationSmall", ud0Var163), zh4.x("lock", ud0Var164), zh4.x("lockOpen", ud0Var165), zh4.x("lockShield", ud0Var166), zh4.x("lockShieldAlt", ud0Var167), zh4.x("lockSmall", ud0Var168), zh4.x("logout", ud0Var169), zh4.x("mailbox", ud0Var170), zh4.x("map", ud0Var171), zh4.x("memory", ud0Var172), zh4.x("mention", ud0Var173), zh4.x("menu", ud0Var174), zh4.x("microphone", ud0Var175), zh4.x("microphoneSlash", ud0Var176), zh4.x("minimizeBottomRight", ud0Var177), zh4.x("minus", ud0Var178), zh4.x("mobilePhone", ud0Var179), zh4.x("moon", ud0Var180), zh4.x("note", ud0Var181), zh4.x("notification", ud0Var182), zh4.x("notificationSmall", ud0Var183), zh4.x("orbit", ud0Var184), zh4.x("organization", ud0Var185), zh4.x("owl", ud0Var186), zh4.x("paperPlane", ud0Var187), zh4.x("pause", ud0Var188), zh4.x("pauseSmall", ud0Var189), zh4.x("phone", ud0Var190), zh4.x("phoneSmall", ud0Var191), zh4.x("placeholder", ud0Var192), zh4.x("placeholderSmall", ud0Var193), zh4.x("play", ud0Var194), zh4.x("playCircle", ud0Var195), zh4.x("playCircleFilled", ud0Var196), zh4.x("playCircleFilledSmall", ud0Var197), zh4.x("playCircleSmall", ud0Var198), zh4.x("playSmall", ud0Var199), zh4.x("prClosed", ud0Var200), zh4.x("prDraft", ud0Var201), zh4.x("prDraftSmall", ud0Var202), zh4.x("prMerged", ud0Var203), zh4.x("prOpen", ud0Var204), zh4.x("prOpenSmall", ud0Var205), zh4.x("projects", ud0Var206), zh4.x("projectsSmall", ud0Var207), zh4.x("projectsX", ud0Var208), zh4.x("prompt", ud0Var209), zh4.x("reorder", ud0Var210), zh4.x("research", ud0Var211), zh4.x("scroll", ud0Var212), zh4.x("search", ud0Var213), zh4.x("searchCircle", ud0Var214), zh4.x("searchCircleSmall", ud0Var215), zh4.x("searchSmall", ud0Var216), zh4.x("select", ud0Var217), zh4.x("settings", ud0Var218), zh4.x("settingsSmall", ud0Var219), zh4.x("shapes", ud0Var220), zh4.x("share", ud0Var221), zh4.x("shareSmall", ud0Var222), zh4.x("shuffle", ud0Var223), zh4.x("shuffleSmall", ud0Var224), zh4.x("signPost", ud0Var225), zh4.x("slides", ud0Var226), zh4.x("speaker", ud0Var227), zh4.x("speakerSmall", ud0Var228), zh4.x("spinner", ud0Var229), zh4.x("spinnerSmall", ud0Var230), zh4.x("spreadsheet", ud0Var231), zh4.x("star", ud0Var232), zh4.x("starFilled", ud0Var233), zh4.x("starSlash", ud0Var234), zh4.x("starSmall", ud0Var235), zh4.x("starSmallFilled", ud0Var236), zh4.x("stop", ud0Var237), zh4.x("stopCircle", ud0Var238), zh4.x("stopCircleSmall", ud0Var239), zh4.x("stopFilled", ud0Var240), zh4.x("stopSmall", ud0Var241), zh4.x("stopSmallFilled", ud0Var242), zh4.x("sun", ud0Var243), zh4.x("sunHorizon", ud0Var244), zh4.x("tasks", ud0Var245), zh4.x("team", ud0Var246), zh4.x("textAa", ud0Var247), zh4.x("thumbsDown", ud0Var248), zh4.x("thumbsDownFilled", ud0Var249), zh4.x("thumbsDownFilledSmall", ud0Var250), zh4.x("thumbsDownSmall", ud0Var251), zh4.x("thumbsUp", ud0Var252), zh4.x("thumbsUpFilled", ud0Var253), zh4.x("thumbsUpFilledSmall", ud0Var254), zh4.x("thumbsUpSmall", ud0Var255), zh4.x("timer", ud0Var256), zh4.x("timerSmall", ud0Var257), zh4.x("toggles", ud0Var258), zh4.x("tool", ud0Var259), zh4.x("toolSmall", ud0Var260), zh4.x("trash", ud0Var261), zh4.x("trashSmall", ud0Var262), zh4.x("trust", ud0Var263), zh4.x("trustSmall", ud0Var264), zh4.x("upload", ud0Var265), zh4.x("uploadSmall", ud0Var266), zh4.x("user", ud0Var267), zh4.x("userCircle", ud0Var268), zh4.x("voice", ud0Var269), zh4.x("walkieTalkie", ud0Var270), zh4.x("walkieTalkieFilled", ud0Var271), zh4.x("warning", ud0Var272), zh4.x("warningCircle", ud0Var273), zh4.x("warningCircleFilledSmall", ud0Var274), zh4.x("warningCircleSmall", ud0Var275), zh4.x("warningFilled", ud0Var276), zh4.x("warningFilledSmall", ud0Var277), zh4.x("warningShield", ud0Var278), zh4.x("warningShieldSmall", ud0Var279), zh4.x("warningSmall", ud0Var280), zh4.x("wrench", ud0Var281), zh4.x("wrenchSmall", ud0Var282), zh4.x("x", ud0Var283), zh4.x("xCircle", ud0Var284), zh4.x("xCircleFilled", new ud0("xCircleFilled", R.drawable.anthropicon_x_circle_filled)), zh4.x("xSmall", new ud0("xSmall", R.drawable.anthropicon_x_small)), zh4.x("caretDownSmall", ud0Var56), zh4.x("caretUpSmall", ud0Var61), zh4.x("mapSmall", ud0Var171), zh4.x("reload", ud0Var15), zh4.x("reloadSmall", ud0Var16));
    }

    public ud0(String str, int i2, boolean z2) {
        this.a = str;
        this.b = i2;
        this.c = z2;
    }

    public final String toString() {
        return ij0.i("Anthropicon.", this.a);
    }

    public /* synthetic */ ud0(String str, int i2) {
        this(str, i2, false);
    }
}
