package defpackage;

/* JADX INFO: loaded from: classes3.dex */
public final class v7k implements tac {
    public static final v7k a = new v7k();
    public static final mh7 b = new mh7("systemInfo", ebh.t(fsh.r(orj.class, new qqj(1))));
    public static final mh7 c = new mh7("eventName", ebh.t(fsh.r(orj.class, new qqj(2))));
    public static final mh7 d = new mh7("isThickClient", ebh.t(fsh.r(orj.class, new qqj(37))));
    public static final mh7 e = new mh7("clientType", ebh.t(fsh.r(orj.class, new qqj(61))));
    public static final mh7 f = new mh7("modelDownloadLogEvent", ebh.t(fsh.r(orj.class, new qqj(3))));
    public static final mh7 g = new mh7("customModelLoadLogEvent", ebh.t(fsh.r(orj.class, new qqj(20))));
    public static final mh7 h = new mh7("customModelInferenceLogEvent", ebh.t(fsh.r(orj.class, new qqj(4))));
    public static final mh7 i = new mh7("customModelCreateLogEvent", ebh.t(fsh.r(orj.class, new qqj(29))));
    public static final mh7 j = new mh7("onDeviceFaceDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(5))));
    public static final mh7 k = new mh7("onDeviceFaceLoadLogEvent", ebh.t(fsh.r(orj.class, new qqj(59))));
    public static final mh7 l = new mh7("onDeviceTextDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(6))));
    public static final mh7 m = new mh7("onDeviceTextDetectionLoadLogEvent", ebh.t(fsh.r(orj.class, new qqj(79))));
    public static final mh7 n = new mh7("onDeviceBarcodeDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(7))));
    public static final mh7 o = new mh7("onDeviceBarcodeLoadLogEvent", ebh.t(fsh.r(orj.class, new qqj(58))));
    public static final mh7 p = new mh7("onDeviceImageLabelCreateLogEvent", ebh.t(fsh.r(orj.class, new qqj(48))));
    public static final mh7 q = new mh7("onDeviceImageLabelLoadLogEvent", ebh.t(fsh.r(orj.class, new qqj(49))));
    public static final mh7 r = new mh7("onDeviceImageLabelDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(18))));
    public static final mh7 s = new mh7("onDeviceObjectCreateLogEvent", ebh.t(fsh.r(orj.class, new qqj(26))));
    public static final mh7 t = new mh7("onDeviceObjectLoadLogEvent", ebh.t(fsh.r(orj.class, new qqj(27))));
    public static final mh7 u = new mh7("onDeviceObjectInferenceLogEvent", ebh.t(fsh.r(orj.class, new qqj(28))));
    public static final mh7 v = new mh7("onDevicePoseDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(44))));
    public static final mh7 w = new mh7("onDeviceSegmentationLogEvent", ebh.t(fsh.r(orj.class, new qqj(45))));
    public static final mh7 x = new mh7("onDeviceSmartReplyLogEvent", ebh.t(fsh.r(orj.class, new qqj(19))));
    public static final mh7 y = new mh7("onDeviceLanguageIdentificationLogEvent", ebh.t(fsh.r(orj.class, new qqj(21))));
    public static final mh7 z = new mh7("onDeviceTranslationLogEvent", ebh.t(fsh.r(orj.class, new qqj(22))));
    public static final mh7 A = new mh7("cloudFaceDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(8))));
    public static final mh7 B = new mh7("cloudCropHintDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(9))));
    public static final mh7 C = new mh7("cloudDocumentTextDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(10))));
    public static final mh7 D = new mh7("cloudImagePropertiesDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(11))));
    public static final mh7 E = new mh7("cloudImageLabelDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(12))));
    public static final mh7 F = new mh7("cloudLandmarkDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(13))));
    public static final mh7 G = new mh7("cloudLogoDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(14))));
    public static final mh7 H = new mh7("cloudSafeSearchDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(15))));
    public static final mh7 I = new mh7("cloudTextDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(16))));
    public static final mh7 J = new mh7("cloudWebSearchDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(17))));
    public static final mh7 K = new mh7("automlImageLabelingCreateLogEvent", ebh.t(fsh.r(orj.class, new qqj(23))));
    public static final mh7 L = new mh7("automlImageLabelingLoadLogEvent", ebh.t(fsh.r(orj.class, new qqj(24))));
    public static final mh7 M = new mh7("automlImageLabelingInferenceLogEvent", ebh.t(fsh.r(orj.class, new qqj(25))));
    public static final mh7 N = new mh7("isModelDownloadedLogEvent", ebh.t(fsh.r(orj.class, new qqj(39))));
    public static final mh7 O = new mh7("deleteModelLogEvent", ebh.t(fsh.r(orj.class, new qqj(40))));
    public static final mh7 P = new mh7("aggregatedAutomlImageLabelingInferenceLogEvent", ebh.t(fsh.r(orj.class, new qqj(30))));
    public static final mh7 Q = new mh7("aggregatedCustomModelInferenceLogEvent", ebh.t(fsh.r(orj.class, new qqj(31))));
    public static final mh7 R = new mh7("aggregatedOnDeviceFaceDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(32))));
    public static final mh7 S = new mh7("aggregatedOnDeviceBarcodeDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(33))));
    public static final mh7 T = new mh7("aggregatedOnDeviceImageLabelDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(34))));
    public static final mh7 U = new mh7("aggregatedOnDeviceObjectInferenceLogEvent", ebh.t(fsh.r(orj.class, new qqj(35))));
    public static final mh7 V = new mh7("aggregatedOnDeviceTextDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(36))));
    public static final mh7 W = new mh7("aggregatedOnDevicePoseDetectionLogEvent", ebh.t(fsh.r(orj.class, new qqj(46))));
    public static final mh7 X = new mh7("aggregatedOnDeviceSegmentationLogEvent", ebh.t(fsh.r(orj.class, new qqj(47))));
    public static final mh7 Y = new mh7("pipelineAccelerationInferenceEvents", ebh.t(fsh.r(orj.class, new qqj(69))));
    public static final mh7 Z = new mh7("remoteConfigLogEvent", ebh.t(fsh.r(orj.class, new qqj(42))));
    public static final mh7 a0 = new mh7("inputImageConstructionLogEvent", ebh.t(fsh.r(orj.class, new qqj(50))));
    public static final mh7 b0 = new mh7("leakedHandleEvent", ebh.t(fsh.r(orj.class, new qqj(51))));
    public static final mh7 c0 = new mh7("cameraSourceLogEvent", ebh.t(fsh.r(orj.class, new qqj(52))));
    public static final mh7 d0 = new mh7("imageLabelOptionalModuleLogEvent", ebh.t(fsh.r(orj.class, new qqj(53))));
    public static final mh7 e0 = new mh7("languageIdentificationOptionalModuleLogEvent", ebh.t(fsh.r(orj.class, new qqj(54))));
    public static final mh7 f0 = new mh7("faceDetectionOptionalModuleLogEvent", ebh.t(fsh.r(orj.class, new qqj(60))));
    public static final mh7 g0 = new mh7("nlClassifierOptionalModuleLogEvent", ebh.t(fsh.r(orj.class, new qqj(55))));
    public static final mh7 h0 = new mh7("nlClassifierClientLibraryLogEvent", ebh.t(fsh.r(orj.class, new qqj(56))));
    public static final mh7 i0 = new mh7("accelerationAllowlistLogEvent", ebh.t(fsh.r(orj.class, new qqj(57))));
    public static final mh7 j0 = new mh7("toxicityDetectionCreateEvent", ebh.t(fsh.r(orj.class, new qqj(62))));
    public static final mh7 k0 = new mh7("toxicityDetectionLoadEvent", ebh.t(fsh.r(orj.class, new qqj(63))));
    public static final mh7 l0 = new mh7("toxicityDetectionInferenceEvent", ebh.t(fsh.r(orj.class, new qqj(64))));
    public static final mh7 m0 = new mh7("barcodeDetectionOptionalModuleLogEvent", ebh.t(fsh.r(orj.class, new qqj(65))));
    public static final mh7 n0 = new mh7("customImageLabelOptionalModuleLogEvent", ebh.t(fsh.r(orj.class, new qqj(66))));
    public static final mh7 o0 = new mh7("codeScannerScanApiEvent", ebh.t(fsh.r(orj.class, new qqj(67))));
    public static final mh7 p0 = new mh7("codeScannerOptionalModuleEvent", ebh.t(fsh.r(orj.class, new qqj(68))));
    public static final mh7 q0 = new mh7("onDeviceExplicitContentCreateLogEvent", ebh.t(fsh.r(orj.class, new qqj(70))));
    public static final mh7 r0 = new mh7("onDeviceExplicitContentLoadLogEvent", ebh.t(fsh.r(orj.class, new qqj(71))));
    public static final mh7 s0 = new mh7("onDeviceExplicitContentInferenceLogEvent", ebh.t(fsh.r(orj.class, new qqj(72))));
    public static final mh7 t0 = new mh7("aggregatedOnDeviceExplicitContentLogEvent", ebh.t(fsh.r(orj.class, new qqj(73))));
    public static final mh7 u0 = new mh7("onDeviceSelfieFaceCreateLogEvent", ebh.t(fsh.r(orj.class, new qqj(74))));
    public static final mh7 v0 = new mh7("onDeviceSelfieFaceLoadLogEvent", ebh.t(fsh.r(orj.class, new qqj(75))));
    public static final mh7 w0 = new mh7("onDeviceSelfieFaceLogEvent", ebh.t(fsh.r(orj.class, new qqj(76))));
    public static final mh7 x0 = new mh7("aggregatedOnDeviceSelfieFaceLogEvent", ebh.t(fsh.r(orj.class, new qqj(77))));
    public static final mh7 y0 = new mh7("smartReplyOptionalModuleLogEvent", ebh.t(fsh.r(orj.class, new qqj(78))));

    @Override // defpackage.cn6
    public final void a(Object obj, Object obj2) {
        ymk ymkVar = (ymk) obj;
        uac uacVar = (uac) obj2;
        uacVar.a(b, ymkVar.a);
        uacVar.a(c, ymkVar.b);
        uacVar.a(d, null);
        uacVar.a(e, ymkVar.c);
        uacVar.a(f, null);
        uacVar.a(g, null);
        uacVar.a(h, null);
        uacVar.a(i, null);
        uacVar.a(j, null);
        uacVar.a(k, null);
        uacVar.a(l, null);
        uacVar.a(m, null);
        uacVar.a(n, null);
        uacVar.a(o, null);
        uacVar.a(p, null);
        uacVar.a(q, null);
        uacVar.a(r, null);
        uacVar.a(s, null);
        uacVar.a(t, null);
        uacVar.a(u, null);
        uacVar.a(v, null);
        uacVar.a(w, null);
        uacVar.a(x, null);
        uacVar.a(y, ymkVar.d);
        uacVar.a(z, null);
        uacVar.a(A, null);
        uacVar.a(B, null);
        uacVar.a(C, null);
        uacVar.a(D, null);
        uacVar.a(E, null);
        uacVar.a(F, null);
        uacVar.a(G, null);
        uacVar.a(H, null);
        uacVar.a(I, null);
        uacVar.a(J, null);
        uacVar.a(K, null);
        uacVar.a(L, null);
        uacVar.a(M, null);
        uacVar.a(N, null);
        uacVar.a(O, null);
        uacVar.a(P, null);
        uacVar.a(Q, null);
        uacVar.a(R, null);
        uacVar.a(S, null);
        uacVar.a(T, null);
        uacVar.a(U, null);
        uacVar.a(V, null);
        uacVar.a(W, null);
        uacVar.a(X, null);
        uacVar.a(Y, null);
        uacVar.a(Z, null);
        uacVar.a(a0, null);
        uacVar.a(b0, null);
        uacVar.a(c0, null);
        uacVar.a(d0, null);
        uacVar.a(e0, null);
        uacVar.a(f0, null);
        uacVar.a(g0, null);
        uacVar.a(h0, null);
        uacVar.a(i0, null);
        uacVar.a(j0, null);
        uacVar.a(k0, null);
        uacVar.a(l0, null);
        uacVar.a(m0, null);
        uacVar.a(n0, null);
        uacVar.a(o0, null);
        uacVar.a(p0, null);
        uacVar.a(q0, null);
        uacVar.a(r0, null);
        uacVar.a(s0, null);
        uacVar.a(t0, null);
        uacVar.a(u0, null);
        uacVar.a(v0, null);
        uacVar.a(w0, null);
        uacVar.a(x0, null);
        uacVar.a(y0, null);
    }
}
