package defpackage;

/* JADX INFO: loaded from: classes.dex */
public abstract class y3k {
    public static final hp1 a;
    public static final hp1 b;
    public static final hp1 c;
    public static final hp1 d;
    public static final hp1 e;
    public static final hp1 f;
    public static final hp1 g;
    public static final hp1 h;
    public static final hp1 i;
    public static final hp1 j;
    public static final hp1 k;
    public static final hp1 l;
    public static final hp1 m;
    public static final hp1 n;
    public static final hp1 o;
    public static final hp1 p;
    public static final hp1 q;

    static {
        gp1 gp1VarA = hp1.a();
        gp1VarA.E = 3;
        gp1VarA.G = "Google Play In-app Billing API version is less than 3";
        gp1VarA.b();
        gp1 gp1VarA2 = hp1.a();
        gp1VarA2.E = 3;
        gp1VarA2.G = "Google Play In-app Billing API version is less than 9";
        gp1VarA2.b();
        gp1 gp1VarA3 = hp1.a();
        gp1VarA3.E = 3;
        gp1VarA3.G = "Billing service unavailable on device.";
        a = gp1VarA3.b();
        gp1 gp1VarA4 = hp1.a();
        gp1VarA4.E = 2;
        gp1VarA4.G = "Billing service unavailable on device.";
        b = gp1VarA4.b();
        gp1 gp1VarA5 = hp1.a();
        gp1VarA5.E = 5;
        gp1VarA5.G = "Client is already in the process of connecting to billing service.";
        c = gp1VarA5.b();
        gp1 gp1VarA6 = hp1.a();
        gp1VarA6.E = 5;
        gp1VarA6.G = "The list of SKUs can't be empty.";
        gp1VarA6.b();
        gp1 gp1VarA7 = hp1.a();
        gp1VarA7.E = 5;
        gp1VarA7.G = "SKU type can't be empty.";
        gp1VarA7.b();
        gp1 gp1VarA8 = hp1.a();
        gp1VarA8.E = 5;
        gp1VarA8.G = "Product type can't be empty.";
        d = gp1VarA8.b();
        gp1 gp1VarA9 = hp1.a();
        gp1VarA9.E = -2;
        gp1VarA9.G = "Client does not support extra params.";
        e = gp1VarA9.b();
        gp1 gp1VarA10 = hp1.a();
        gp1VarA10.E = 5;
        gp1VarA10.G = "Invalid purchase token.";
        gp1VarA10.b();
        gp1 gp1VarA11 = hp1.a();
        gp1VarA11.E = 6;
        gp1VarA11.G = "An internal error occurred.";
        f = gp1VarA11.b();
        gp1 gp1VarA12 = hp1.a();
        gp1VarA12.E = 5;
        gp1VarA12.G = "SKU can't be null.";
        gp1VarA12.b();
        gp1 gp1VarA13 = hp1.a();
        gp1VarA13.E = 0;
        g = gp1VarA13.b();
        gp1 gp1VarA14 = hp1.a();
        gp1VarA14.E = -1;
        gp1VarA14.G = "Service connection is disconnected.";
        h = gp1VarA14.b();
        gp1 gp1VarA15 = hp1.a();
        gp1VarA15.E = 2;
        gp1VarA15.G = "Timeout communicating with service.";
        i = gp1VarA15.b();
        gp1 gp1VarA16 = hp1.a();
        gp1VarA16.E = -2;
        gp1VarA16.G = "Client does not support subscriptions.";
        j = gp1VarA16.b();
        gp1 gp1VarA17 = hp1.a();
        gp1VarA17.E = -2;
        gp1VarA17.G = "Client does not support subscriptions update.";
        gp1VarA17.b();
        gp1 gp1VarA18 = hp1.a();
        gp1VarA18.E = -2;
        gp1VarA18.G = "Client does not support get purchase history.";
        gp1VarA18.b();
        gp1 gp1VarA19 = hp1.a();
        gp1VarA19.E = -2;
        gp1VarA19.G = "Client does not support price change confirmation.";
        gp1VarA19.b();
        gp1 gp1VarA20 = hp1.a();
        gp1VarA20.E = -2;
        gp1VarA20.G = "Play Store version installed does not support cross selling products.";
        gp1VarA20.b();
        gp1 gp1VarA21 = hp1.a();
        gp1VarA21.E = -2;
        gp1VarA21.G = "Client does not support multi-item purchases.";
        k = gp1VarA21.b();
        gp1 gp1VarA22 = hp1.a();
        gp1VarA22.E = -2;
        gp1VarA22.G = "Client does not support offer_id_token.";
        l = gp1VarA22.b();
        gp1 gp1VarA23 = hp1.a();
        gp1VarA23.E = -2;
        gp1VarA23.G = "Client does not support ProductDetails.";
        m = gp1VarA23.b();
        gp1 gp1VarA24 = hp1.a();
        gp1VarA24.E = -2;
        gp1VarA24.G = "Client does not support in-app messages.";
        gp1VarA24.b();
        gp1 gp1VarA25 = hp1.a();
        gp1VarA25.E = -2;
        gp1VarA25.G = "Client does not support user choice billing.";
        gp1VarA25.b();
        gp1 gp1VarA26 = hp1.a();
        gp1VarA26.E = -2;
        gp1VarA26.G = "Play Store version installed does not support external offer.";
        gp1VarA26.b();
        gp1 gp1VarA27 = hp1.a();
        gp1VarA27.E = -2;
        gp1VarA27.G = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        gp1VarA27.b();
        gp1 gp1VarA28 = hp1.a();
        gp1VarA28.E = -2;
        gp1VarA28.G = "Play Store version installed does not support querying AutoPay plan purchase.";
        gp1VarA28.b();
        gp1 gp1VarA29 = hp1.a();
        gp1VarA29.E = -2;
        gp1VarA29.G = "Play Store version installed does not support including suspended subscriptions.";
        gp1VarA29.b();
        gp1 gp1VarA30 = hp1.a();
        gp1VarA30.E = 5;
        gp1VarA30.G = "Unknown feature";
        gp1VarA30.b();
        gp1 gp1VarA31 = hp1.a();
        gp1VarA31.E = -2;
        gp1VarA31.G = "Play Store version installed does not support get billing config.";
        n = gp1VarA31.b();
        gp1 gp1VarA32 = hp1.a();
        gp1VarA32.E = -2;
        gp1VarA32.G = "Query product details with serialized docid is not supported.";
        gp1VarA32.b();
        gp1 gp1VarA33 = hp1.a();
        gp1VarA33.E = -2;
        gp1VarA33.G = "Play Store version installed does not support launching external offer flow.";
        gp1VarA33.b();
        gp1 gp1VarA34 = hp1.a();
        gp1VarA34.E = 4;
        gp1VarA34.G = "Item is unavailable for purchase.";
        o = gp1VarA34.b();
        gp1 gp1VarA35 = hp1.a();
        gp1VarA35.E = -2;
        gp1VarA35.G = "Query product details with developer specified account is not supported.";
        gp1VarA35.b();
        gp1 gp1VarA36 = hp1.a();
        gp1VarA36.E = -2;
        gp1VarA36.G = "Play Store version installed does not support alternative billing only.";
        gp1VarA36.b();
        gp1 gp1VarA37 = hp1.a();
        gp1VarA37.E = 5;
        gp1VarA37.G = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        p = gp1VarA37.b();
        gp1 gp1VarA38 = hp1.a();
        gp1VarA38.E = 6;
        gp1VarA38.G = "An error occurred while retrieving billing override.";
        q = gp1VarA38.b();
        gp1 gp1VarA39 = hp1.a();
        gp1VarA39.E = -2;
        gp1VarA39.G = "Play Store version installed does not support the provided billing program.";
        gp1VarA39.b();
        gp1 gp1VarA40 = hp1.a();
        gp1VarA40.E = -2;
        gp1VarA40.G = "Play Store version installed does not support launching external links.";
        gp1VarA40.b();
        gp1 gp1VarA41 = hp1.a();
        gp1VarA41.E = 5;
        gp1VarA41.G = "A DeveloperProvidedBillingListener must be provided when initializing the BillingClient in order to use multiple payment options for this billing program.";
        gp1VarA41.b();
    }

    public static hp1 a(int i2, String str) {
        gp1 gp1VarA = hp1.a();
        gp1VarA.E = i2;
        gp1VarA.G = str;
        return gp1VarA.b();
    }
}
