package defpackage;

/* JADX INFO: loaded from: classes.dex */
public abstract class zai {
    public static final long A;
    public static final long A0;
    public static final z28 A1;
    public static final long B;
    public static final dv7 B0;
    public static final long B1;
    public static final long C;
    public static final z28 C0;
    public static final long C1;
    public static final dv7 D;
    public static final long D0;
    public static final long D1;
    public static final z28 E;
    public static final long E0;
    public static final dv7 E1;
    public static final long F;
    public static final long F0;
    public static final z28 F1;
    public static final long G;
    public static final dv7 G0;
    public static final long G1;
    public static final long H;
    public static final z28 H0;
    public static final long H1;
    public static final dv7 I;
    public static final long I0;
    public static final long I1;
    public static final z28 J;
    public static final long J0;
    public static final dv7 J1;
    public static final long K;
    public static final long K0;
    public static final z28 K1;
    public static final long L;
    public static final dv7 L0;
    public static final long L1;
    public static final long M;
    public static final z28 M0;
    public static final long M1;
    public static final dv7 N;
    public static final long N0;
    public static final long N1;
    public static final z28 O;
    public static final long O0;
    public static final dv7 O1;
    public static final long P;
    public static final long P0;
    public static final z28 P1;
    public static final long Q;
    public static final dv7 Q0;
    public static final long Q1;
    public static final long R;
    public static final z28 R0;
    public static final long R1;
    public static final dv7 S;
    public static final long S0;
    public static final long S1;
    public static final z28 T;
    public static final long T0;
    public static final dv7 T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final dv7 V0;
    public static final long W;
    public static final z28 W0;
    public static final dv7 X;
    public static final long X0;
    public static final z28 Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final z28 a;
    public static final long a0;
    public static final dv7 a1;
    public static final long b;
    public static final long b0;
    public static final z28 b1;
    public static final long c;
    public static final dv7 c0;
    public static final long c1;
    public static final long d;
    public static final z28 d0;
    public static final long d1;
    public static final dv7 e;
    public static final long e0;
    public static final long e1;
    public static final z28 f;
    public static final long f0;
    public static final dv7 f1;
    public static final long g;
    public static final long g0;
    public static final z28 g1;
    public static final long h;
    public static final dv7 h0;
    public static final long h1;
    public static final long i;
    public static final z28 i0;
    public static final long i1;
    public static final dv7 j;
    public static final long j0;
    public static final long j1;
    public static final z28 k;
    public static final long k0;
    public static final dv7 k1;
    public static final long l;
    public static final long l0;
    public static final z28 l1;
    public static final long m;
    public static final dv7 m0;
    public static final long m1;
    public static final long n;
    public static final z28 n0;
    public static final long n1;
    public static final dv7 o;
    public static final long o0;
    public static final long o1;
    public static final z28 p;
    public static final long p0;
    public static final dv7 p1;
    public static final long q;
    public static final long q0;
    public static final z28 q1;
    public static final long r;
    public static final dv7 r0;
    public static final long r1;
    public static final long s;
    public static final z28 s0;
    public static final long s1;
    public static final dv7 t;
    public static final long t0;
    public static final long t1;
    public static final z28 u;
    public static final long u0;
    public static final dv7 u1;
    public static final long v;
    public static final long v0;
    public static final z28 v1;
    public static final long w;
    public static final dv7 w0;
    public static final long w1;
    public static final long x;
    public static final z28 x0;
    public static final long x1;
    public static final dv7 y;
    public static final long y0;
    public static final long y1;
    public static final z28 z;
    public static final long z0;
    public static final dv7 z1;

    static {
        dv7 dv7Var = vbi.a;
        z28 z28Var = xt7.F;
        a = z28Var;
        b = eve.A(24.0d);
        c = eve.B(16);
        d = eve.A(0.5d);
        dv7 dv7Var2 = vbi.c;
        e = dv7Var2;
        f = z28Var;
        g = eve.A(20.0d);
        h = eve.B(14);
        i = eve.A(0.2d);
        j = dv7Var2;
        k = z28Var;
        l = eve.A(16.0d);
        m = eve.B(12);
        n = eve.A(0.4d);
        o = dv7Var2;
        p = z28Var;
        q = eve.A(64.0d);
        r = eve.B(57);
        long jA = eve.A(0.2d);
        eve.n(jA);
        s = eve.L(-clh.c(jA), jA & 1095216660480L);
        t = dv7Var2;
        u = z28Var;
        v = eve.A(52.0d);
        w = eve.B(45);
        x = eve.A(0.0d);
        y = dv7Var2;
        z = z28Var;
        A = eve.A(44.0d);
        B = eve.B(36);
        C = eve.A(0.0d);
        D = dv7Var2;
        E = z28Var;
        F = eve.A(40.0d);
        G = eve.B(32);
        H = eve.A(0.0d);
        I = dv7Var2;
        J = z28Var;
        K = eve.A(36.0d);
        L = eve.B(28);
        M = eve.A(0.0d);
        N = dv7Var2;
        O = z28Var;
        P = eve.A(32.0d);
        Q = eve.B(24);
        R = eve.A(0.0d);
        S = dv7Var2;
        T = z28Var;
        U = eve.A(20.0d);
        V = eve.B(14);
        W = eve.A(0.1d);
        dv7 dv7Var3 = vbi.b;
        X = dv7Var3;
        Y = z28Var;
        Z = eve.A(16.0d);
        a0 = eve.B(12);
        b0 = eve.A(0.5d);
        c0 = dv7Var3;
        d0 = z28Var;
        e0 = eve.A(16.0d);
        f0 = eve.B(11);
        g0 = eve.A(0.5d);
        h0 = dv7Var3;
        i0 = z28Var;
        j0 = eve.A(28.0d);
        k0 = eve.B(22);
        l0 = eve.A(0.0d);
        m0 = dv7Var2;
        n0 = z28Var;
        o0 = eve.A(24.0d);
        p0 = eve.B(16);
        q0 = eve.A(0.2d);
        r0 = dv7Var3;
        s0 = z28Var;
        t0 = eve.A(20.0d);
        u0 = eve.B(14);
        v0 = eve.A(0.1d);
        w0 = dv7Var3;
        x0 = z28Var;
        y0 = eve.A(24.0d);
        z0 = eve.B(16);
        A0 = eve.A(0.15d);
        B0 = dv7Var3;
        C0 = z28Var;
        D0 = eve.A(20.0d);
        E0 = eve.B(14);
        F0 = eve.A(0.25d);
        G0 = dv7Var3;
        H0 = z28Var;
        I0 = eve.A(16.0d);
        J0 = eve.B(12);
        K0 = eve.A(0.4d);
        L0 = dv7Var3;
        M0 = z28Var;
        N0 = eve.A(64.0d);
        O0 = eve.B(57);
        P0 = eve.B(0);
        Q0 = dv7Var3;
        R0 = z28Var;
        S0 = eve.A(52.0d);
        T0 = eve.B(45);
        U0 = eve.B(0);
        V0 = dv7Var3;
        W0 = z28Var;
        X0 = eve.A(44.0d);
        Y0 = eve.B(36);
        Z0 = eve.B(0);
        a1 = dv7Var3;
        b1 = z28Var;
        c1 = eve.A(40.0d);
        d1 = eve.B(32);
        e1 = eve.B(0);
        f1 = dv7Var3;
        g1 = z28Var;
        h1 = eve.A(36.0d);
        i1 = eve.B(28);
        j1 = eve.B(0);
        k1 = dv7Var3;
        l1 = z28Var;
        m1 = eve.A(32.0d);
        n1 = eve.B(24);
        o1 = eve.B(0);
        p1 = dv7Var3;
        q1 = z28Var;
        r1 = eve.A(20.0d);
        s1 = eve.B(14);
        t1 = eve.A(0.1d);
        dv7 dv7Var4 = vbi.a;
        u1 = dv7Var4;
        v1 = z28Var;
        w1 = eve.A(16.0d);
        x1 = eve.B(12);
        y1 = eve.A(0.5d);
        z1 = dv7Var4;
        A1 = z28Var;
        B1 = eve.A(16.0d);
        C1 = eve.B(11);
        D1 = eve.A(0.5d);
        E1 = dv7Var4;
        F1 = z28Var;
        G1 = eve.A(28.0d);
        H1 = eve.B(22);
        I1 = eve.B(0);
        J1 = dv7Var3;
        K1 = z28Var;
        L1 = eve.A(24.0d);
        M1 = eve.B(16);
        N1 = eve.A(0.15d);
        O1 = dv7Var4;
        P1 = z28Var;
        Q1 = eve.A(20.0d);
        R1 = eve.B(14);
        S1 = eve.A(0.1d);
        T1 = dv7Var4;
    }
}
