package defpackage;

import java.util.LinkedHashMap;

/* JADX INFO: loaded from: classes.dex */
public final class zf3 {
    public static final k2e b;
    public static final iec c;
    public static final LinkedHashMap d;
    public static final zf3 e;
    public static final zf3 f;
    public static final zf3 g;
    public static final zf3 h;
    public static final zf3 i;
    public static final zf3 j;
    public static final zf3 k;
    public static final zf3 l;
    public static final zf3 m;
    public static final zf3 n;
    public static final zf3 o;
    public static final zf3 p;
    public static final zf3 q;
    public static final zf3 r;
    public static final zf3 s;
    public static final zf3 t;
    public final String a;

    static {
        k2e k2eVar = new k2e(14);
        b = k2eVar;
        c = new iec(1);
        d = new LinkedHashMap();
        k2e.o(k2eVar, "SSL_RSA_WITH_NULL_MD5");
        k2e.o(k2eVar, "SSL_RSA_WITH_NULL_SHA");
        k2e.o(k2eVar, "SSL_RSA_EXPORT_WITH_RC4_40_MD5");
        k2e.o(k2eVar, "SSL_RSA_WITH_RC4_128_MD5");
        k2e.o(k2eVar, "SSL_RSA_WITH_RC4_128_SHA");
        k2e.o(k2eVar, "SSL_RSA_EXPORT_WITH_DES40_CBC_SHA");
        k2e.o(k2eVar, "SSL_RSA_WITH_DES_CBC_SHA");
        e = k2e.o(k2eVar, "SSL_RSA_WITH_3DES_EDE_CBC_SHA");
        k2e.o(k2eVar, "SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA");
        k2e.o(k2eVar, "SSL_DHE_DSS_WITH_DES_CBC_SHA");
        k2e.o(k2eVar, "SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA");
        k2e.o(k2eVar, "SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA");
        k2e.o(k2eVar, "SSL_DHE_RSA_WITH_DES_CBC_SHA");
        k2e.o(k2eVar, "SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA");
        k2e.o(k2eVar, "SSL_DH_anon_EXPORT_WITH_RC4_40_MD5");
        k2e.o(k2eVar, "SSL_DH_anon_WITH_RC4_128_MD5");
        k2e.o(k2eVar, "SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA");
        k2e.o(k2eVar, "SSL_DH_anon_WITH_DES_CBC_SHA");
        k2e.o(k2eVar, "SSL_DH_anon_WITH_3DES_EDE_CBC_SHA");
        k2e.o(k2eVar, "TLS_KRB5_WITH_DES_CBC_SHA");
        k2e.o(k2eVar, "TLS_KRB5_WITH_3DES_EDE_CBC_SHA");
        k2e.o(k2eVar, "TLS_KRB5_WITH_RC4_128_SHA");
        k2e.o(k2eVar, "TLS_KRB5_WITH_DES_CBC_MD5");
        k2e.o(k2eVar, "TLS_KRB5_WITH_3DES_EDE_CBC_MD5");
        k2e.o(k2eVar, "TLS_KRB5_WITH_RC4_128_MD5");
        k2e.o(k2eVar, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA");
        k2e.o(k2eVar, "TLS_KRB5_EXPORT_WITH_RC4_40_SHA");
        k2e.o(k2eVar, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5");
        k2e.o(k2eVar, "TLS_KRB5_EXPORT_WITH_RC4_40_MD5");
        f = k2e.o(k2eVar, "TLS_RSA_WITH_AES_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_DH_anon_WITH_AES_128_CBC_SHA");
        g = k2e.o(k2eVar, "TLS_RSA_WITH_AES_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_DH_anon_WITH_AES_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_RSA_WITH_NULL_SHA256");
        k2e.o(k2eVar, "TLS_RSA_WITH_AES_128_CBC_SHA256");
        k2e.o(k2eVar, "TLS_RSA_WITH_AES_256_CBC_SHA256");
        k2e.o(k2eVar, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256");
        k2e.o(k2eVar, "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256");
        k2e.o(k2eVar, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256");
        k2e.o(k2eVar, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256");
        k2e.o(k2eVar, "TLS_DH_anon_WITH_AES_128_CBC_SHA256");
        k2e.o(k2eVar, "TLS_DH_anon_WITH_AES_256_CBC_SHA256");
        k2e.o(k2eVar, "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_PSK_WITH_RC4_128_SHA");
        k2e.o(k2eVar, "TLS_PSK_WITH_3DES_EDE_CBC_SHA");
        k2e.o(k2eVar, "TLS_PSK_WITH_AES_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_PSK_WITH_AES_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_RSA_WITH_SEED_CBC_SHA");
        h = k2e.o(k2eVar, "TLS_RSA_WITH_AES_128_GCM_SHA256");
        i = k2e.o(k2eVar, "TLS_RSA_WITH_AES_256_GCM_SHA384");
        k2e.o(k2eVar, "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256");
        k2e.o(k2eVar, "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384");
        k2e.o(k2eVar, "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256");
        k2e.o(k2eVar, "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384");
        k2e.o(k2eVar, "TLS_DH_anon_WITH_AES_128_GCM_SHA256");
        k2e.o(k2eVar, "TLS_DH_anon_WITH_AES_256_GCM_SHA384");
        k2e.o(k2eVar, "TLS_EMPTY_RENEGOTIATION_INFO_SCSV");
        k2e.o(k2eVar, "TLS_FALLBACK_SCSV");
        k2e.o(k2eVar, "TLS_ECDH_ECDSA_WITH_NULL_SHA");
        k2e.o(k2eVar, "TLS_ECDH_ECDSA_WITH_RC4_128_SHA");
        k2e.o(k2eVar, "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDHE_ECDSA_WITH_NULL_SHA");
        k2e.o(k2eVar, "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA");
        k2e.o(k2eVar, "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDH_RSA_WITH_NULL_SHA");
        k2e.o(k2eVar, "TLS_ECDH_RSA_WITH_RC4_128_SHA");
        k2e.o(k2eVar, "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDHE_RSA_WITH_NULL_SHA");
        k2e.o(k2eVar, "TLS_ECDHE_RSA_WITH_RC4_128_SHA");
        k2e.o(k2eVar, "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA");
        j = k2e.o(k2eVar, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA");
        k = k2e.o(k2eVar, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDH_anon_WITH_NULL_SHA");
        k2e.o(k2eVar, "TLS_ECDH_anon_WITH_RC4_128_SHA");
        k2e.o(k2eVar, "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDH_anon_WITH_AES_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDH_anon_WITH_AES_256_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256");
        k2e.o(k2eVar, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384");
        k2e.o(k2eVar, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256");
        k2e.o(k2eVar, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384");
        k2e.o(k2eVar, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256");
        k2e.o(k2eVar, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384");
        k2e.o(k2eVar, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256");
        k2e.o(k2eVar, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384");
        l = k2e.o(k2eVar, "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256");
        m = k2e.o(k2eVar, "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384");
        k2e.o(k2eVar, "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256");
        k2e.o(k2eVar, "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384");
        n = k2e.o(k2eVar, "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256");
        o = k2e.o(k2eVar, "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384");
        k2e.o(k2eVar, "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256");
        k2e.o(k2eVar, "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384");
        k2e.o(k2eVar, "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA");
        k2e.o(k2eVar, "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA");
        p = k2e.o(k2eVar, "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        q = k2e.o(k2eVar, "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256");
        k2e.o(k2eVar, "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        k2e.o(k2eVar, "TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256");
        r = k2e.o(k2eVar, "TLS_AES_128_GCM_SHA256");
        s = k2e.o(k2eVar, "TLS_AES_256_GCM_SHA384");
        t = k2e.o(k2eVar, "TLS_CHACHA20_POLY1305_SHA256");
        k2e.o(k2eVar, "TLS_AES_128_CCM_SHA256");
        k2e.o(k2eVar, "TLS_AES_128_CCM_8_SHA256");
    }

    public zf3(String str) {
        this.a = str;
    }

    public final String toString() {
        return this.a;
    }
}
