package defpackage;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;

/* JADX INFO: loaded from: classes.dex */
public abstract class zvj {
    public static final yek A;
    public static final yek A0;
    public static final yek B;
    public static final yek B0;
    public static final yek C;
    public static final yek C0;
    public static final yek D;
    public static final yek D0;
    public static final yek E;
    public static final yek E0;
    public static final yek F;
    public static final yek F0;
    public static final yek G;
    public static final yek G0;
    public static final yek H;
    public static final yek H0;
    public static final yek I;
    public static final yek I0;
    public static final yek J;
    public static final yek J0;
    public static final yek K;
    public static final yek K0;
    public static final yek L;
    public static final yek L0;
    public static final yek M;
    public static final yek M0;
    public static final yek N;
    public static final yek N0;
    public static final yek O;
    public static final yek O0;
    public static final yek P;
    public static final yek P0;
    public static final yek Q;
    public static final yek Q0;
    public static final yek R;
    public static final yek R0;
    public static final yek S;
    public static final yek S0;
    public static final yek T;
    public static final yek T0;
    public static final yek U;
    public static final yek U0;
    public static final yek V;
    public static final yek V0;
    public static final yek W;
    public static final yek W0;
    public static final yek X;
    public static final yek X0;
    public static final yek Y;
    public static final yek Y0;
    public static final yek Z;
    public static final yek Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final yek a0;
    public static final yek a1;
    public static final yek b;
    public static final yek b0;
    public static final yek b1;
    public static final yek c;
    public static final yek c0;
    public static final yek c1;
    public static final yek d;
    public static final yek d0;
    public static final yek d1;
    public static final yek e;
    public static final yek e0;
    public static final yek e1;
    public static final yek f;
    public static final yek f0;
    public static final yek f1;
    public static final yek g;
    public static final yek g0;
    public static final yek g1;
    public static final yek h;
    public static final yek h0;
    public static final yek h1;
    public static final yek i;
    public static final yek i0;
    public static final yek i1;
    public static final yek j;
    public static final yek j0;
    public static final yek j1;
    public static final yek k;
    public static final yek k0;
    public static final yek k1;
    public static final yek l;
    public static final yek l0;
    public static final yek l1;
    public static final yek m;
    public static final yek m0;
    public static final yek m1;
    public static final yek n;
    public static final yek n0;
    public static final yek o;
    public static final yek o0;
    public static final yek p;
    public static final yek p0;
    public static final yek q;
    public static final yek q0;
    public static final yek r;
    public static final yek r0;
    public static final yek s;
    public static final yek s0;
    public static final yek t;
    public static final yek t0;
    public static final yek u;
    public static final yek u0;
    public static final yek v;
    public static final yek v0;
    public static final yek w;
    public static final yek w0;
    public static final yek x;
    public static final yek x0;
    public static final yek y;
    public static final yek y0;
    public static final yek z;
    public static final yek z0;

    static {
        Collections.synchronizedSet(new HashSet());
        int i2 = 2;
        b = a("measurement.ad_id_cache_time", 10000L, new cli(i2), false);
        int i3 = 5;
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, new g6j(i3), false);
        int i4 = 7;
        d = a("measurement.monitoring.sample_period_millis", 86400000L, new v4i(i4), false);
        int i5 = 8;
        e = a("measurement.config.cache_time", 86400000L, new xxi(i5), false);
        int i6 = 9;
        f = a("measurement.config.url_scheme", "https", new g6j(i6), false);
        int i7 = 11;
        g = a("measurement.config.url_authority", "app-measurement.com", new v4i(i7), false);
        h = a("measurement.upload.max_bundles", 100, new cli(12), false);
        i = a("measurement.upload.max_batch_size", 65536, new xxi(13), false);
        j = a("measurement.upload.max_bundle_size", 65536, new g6j(i2), false);
        int i8 = 4;
        k = a("measurement.upload.max_events_per_bundle", 1000, new v4i(i8), false);
        l = a("measurement.upload.max_events_per_day", 100000, new cli(i8), false);
        m = a("measurement.upload.max_error_events_per_day", 1000, new g6j(i8), false);
        n = a("measurement.upload.max_public_events_per_day", 50000, new v4i(i3), false);
        o = a("measurement.upload.max_conversions_per_day", Integer.valueOf(yr6.INVALID_OWNERSHIP), new cli(i3), false);
        int i9 = 10;
        p = a("measurement.upload.max_realtime_events_per_day", 10, new sai(i3), false);
        q = a("measurement.store.max_stored_events_per_app", 100000, new roi(i3), false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", new jli(i3), false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s", new byi(i3), false);
        t = a("measurement.upload.backoff_period", 43200000L, new xxi(i3), false);
        int i10 = 6;
        a("measurement.upload.window_interval", 3600000L, new s4i(i10), false);
        u = a("measurement.upload.interval", 3600000L, new f7i(i10), false);
        v = a("measurement.upload.realtime_upload_interval", 10000L, new cli(i10), false);
        w = a("measurement.upload.debug_upload_interval", 1000L, new sai(i10), false);
        x = a("measurement.upload.minimum_delay", 500L, new roi(i10), false);
        y = a("measurement.alarm_manager.minimum_interval", 60000L, new jli(i10), false);
        z = a("measurement.upload.stale_data_deletion_interval", 86400000L, new byi(i10), false);
        A = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, new xxi(i10), false);
        B = a("measurement.upload.initial_upload_delay_time", 15000L, new s4i(i4), false);
        C = a("measurement.upload.retry_time", 1800000L, new g6j(i10), false);
        D = a("measurement.upload.retry_count", 6, new f7i(i4), false);
        E = a("measurement.upload.max_queue_time", 2419200000L, new sai(i4), false);
        F = a("measurement.upload.google_sginal_max_queue_time", 300000L, new roi(i4), false);
        G = a("measurement.lifetimevalue.max_currency_tracked", 4, new jli(i4), false);
        H = a("measurement.audience.filter_result_max_count", 200, new g6j(i4), false);
        I = a("measurement.upload.max_public_user_properties", 25, null, false);
        J = a("measurement.upload.max_event_name_cardinality", 500, null, false);
        K = a("measurement.upload.max_public_event_params", 25, null, false);
        L = a("measurement.service_client.idle_disconnect_millis", 5000L, new xxi(i4), false);
        Boolean bool = Boolean.FALSE;
        M = a("measurement.test.boolean_flag", bool, new v4i(i5), false);
        N = a("measurement.test.string_flag", "---", new s4i(i5), false);
        O = a("measurement.test.long_flag", -1L, new sai(i5), false);
        a("measurement.test.cached_long_flag", -1L, new f7i(i5), true);
        P = a("measurement.test.int_flag", -2, new jli(i5), false);
        Q = a("measurement.test.double_flag", Double.valueOf(-3.0d), new roi(i5), false);
        R = a("measurement.experiment.max_ids", 50, new g6j(i5), false);
        S = a("measurement.upload.max_item_scoped_custom_parameters", 27, new byi(i5), false);
        T = a("measurement.upload.max_event_parameter_value_length", 100, new v4i(i6), true);
        U = a("measurement.max_bundles_per_iteration", 100, new s4i(i6), false);
        V = a("measurement.sdk.attribution.cache.ttl", 604800000L, new sai(i6), false);
        W = a("measurement.redaction.app_instance_id.ttl", 7200000L, new f7i(i6), false);
        X = a("measurement.rb.attribution.client.min_ad_services_version", 7, new jli(i6), false);
        Y = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, new cli(i6), false);
        Z = a("measurement.rb.attribution.uri_scheme", "https", new roi(i6), false);
        a0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", new byi(i6), false);
        b0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", new v4i(i9), false);
        c0 = a("measurement.session.engagement_interval", 3600000L, new s4i(i9), false);
        d0 = a("measurement.rb.attribution.app_allowlist", "com.labpixies.flood,com.sofascore.results,games.spearmint.triplecrush,com.block.juggle,io.supercent.linkedcubic,com.cdtg.gunsound,com.corestudios.storemanagementidle,com.cdgames.fidget3d,io.supercent.burgeridle,io.supercent.pizzaidle,jp.ne.ibis.ibispaintx.app,com.dencreak.dlcalculator,com.ebay.kleinanzeigen,de.wetteronline.wetterapp,com.game.shape.shift,com.champion.cubes,bubbleshooter.orig,com.wolt.android,com.master.hotelmaster,com.games.bus.arrival,com.playstrom.dop2,com.huuuge.casino.slots,com.ig.spider.fighting,com.jura.coloring.page,com.rikkogame.ragdoll2,com.ludo.king,com.sigma.prank.sound.haircut,com.crazy.block.robo.monster.cliffs.craft,com.fugo.wow,com.maps.locator.gps.gpstracker.phone,com.gamovation.tileclub,com.pronetis.ironball2,com.meesho.supply,pdf.pdfreader.viewer.editor.free,com.dino.race.master,com.ig.moto.racing,ai.photo.enhancer.photoclear,com.duolingo,com.candle.magic_piano,com.free.vpn.super.hotspot.open,sg.bigo.live,com.cdg.tictactoe,com.zhiliaoapp.musically.go,com.wildspike.wormszone,com.mast.status.video.edit,com.vyroai.photoeditorone,com.pujiagames.deeeersimulator,com.superbinogo.jungleboyadventure,com.trustedapp.pdfreaderpdfviewer,com.artimind.aiart.artgenerator.artavatar,de.cellular.ottohybrid,com.zeptolab.cats.google,in.crossy.daily_crossword", new sai(i9), false);
        e0 = a("measurement.rb.attribution.user_properties", "_npa,npa", new f7i(i9), false);
        f0 = a("measurement.rb.attribution.event_params", "value|currency", new jli(i9), false);
        g0 = a("measurement.rb.attribution.query_parameters_to_remove", "", new cli(i9), false);
        h0 = a("measurement.rb.attribution.max_queue_time", 1209600000L, new xxi(i9), false);
        Boolean bool2 = Boolean.TRUE;
        i0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, new g6j(i9), false);
        j0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, new byi(i9), false);
        a("measurement.collection.log_event_and_bundle_v2", bool2, new s4i(i7), false);
        k0 = a("measurement.quality.checksum", bool, null, false);
        l0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, new sai(i7), false);
        m0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, new f7i(i7), false);
        n0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, new jli(i7), true);
        o0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, new cli(i7), false);
        p0 = a("measurement.integration.disable_firebase_instance_id", bool, new xxi(i7), false);
        q0 = a("measurement.collection.service.update_with_analytics_fix", bool, new roi(i7), false);
        r0 = a("measurement.service.storage_consent_support_version", 203600, new g6j(i7), false);
        int i11 = 12;
        s0 = a("measurement.service.store_null_safelist", bool2, new f7i(i11), false);
        t0 = a("measurement.service.store_safelist", bool2, new v4i(i11), false);
        u0 = a("measurement.session_stitching_token_enabled", bool, new sai(i11), false);
        v0 = a("measurement.sgtm.service", bool2, new roi(i11), true);
        w0 = a("measurement.sgtm.preview_mode_enabled", bool2, new jli(i11), true);
        x0 = a("measurement.sgtm.app_allowlist", "de.zalando.mobile.internal,de.zalando.mobile.internal.debug,de.zalando.lounge.dev,grit.storytel.app,com.rbc.mobile.android,com.rbc.mobile.android,com.dylvian.mango.activities,com.home24.android,com.home24.android.staging,se.lf.mobile.android,se.lf.mobile.android.beta,se.lf.mobile.android.rc,se.lf.mobile.android.test,se.lf.mobile.android.test.debug,com.boots.flagship.android,com.boots.flagshiproi.android,de.zalando.mobile,com.trivago,com.getyourguide.android,es.mobail.meliarewards,se.nansen.coop.debug,se.nansen.coop,se.coop.coop.qa,com.booking,com.google.firebaseengage,com.mse.mseapp.dev,com.mse.mseapp,pl.eobuwie.eobuwieapp,br.com.eventim.mobile.app.Android,ch.ticketcorner.mobile.app.Android,de.eventim.mobile.app.Android,dk.billetlugen.mobile.app.Android,nl.eventim.mobile.app.Android,com.asos.app,com.blueshieldca.prod,dk.magnetix.tivoliapp,matas.matas.internal,nl.omoda,com.thetrainline,com.simo.androidtest,de.aboutyou.mobile.app,com.hometogo,de.casamundo.casamundomobile,it.casevacanz,eu.coolblue.shop,com.stihl.app,com.indeed.android.jobsearch,com.homeretailgroup.argos.android,com.dylvian.mango.activities.pre,se.nansen.coop.qa", new g6j(i11), true);
        y0 = a("measurement.sgtm.upload_queue", bool, new xxi(i11), false);
        int i12 = 13;
        z0 = a("measurement.sgtm.google_signal.enable", bool, new v4i(i12), false);
        A0 = a("measurement.gmscore_feature_tracking", bool2, new sai(i12), false);
        B0 = a("measurement.gmscore_network_migration", bool, new f7i(i12), false);
        C0 = a("measurement.fix_health_monitor_stack_trace", bool2, new jli(i12), true);
        D0 = a("measurement.item_scoped_custom_parameters.client", bool2, new cli(i12), true);
        E0 = a("measurement.item_scoped_custom_parameters.service", bool2, new roi(i12), false);
        F0 = a("measurement.rb.attribution.service", bool2, new g6j(i12), true);
        G0 = a("measurement.rb.attribution.client2", bool2, new byi(i12), true);
        int i13 = 14;
        H0 = a("measurement.rb.attribution.uuid_generation", bool2, new v4i(i13), false);
        I0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, new s4i(i13), false);
        int i14 = 2;
        a("measurement.rb.attribution.followup1.service", bool, new roi(i14), false);
        J0 = a("measurement.rb.attribution.retry_disposition", bool, new jli(i14), false);
        K0 = a("measurement.rb.attribution.ad_campaign_info", bool, new byi(i14), false);
        L0 = a("measurement.rb.attribution.improved_retry", bool2, new xxi(i14), true);
        int i15 = 3;
        M0 = a("measurement.client.sessions.enable_fix_background_engagement", bool, new s4i(i15), false);
        N0 = a("measurement.client.sessions.enable_pause_engagement_in_background", bool2, new f7i(i15), false);
        O0 = a("measurement.dma_consent.service_dcu_event2", bool2, new v4i(i15), false);
        P0 = a("measurement.dma_consent.services_database_update_fix", bool2, new cli(i15), false);
        Q0 = a("measurement.service.deferred_first_open", bool2, new sai(i15), true);
        R0 = a("measurement.gbraid_campaign.gbraid.client", bool, new jli(i15), true);
        S0 = a("measurement.gbraid_campaign.gbraid.service", bool, new byi(i15), true);
        T0 = a("measurement.increase_param_lengths", bool2, new xxi(i15), true);
        U0 = a("measurement.disable_npa_for_dasher_and_unicorn", bool2, new s4i(i8), false);
        V0 = a("measurement.consent_regional_defaults.service", bool2, new g6j(i15), true);
        W0 = a("measurement.consent_regional_defaults.client2", bool2, new f7i(i8), true);
        X0 = a("measurement.service.consent.pfo_on_fx", bool2, new f7i(i3), false);
        Y0 = a("measurement.service.consent.params_on_fx", bool2, new v4i(6), false);
        Z0 = a("measurement.service.consent.app_start_fix", bool2, new cli(i4), false);
        a1 = a("measurement.consent.stop_reset_on_storage_denied.client", bool2, new cli(i5), true);
        b1 = a("measurement.consent.stop_reset_on_storage_denied.service", bool2, new xxi(i6), true);
        c1 = a("measurement.consent.scrub_audience_data_analytics_consent", bool2, new roi(i9), false);
        d1 = a("measurement.consent.fix_first_open_count_from_snapshot", bool2, new s4i(12), false);
        e1 = a("measurement.fix_engagement_on_reset_analytics_data", bool2, new s4i(13), false);
        f1 = a("measurement.rb.attribution.service.bundle_on_backgrounded", bool, new sai(2), false);
        g1 = a("measurement.rb.attribution.client.bundle_on_backgrounded", bool, new roi(i15), false);
        int i16 = 4;
        h1 = a("measurement.set_default_event_parameters_propagate_clear.service.dev", bool, new sai(i16), false);
        i1 = a("measurement.set_default_event_parameters_propagate_clear.client.dev", bool, new roi(i16), false);
        j1 = a("measurement.set_default_event_parameters_with_backfill.service", bool, new jli(i16), false);
        k1 = a("measurement.set_default_event_parameters_with_backfill.client.dev", bool, new byi(i16), false);
        l1 = a("measurement.fix_origin_in_upload_utils.service", bool2, new xxi(i16), false);
        m1 = a("measurement.service.ad_impression.convert_value_to_double", bool2, new s4i(i3), false);
    }

    public static yek a(String str, Object obj, pek pekVar, boolean z2) {
        yek yekVar = new yek(str, obj, pekVar);
        if (z2) {
            a.add(yekVar);
        }
        return yekVar;
    }
}
