  __export(vOr, {
    USE_STAGING_OAUTH: () => USE_STAGING_OAUTH,
    USE_LOCAL_OAUTH: () => USE_LOCAL_OAUTH,
    MCP_XAA_IDP_CLIENT_SECRET: () => MCP_XAA_IDP_CLIENT_SECRET,
    MCP_CLIENT_SECRET: () => MCP_CLIENT_SECRET,
    ENVIRONMENT_SERVICE_KEY: () => ENVIRONMENT_SERVICE_KEY,
    CLAUDE_TRUSTED_DEVICE_TOKEN: () => CLAUDE_TRUSTED_DEVICE_TOKEN,
    CLAUDE_SESSION_INGRESS_TOKEN_FILE: () => CLAUDE_SESSION_INGRESS_TOKEN_FILE,
    CLAUDE_LOCAL_OAUTH_CONSOLE_BASE: () => CLAUDE_LOCAL_OAUTH_CONSOLE_BASE,
    CLAUDE_LOCAL_OAUTH_APPS_BASE: () => CLAUDE_LOCAL_OAUTH_APPS_BASE,
    CLAUDE_LOCAL_OAUTH_API_BASE: () => CLAUDE_LOCAL_OAUTH_API_BASE,
    CLAUDE_CODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR: () => CLAUDE_CODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR,
    CLAUDE_CODE_USER_EMAIL: () => CLAUDE_CODE_USER_EMAIL,
    CLAUDE_CODE_SUBSCRIPTION_TYPE: () => CLAUDE_CODE_SUBSCRIPTION_TYPE,
    CLAUDE_CODE_SKIP_VERTEX_AUTH: () => CLAUDE_CODE_SKIP_VERTEX_AUTH,
    CLAUDE_CODE_SKIP_MANTLE_AUTH: () => CLAUDE_CODE_SKIP_MANTLE_AUTH,
    CLAUDE_CODE_SKIP_FOUNDRY_AUTH: () => CLAUDE_CODE_SKIP_FOUNDRY_AUTH,
    CLAUDE_CODE_SKIP_BEDROCK_AUTH: () => CLAUDE_CODE_SKIP_BEDROCK_AUTH,
    CLAUDE_CODE_SKIP_ANTHROPIC_AWS_AUTH: () => CLAUDE_CODE_SKIP_ANTHROPIC_AWS_AUTH,
    CLAUDE_CODE_SESSION_ACCESS_TOKEN: () => CLAUDE_CODE_SESSION_ACCESS_TOKEN,
    CLAUDE_CODE_SDK_HAS_OAUTH_REFRESH: () => CLAUDE_CODE_SDK_HAS_OAUTH_REFRESH,
    CLAUDE_CODE_RATE_LIMIT_TIER: () => CLAUDE_CODE_RATE_LIMIT_TIER,
    CLAUDE_CODE_PROXY_AUTH_HELPER_TTL_MS: () => CLAUDE_CODE_PROXY_AUTH_HELPER_TTL_MS,
    CLAUDE_CODE_ORGANIZATION_UUID: () => CLAUDE_CODE_ORGANIZATION_UUID,
    CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR: () => CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR,
    CLAUDE_CODE_OAUTH_TOKEN: () => CLAUDE_CODE_OAUTH_TOKEN,
    CLAUDE_CODE_OAUTH_SCOPES: () => CLAUDE_CODE_OAUTH_SCOPES,
    CLAUDE_CODE_OAUTH_REFRESH_TOKEN: () => CLAUDE_CODE_OAUTH_REFRESH_TOKEN,
    CLAUDE_CODE_OAUTH_CLIENT_ID: () => CLAUDE_CODE_OAUTH_CLIENT_ID,
    CLAUDE_CODE_OAUTH_401_WAIT_MS: () => CLAUDE_CODE_OAUTH_401_WAIT_MS,
    CLAUDE_CODE_HOST_CREDS_FILE: () => CLAUDE_CODE_HOST_CREDS_FILE,
    CLAUDE_CODE_HOST_AUTH_ENV_VAR: () => CLAUDE_CODE_HOST_AUTH_ENV_VAR,
    CLAUDE_CODE_HFI_BEARER_TOKEN: () => CLAUDE_CODE_HFI_BEARER_TOKEN,
    CLAUDE_CODE_ENABLE_PROXY_AUTH_HELPER: () => CLAUDE_CODE_ENABLE_PROXY_AUTH_HELPER,
    CLAUDE_CODE_DESIGN_OAUTH_CLIENT_ID: () => CLAUDE_CODE_DESIGN_OAUTH_CLIENT_ID,
    CLAUDE_CODE_CUSTOM_OAUTH_URL: () => CLAUDE_CODE_CUSTOM_OAUTH_URL,
    CLAUDE_CODE_AUTH_FAIL_EXIT_MS: () => CLAUDE_CODE_AUTH_FAIL_EXIT_MS,
    CLAUDE_CODE_API_KEY_HELPER_TTL_MS: () => CLAUDE_CODE_API_KEY_HELPER_TTL_MS,
    CLAUDE_CODE_API_KEY_FILE_DESCRIPTOR: () => CLAUDE_CODE_API_KEY_FILE_DESCRIPTOR,
    CLAUDE_CODE_ACCOUNT_UUID: () => CLAUDE_CODE_ACCOUNT_UUID,
    CLAUDE_CODE_ACCOUNT_TAGGED_ID: () => CLAUDE_CODE_ACCOUNT_TAGGED_ID,
    AWS_BEARER_TOKEN_BEDROCK: () => AWS_BEARER_TOKEN_BEDROCK,
    API_TOKEN: () => API_TOKEN,
    ANTHROPIC_PROFILE: () => ANTHROPIC_PROFILE,
    ANTHROPIC_ORGANIZATION_ID: () => ANTHROPIC_ORGANIZATION_ID,
    ANTHROPIC_FOUNDRY_API_KEY: () => ANTHROPIC_FOUNDRY_API_KEY,
    ANTHROPIC_FEDERATION_RULE_ID: () => ANTHROPIC_FEDERATION_RULE_ID,
    ANTHROPIC_AWS_API_KEY: () => ANTHROPIC_AWS_API_KEY,
    ANTHROPIC_AUTH_TOKEN: () => ANTHROPIC_AUTH_TOKEN,
    ANTHROPIC_API_KEY: () => ANTHROPIC_API_KEY,
    AGENT_PROXY_AUTH_TOKEN: () => AGENT_PROXY_AUTH_TOKEN
  });
  var ANTHROPIC_API_KEY;
  var ANTHROPIC_AUTH_TOKEN;
  var CLAUDE_CODE_OAUTH_TOKEN;
  var AWS_BEARER_TOKEN_BEDROCK;
  var ANTHROPIC_AWS_API_KEY;
  var ANTHROPIC_FOUNDRY_API_KEY;
  var CLAUDE_CODE_HFI_BEARER_TOKEN;
  var AGENT_PROXY_AUTH_TOKEN;
  var API_TOKEN;
  var ENVIRONMENT_SERVICE_KEY;
  var MCP_CLIENT_SECRET;
  var MCP_XAA_IDP_CLIENT_SECRET;
  var CLAUDE_CODE_API_KEY_FILE_DESCRIPTOR;
  var CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR;
  var CLAUDE_CODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR;
  var CLAUDE_SESSION_INGRESS_TOKEN_FILE;
  var CLAUDE_CODE_OAUTH_REFRESH_TOKEN;
  var CLAUDE_CODE_OAUTH_CLIENT_ID;
  var CLAUDE_CODE_DESIGN_OAUTH_CLIENT_ID;
  var CLAUDE_CODE_OAUTH_SCOPES;
  var CLAUDE_CODE_CUSTOM_OAUTH_URL;
  var CLAUDE_CODE_SDK_HAS_OAUTH_REFRESH;
  var CLAUDE_CODE_HOST_AUTH_ENV_VAR;
  var CLAUDE_CODE_HOST_CREDS_FILE;
  var CLAUDE_CODE_SESSION_ACCESS_TOKEN;
  var CLAUDE_TRUSTED_DEVICE_TOKEN;
  var USE_LOCAL_OAUTH;
  var USE_STAGING_OAUTH;
  var CLAUDE_LOCAL_OAUTH_API_BASE;
  var CLAUDE_LOCAL_OAUTH_APPS_BASE;
  var CLAUDE_LOCAL_OAUTH_CONSOLE_BASE;
  var CLAUDE_CODE_OAUTH_401_WAIT_MS;
  var CLAUDE_CODE_AUTH_FAIL_EXIT_MS;
  var CLAUDE_CODE_API_KEY_HELPER_TTL_MS;
  var CLAUDE_CODE_ENABLE_PROXY_AUTH_HELPER;
  var CLAUDE_CODE_PROXY_AUTH_HELPER_TTL_MS;
  var CLAUDE_CODE_SKIP_BEDROCK_AUTH;
  var CLAUDE_CODE_SKIP_VERTEX_AUTH;
  var CLAUDE_CODE_SKIP_FOUNDRY_AUTH;
  var CLAUDE_CODE_SKIP_ANTHROPIC_AWS_AUTH;
  var CLAUDE_CODE_SKIP_MANTLE_AUTH;
  var ANTHROPIC_FEDERATION_RULE_ID;
  var ANTHROPIC_ORGANIZATION_ID;
  var ANTHROPIC_PROFILE;
  var CLAUDE_CODE_ACCOUNT_UUID;
  var CLAUDE_CODE_ACCOUNT_TAGGED_ID;
  var CLAUDE_CODE_ORGANIZATION_UUID;
  var CLAUDE_CODE_USER_EMAIL;
  var CLAUDE_CODE_SUBSCRIPTION_TYPE;
  var CLAUDE_CODE_RATE_LIMIT_TIER;
  var mTs = __lazy(() => {
    ile();
    ANTHROPIC_API_KEY = $e.str();
    ANTHROPIC_AUTH_TOKEN = $e.str();
    CLAUDE_CODE_OAUTH_TOKEN = $e.str();
    AWS_BEARER_TOKEN_BEDROCK = $e.str();
    ANTHROPIC_AWS_API_KEY = $e.str();
    ANTHROPIC_FOUNDRY_API_KEY = $e.str();
    CLAUDE_CODE_HFI_BEARER_TOKEN = $e.str();
    AGENT_PROXY_AUTH_TOKEN = $e.str();
    API_TOKEN = $e.str();
    ENVIRONMENT_SERVICE_KEY = $e.str();
    MCP_CLIENT_SECRET = $e.str();
    MCP_XAA_IDP_CLIENT_SECRET = $e.str();
    CLAUDE_CODE_API_KEY_FILE_DESCRIPTOR = $e.str();
    CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR = $e.str();
    CLAUDE_CODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR = $e.str();
    CLAUDE_SESSION_INGRESS_TOKEN_FILE = $e.str();
    CLAUDE_CODE_OAUTH_REFRESH_TOKEN = $e.str();
    CLAUDE_CODE_OAUTH_CLIENT_ID = $e.str();
    CLAUDE_CODE_DESIGN_OAUTH_CLIENT_ID = $e.str();
    CLAUDE_CODE_OAUTH_SCOPES = $e.str();
    CLAUDE_CODE_CUSTOM_OAUTH_URL = $e.str();
    CLAUDE_CODE_SDK_HAS_OAUTH_REFRESH = $e.bool();
    CLAUDE_CODE_HOST_AUTH_ENV_VAR = $e.str();
    CLAUDE_CODE_HOST_CREDS_FILE = $e.str();
    CLAUDE_CODE_SESSION_ACCESS_TOKEN = $e.str();
    CLAUDE_TRUSTED_DEVICE_TOKEN = $e.str();
    USE_LOCAL_OAUTH = $e.bool();
    USE_STAGING_OAUTH = $e.bool();
    CLAUDE_LOCAL_OAUTH_API_BASE = $e.str();
    CLAUDE_LOCAL_OAUTH_APPS_BASE = $e.str();
    CLAUDE_LOCAL_OAUTH_CONSOLE_BASE = $e.str();
    CLAUDE_CODE_OAUTH_401_WAIT_MS = $e.int({
      min: 0
    });
    CLAUDE_CODE_AUTH_FAIL_EXIT_MS = $e.int({
      min: 0
    });
    CLAUDE_CODE_API_KEY_HELPER_TTL_MS = $e.int();
    CLAUDE_CODE_ENABLE_PROXY_AUTH_HELPER = $e.bool();
    CLAUDE_CODE_PROXY_AUTH_HELPER_TTL_MS = $e.int();
    CLAUDE_CODE_SKIP_BEDROCK_AUTH = $e.bool();
    CLAUDE_CODE_SKIP_VERTEX_AUTH = $e.bool();
    CLAUDE_CODE_SKIP_FOUNDRY_AUTH = $e.bool();
    CLAUDE_CODE_SKIP_ANTHROPIC_AWS_AUTH = $e.bool();
    CLAUDE_CODE_SKIP_MANTLE_AUTH = $e.bool();
    ANTHROPIC_FEDERATION_RULE_ID = $e.str();
    ANTHROPIC_ORGANIZATION_ID = $e.str();
    ANTHROPIC_PROFILE = $e.str();
    CLAUDE_CODE_ACCOUNT_UUID = $e.str();
    CLAUDE_CODE_ACCOUNT_TAGGED_ID = $e.str();
    CLAUDE_CODE_ORGANIZATION_UUID = $e.str();
    CLAUDE_CODE_USER_EMAIL = $e.str();
    CLAUDE_CODE_SUBSCRIPTION_TYPE = $e.str();
    CLAUDE_CODE_RATE_LIMIT_TIER = $e.str();
  });
  var wOr = {};