  __export(oMr, {
    VOICE_STREAM_BASE_URL: () => VOICE_STREAM_BASE_URL,
    VCR_RECORD: () => VCR_RECORD,
    ULTRAPLAN_PROMPT_FILE: () => ULTRAPLAN_PROMPT_FILE,
    TEST_ENABLE_SESSION_PERSISTENCE: () => TEST_ENABLE_SESSION_PERSISTENCE,
    TEAM_MEMORY_SYNC_URL: () => TEAM_MEMORY_SYNC_URL,
    TASK_MAX_OUTPUT_LENGTH: () => TASK_MAX_OUTPUT_LENGTH,
    SLASH_COMMAND_TOOL_CHAR_BUDGET: () => SLASH_COMMAND_TOOL_CHAR_BUDGET,
    SESSION_INGRESS_URL: () => SESSION_INGRESS_URL,
    MCP_TRUNCATION_PROMPT_OVERRIDE: () => MCP_TRUNCATION_PROMPT_OVERRIDE,
    MCP_TOOL_TIMEOUT: () => MCP_TOOL_TIMEOUT,
    MCP_TIMEOUT: () => MCP_TIMEOUT,
    MCP_SERVER_CONNECTION_BATCH_SIZE: () => MCP_SERVER_CONNECTION_BATCH_SIZE,
    MCP_REMOTE_SERVER_CONNECTION_BATCH_SIZE: () => MCP_REMOTE_SERVER_CONNECTION_BATCH_SIZE,
    MCP_OAUTH_CLIENT_METADATA_URL: () => MCP_OAUTH_CLIENT_METADATA_URL,
    MCP_OAUTH_CALLBACK_PORT: () => MCP_OAUTH_CALLBACK_PORT,
    MCP_CONNECT_TIMEOUT_MS: () => MCP_CONNECT_TIMEOUT_MS,
    MCP_CONNECTION_NONBLOCKING: () => MCP_CONNECTION_NONBLOCKING,
    LOCAL_BRIDGE: () => LOCAL_BRIDGE,
    CLAUDE_TMPDIR: () => CLAUDE_TMPDIR,
    CLAUDE_SUBAGENT_BG_SHELL_MAX_MS: () => CLAUDE_SUBAGENT_BG_SHELL_MAX_MS,
    CLAUDE_STAGE_FILE_ROOT: () => CLAUDE_STAGE_FILE_ROOT,
    CLAUDE_SSH_VERSION: () => CLAUDE_SSH_VERSION,
    CLAUDE_SSH_LOCAL_BINARY: () => CLAUDE_SSH_LOCAL_BINARY,
    CLAUDE_SNIP: () => CLAUDE_SNIP,
    CLAUDE_SERVE_DRAIN_TIMEOUT_MS: () => CLAUDE_SERVE_DRAIN_TIMEOUT_MS,
    CLAUDE_RUNNER_FETCH_DEPTH: () => CLAUDE_RUNNER_FETCH_DEPTH,
    CLAUDE_REPL_VARIANT: () => CLAUDE_REPL_VARIANT,
    CLAUDE_REMOTE_CONTROL_SESSION_NAME_PREFIX: () => CLAUDE_REMOTE_CONTROL_SESSION_NAME_PREFIX,
    CLAUDE_JOB_DIR: () => CLAUDE_JOB_DIR,
    CLAUDE_INTERNAL_WARM_RESUME_QA: () => CLAUDE_INTERNAL_WARM_RESUME_QA,
    CLAUDE_INTERNAL_FC_OVERRIDES: () => CLAUDE_INTERNAL_FC_OVERRIDES,
    CLAUDE_INTERNAL_ASSISTANT_TEAM_NAME: () => CLAUDE_INTERNAL_ASSISTANT_TEAM_NAME,
    CLAUDE_FORCE_DISPLAY_SURVEY: () => CLAUDE_FORCE_DISPLAY_SURVEY,
    CLAUDE_ENV_FILE: () => CLAUDE_ENV_FILE,
    CLAUDE_COWORK_MEMORY_PATH_OVERRIDE: () => CLAUDE_COWORK_MEMORY_PATH_OVERRIDE,
    CLAUDE_COWORK_MEMORY_INDEX_CONTENT: () => CLAUDE_COWORK_MEMORY_INDEX_CONTENT,
    CLAUDE_COWORK_MEMORY_GUIDELINES: () => CLAUDE_COWORK_MEMORY_GUIDELINES,
    CLAUDE_COWORK_MEMORY_EXTRA_GUIDELINES: () => CLAUDE_COWORK_MEMORY_EXTRA_GUIDELINES,
    CLAUDE_CONFIG_DIR: () => CLAUDE_CONFIG_DIR,
    CLAUDE_CODE_WORKSPACE_HOST_PATHS: () => CLAUDE_CODE_WORKSPACE_HOST_PATHS,
    CLAUDE_CODE_WORKER_EPOCH: () => CLAUDE_CODE_WORKER_EPOCH,
    CLAUDE_CODE_USER_DIALOG_TIMEOUT_MS: () => CLAUDE_CODE_USER_DIALOG_TIMEOUT_MS,
    CLAUDE_CODE_ULTRAREVIEW_PREFLIGHT_FIXTURE: () => CLAUDE_CODE_ULTRAREVIEW_PREFLIGHT_FIXTURE,
    CLAUDE_CODE_TUI_JUST_SWITCHED: () => CLAUDE_CODE_TUI_JUST_SWITCHED,
    CLAUDE_CODE_TMUX_TRUECOLOR: () => CLAUDE_CODE_TMUX_TRUECOLOR,
    CLAUDE_CODE_TMUX_SESSION: () => CLAUDE_CODE_TMUX_SESSION,
    CLAUDE_CODE_TMUX_PREFIX_CONFLICTS: () => CLAUDE_CODE_TMUX_PREFIX_CONFLICTS,
    CLAUDE_CODE_TMUX_PREFIX: () => CLAUDE_CODE_TMUX_PREFIX,
    CLAUDE_CODE_TMPDIR: () => CLAUDE_CODE_TMPDIR,
    CLAUDE_CODE_TEST_NO_PWSH: () => CLAUDE_CODE_TEST_NO_PWSH,
    CLAUDE_CODE_TEST_NO_GIT_BASH: () => CLAUDE_CODE_TEST_NO_GIT_BASH,
    CLAUDE_CODE_TEST_FORCE_DENY: () => CLAUDE_CODE_TEST_FORCE_DENY,
    CLAUDE_CODE_TEST_FIXTURES_ROOT: () => CLAUDE_CODE_TEST_FIXTURES_ROOT,
    CLAUDE_CODE_TASK_LIST_ID: () => CLAUDE_CODE_TASK_LIST_ID,
    CLAUDE_CODE_TAGS: () => CLAUDE_CODE_TAGS,
    CLAUDE_CODE_SYSTEM_PROMPT_GB_FEATURE: () => CLAUDE_CODE_SYSTEM_PROMPT_GB_FEATURE,
    CLAUDE_CODE_SYNTAX_HIGHLIGHT: () => CLAUDE_CODE_SYNTAX_HIGHLIGHT,
    CLAUDE_CODE_SYNC_SKILLS_WAIT_TIMEOUT_MS: () => CLAUDE_CODE_SYNC_SKILLS_WAIT_TIMEOUT_MS,
    CLAUDE_CODE_SYNC_SKILLS_INSTALL_TIMEOUT_MS: () => CLAUDE_CODE_SYNC_SKILLS_INSTALL_TIMEOUT_MS,
    CLAUDE_CODE_SYNC_PLUGIN_INSTALL_TIMEOUT_MS: () => CLAUDE_CODE_SYNC_PLUGIN_INSTALL_TIMEOUT_MS,
    CLAUDE_CODE_SYNC_PLUGINS_DOWNLOAD_STALL_MS: () => CLAUDE_CODE_SYNC_PLUGINS_DOWNLOAD_STALL_MS,
    CLAUDE_CODE_SYNC_PLUGINS_BUFFERED_DOWNLOAD: () => CLAUDE_CODE_SYNC_PLUGINS_BUFFERED_DOWNLOAD,
    CLAUDE_CODE_SUPERVISED: () => CLAUDE_CODE_SUPERVISED,
    CLAUDE_CODE_SUBPROCESS_ENV_SCRUB: () => CLAUDE_CODE_SUBPROCESS_ENV_SCRUB,
    CLAUDE_CODE_STALL_TIMEOUT_MS_FOR_TESTING: () => CLAUDE_CODE_STALL_TIMEOUT_MS_FOR_TESTING,
    CLAUDE_CODE_SSE_PORT: () => CLAUDE_CODE_SSE_PORT,
    CLAUDE_CODE_SIMPLE_SYSTEM_PROMPT: () => CLAUDE_CODE_SIMPLE_SYSTEM_PROMPT,
    CLAUDE_CODE_SIMPLE: () => CLAUDE_CODE_SIMPLE,
    CLAUDE_CODE_SHELL_PREFIX: () => CLAUDE_CODE_SHELL_PREFIX,
    CLAUDE_CODE_SHELL: () => CLAUDE_CODE_SHELL,
    CLAUDE_CODE_SESSION_NAME: () => CLAUDE_CODE_SESSION_NAME,
    CLAUDE_CODE_SESSION_KIND: () => CLAUDE_CODE_SESSION_KIND,
    CLAUDE_CODE_SESSION_ID: () => CLAUDE_CODE_SESSION_ID,
    CLAUDE_CODE_SESSIONEND_HOOKS_TIMEOUT_MS: () => CLAUDE_CODE_SESSIONEND_HOOKS_TIMEOUT_MS,
    CLAUDE_CODE_SCROLL_SPEED: () => CLAUDE_CODE_SCROLL_SPEED,
    CLAUDE_CODE_SCRIPT_CAPS: () => CLAUDE_CODE_SCRIPT_CAPS,
    CLAUDE_CODE_SANDBOXED: () => CLAUDE_CODE_SANDBOXED,
    CLAUDE_CODE_RESUME_TOKEN_THRESHOLD: () => CLAUDE_CODE_RESUME_TOKEN_THRESHOLD,
    CLAUDE_CODE_RESUME_THRESHOLD_MINUTES: () => CLAUDE_CODE_RESUME_THRESHOLD_MINUTES,
    CLAUDE_CODE_RESUME_PROMPT: () => CLAUDE_CODE_RESUME_PROMPT,
    CLAUDE_CODE_RESUME_INTERRUPTED_TURN: () => CLAUDE_CODE_RESUME_INTERRUPTED_TURN,
    CLAUDE_CODE_RESUME_FROM_SESSION: () => CLAUDE_CODE_RESUME_FROM_SESSION,
    CLAUDE_CODE_REPO_CHECKOUTS: () => CLAUDE_CODE_REPO_CHECKOUTS,
    CLAUDE_CODE_REPL: () => CLAUDE_CODE_REPL,
    CLAUDE_CODE_REMOTE_SETTINGS_POLL_MS: () => CLAUDE_CODE_REMOTE_SETTINGS_POLL_MS,
    CLAUDE_CODE_REMOTE_SETTINGS_PATH: () => CLAUDE_CODE_REMOTE_SETTINGS_PATH,
    CLAUDE_CODE_REMOTE_SESSION_ID: () => CLAUDE_CODE_REMOTE_SESSION_ID,
    CLAUDE_CODE_REMOTE_SEND_KEEPALIVES: () => CLAUDE_CODE_REMOTE_SEND_KEEPALIVES,
    CLAUDE_CODE_REMOTE_RAW_EVENTS_FILE: () => CLAUDE_CODE_REMOTE_RAW_EVENTS_FILE,
    CLAUDE_CODE_REMOTE_MEMORY_DIR: () => CLAUDE_CODE_REMOTE_MEMORY_DIR,
    CLAUDE_CODE_REMOTE_HERMETIC_MODE: () => CLAUDE_CODE_REMOTE_HERMETIC_MODE,
    CLAUDE_CODE_REMOTE_ENVIRONMENT_TYPE: () => CLAUDE_CODE_REMOTE_ENVIRONMENT_TYPE,
    CLAUDE_CODE_REMOTE: () => CLAUDE_CODE_REMOTE,
    CLAUDE_CODE_QUESTION_PREVIEW_FORMAT: () => CLAUDE_CODE_QUESTION_PREVIEW_FORMAT,
    CLAUDE_CODE_PWSH_PARSE_TIMEOUT_MS: () => CLAUDE_CODE_PWSH_PARSE_TIMEOUT_MS,
    CLAUDE_CODE_POWERUP_ONBOARDING: () => CLAUDE_CODE_POWERUP_ONBOARDING,
    CLAUDE_CODE_POST_FOR_SESSION_INGRESS_V2: () => CLAUDE_CODE_POST_FOR_SESSION_INGRESS_V2,
    CLAUDE_CODE_PLUGIN_SEED_DIR: () => CLAUDE_CODE_PLUGIN_SEED_DIR,
    CLAUDE_CODE_PLUGIN_GIT_TIMEOUT_MS: () => CLAUDE_CODE_PLUGIN_GIT_TIMEOUT_MS,
    CLAUDE_CODE_PLUGIN_CACHE_DIR: () => CLAUDE_CODE_PLUGIN_CACHE_DIR,
    CLAUDE_CODE_PLAN_V2_EXPLORE_AGENT_COUNT: () => CLAUDE_CODE_PLAN_V2_EXPLORE_AGENT_COUNT,
    CLAUDE_CODE_PLAN_V2_AGENT_COUNT: () => CLAUDE_CODE_PLAN_V2_AGENT_COUNT,
    CLAUDE_CODE_PLAN_MODE_INTERVIEW_PHASE: () => CLAUDE_CODE_PLAN_MODE_INTERVIEW_PHASE,
    CLAUDE_CODE_PERFORCE_MODE: () => CLAUDE_CODE_PERFORCE_MODE,
    CLAUDE_CODE_PARKED_PERMISSION_WAIT_MS: () => CLAUDE_CODE_PARKED_PERMISSION_WAIT_MS,
    CLAUDE_CODE_OVERRIDE_DATE: () => CLAUDE_CODE_OVERRIDE_DATE,
    CLAUDE_CODE_MOCK_TRIAL: () => CLAUDE_CODE_MOCK_TRIAL,
    CLAUDE_CODE_MOCK_REMOTE_SETTINGS: () => CLAUDE_CODE_MOCK_REMOTE_SETTINGS,
    CLAUDE_CODE_MID_CONVERSATION_SYSTEM: () => CLAUDE_CODE_MID_CONVERSATION_SYSTEM,
    CLAUDE_CODE_MCP_TOOL_IDLE_TIMEOUT: () => CLAUDE_CODE_MCP_TOOL_IDLE_TIMEOUT,
    CLAUDE_CODE_MCP_AUTO_BACKGROUND_MS: () => CLAUDE_CODE_MCP_AUTO_BACKGROUND_MS,
    CLAUDE_CODE_MCP_ALLOWLIST_ENV: () => CLAUDE_CODE_MCP_ALLOWLIST_ENV,
    CLAUDE_CODE_MANAGED_SETTINGS_PATH: () => CLAUDE_CODE_MANAGED_SETTINGS_PATH,
    CLAUDE_CODE_LOOP_PERSISTENT: () => CLAUDE_CODE_LOOP_PERSISTENT,
    CLAUDE_CODE_IS_COWORK: () => CLAUDE_CODE_IS_COWORK,
    CLAUDE_CODE_INVESTIGATE_FIRST: () => CLAUDE_CODE_INVESTIGATE_FIRST,
    CLAUDE_CODE_IDLE_TOKEN_THRESHOLD: () => CLAUDE_CODE_IDLE_TOKEN_THRESHOLD,
    CLAUDE_CODE_IDLE_THRESHOLD_MINUTES: () => CLAUDE_CODE_IDLE_THRESHOLD_MINUTES,
    CLAUDE_CODE_IDE_HOST_OVERRIDE: () => CLAUDE_CODE_IDE_HOST_OVERRIDE,
    CLAUDE_CODE_HOST_PLATFORM: () => CLAUDE_CODE_HOST_PLATFORM,
    CLAUDE_CODE_HIDE_SETTINGS_HINT: () => CLAUDE_CODE_HIDE_SETTINGS_HINT,
    CLAUDE_CODE_GLOB_TIMEOUT_SECONDS: () => CLAUDE_CODE_GLOB_TIMEOUT_SECONDS,
    CLAUDE_CODE_GIT_BASH_PATH: () => CLAUDE_CODE_GIT_BASH_PATH,
    CLAUDE_CODE_FORCE_TIP_ID: () => CLAUDE_CODE_FORCE_TIP_ID,
    CLAUDE_CODE_FORCE_MEMORY_SURVEY: () => CLAUDE_CODE_FORCE_MEMORY_SURVEY,
    CLAUDE_CODE_FORCE_FULL_LOGO: () => CLAUDE_CODE_FORCE_FULL_LOGO,
    CLAUDE_CODE_FORCE_FULLSCREEN_UPSELL: () => CLAUDE_CODE_FORCE_FULLSCREEN_UPSELL,
    CLAUDE_CODE_FORCE_EVALUATE_MEMORY: () => CLAUDE_CODE_FORCE_EVALUATE_MEMORY,
    CLAUDE_CODE_FORCE_BRIDGE: () => CLAUDE_CODE_FORCE_BRIDGE,
    CLAUDE_CODE_FABLE_BRIDGE_DIALOG_TIMEOUT_MS: () => CLAUDE_CODE_FABLE_BRIDGE_DIALOG_TIMEOUT_MS,
    CLAUDE_CODE_EXIT_AFTER_STOP_DELAY: () => CLAUDE_CODE_EXIT_AFTER_STOP_DELAY,
    CLAUDE_CODE_EXIT_AFTER_FIRST_RENDER: () => CLAUDE_CODE_EXIT_AFTER_FIRST_RENDER,
    CLAUDE_CODE_ENVIRONMENT_RUNNER_VERSION: () => CLAUDE_CODE_ENVIRONMENT_RUNNER_VERSION,
    CLAUDE_CODE_ENVIRONMENT_KIND: () => CLAUDE_CODE_ENVIRONMENT_KIND,
    CLAUDE_CODE_ENTRYPOINT: () => CLAUDE_CODE_ENTRYPOINT,
    CLAUDE_CODE_EMIT_TOOL_USE_SUMMARIES: () => CLAUDE_CODE_EMIT_TOOL_USE_SUMMARIES,
    CLAUDE_CODE_EMIT_SESSION_STATE_EVENTS: () => CLAUDE_CODE_EMIT_SESSION_STATE_EVENTS,
    CLAUDE_CODE_DONT_INHERIT_ENV: () => CLAUDE_CODE_DONT_INHERIT_ENV,
    CLAUDE_CODE_DISABLE_WORKING_SYNC: () => CLAUDE_CODE_DISABLE_WORKING_SYNC,
    CLAUDE_CODE_DISABLE_BG_SHELL_PRESSURE_REAP: () => CLAUDE_CODE_DISABLE_BG_SHELL_PRESSURE_REAP,
    CLAUDE_CODE_DEV_RAW_CHANGELOG_URL: () => CLAUDE_CODE_DEV_RAW_CHANGELOG_URL,
    CLAUDE_CODE_DECSTBM: () => CLAUDE_CODE_DECSTBM,
    CLAUDE_CODE_DAEMON_COLD_START: () => CLAUDE_CODE_DAEMON_COLD_START,
    CLAUDE_CODE_CONTAINER_ID: () => CLAUDE_CODE_CONTAINER_ID,
    CLAUDE_CODE_CLASSIFIER_SUMMARY: () => CLAUDE_CODE_CLASSIFIER_SUMMARY,
    CLAUDE_CODE_BRIEF_UPLOAD: () => CLAUDE_CODE_BRIEF_UPLOAD,
    CLAUDE_CODE_BRIEF: () => CLAUDE_CODE_BRIEF,
    CLAUDE_CODE_BLOCKING_LIMIT_OVERRIDE: () => CLAUDE_CODE_BLOCKING_LIMIT_OVERRIDE,
    CLAUDE_CODE_BASE_REFS: () => CLAUDE_CODE_BASE_REFS,
    CLAUDE_CODE_BASE_REF: () => CLAUDE_CODE_BASE_REF,
    CLAUDE_CODE_AUTO_MODE_EXTERNAL_PERMISSIONS: () => CLAUDE_CODE_AUTO_MODE_EXTERNAL_PERMISSIONS,
    CLAUDE_CODE_AUTO_COMPACT_WINDOW: () => CLAUDE_CODE_AUTO_COMPACT_WINDOW,
    CLAUDE_CODE_ARTIFACT_AUTO_OPEN: () => CLAUDE_CODE_ARTIFACT_AUTO_OPEN,
    CLAUDE_CODE_ARTIFACTS_API_BASE_URL: () => CLAUDE_CODE_ARTIFACTS_API_BASE_URL,
    CLAUDE_CODE_ARTIFACT: () => CLAUDE_CODE_ARTIFACT,
    CLAUDE_CODE_AGENT: () => CLAUDE_CODE_AGENT,
    CLAUDE_CODE_ADDITIONAL_PROTECTION: () => CLAUDE_CODE_ADDITIONAL_PROTECTION,
    CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD: () => CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD,
    CLAUDE_CODE_ACTION: () => CLAUDE_CODE_ACTION,
    CLAUDE_CLIENT_PRESENCE_FILE: () => CLAUDE_CLIENT_PRESENCE_FILE,
    CLAUDE_CHROME_PERMISSION_MODE: () => CLAUDE_CHROME_PERMISSION_MODE,
    CLAUDE_BRIDGE_USE_CCR_V2: () => CLAUDE_BRIDGE_USE_CCR_V2,
    CLAUDE_BRIDGE_SESSION_INGRESS_URL: () => CLAUDE_BRIDGE_SESSION_INGRESS_URL,
    CLAUDE_BRIDGE_REATTACH_SESSION: () => CLAUDE_BRIDGE_REATTACH_SESSION,
    CLAUDE_BRIDGE_REATTACH_SEQ: () => CLAUDE_BRIDGE_REATTACH_SEQ,
    CLAUDE_BRIDGE_OAUTH_TOKEN: () => CLAUDE_BRIDGE_OAUTH_TOKEN,
    CLAUDE_BRIDGE_BASE_URL: () => CLAUDE_BRIDGE_BASE_URL,
    CLAUDE_BG_STARTUP_WEDGE_MS: () => CLAUDE_BG_STARTUP_WEDGE_MS,
    CLAUDE_BG_SOURCE: () => CLAUDE_BG_SOURCE,
    CLAUDE_BG_SOCKET_TOKENS_PATH: () => CLAUDE_BG_SOCKET_TOKENS_PATH,
    CLAUDE_BG_RV_AUTH: () => CLAUDE_BG_RV_AUTH,
    CLAUDE_BG_RENDEZVOUS_SOCK: () => CLAUDE_BG_RENDEZVOUS_SOCK,
    CLAUDE_BG_PTY_AUTH: () => CLAUDE_BG_PTY_AUTH,
    CLAUDE_BG_POST_CLEAR_RESPAWN: () => CLAUDE_BG_POST_CLEAR_RESPAWN,
    CLAUDE_BG_ISOLATION: () => CLAUDE_BG_ISOLATION,
    CLAUDE_BG_CLAIM_AUTH: () => CLAUDE_BG_CLAIM_AUTH,
    CLAUDE_BG_BACKEND: () => CLAUDE_BG_BACKEND,
    CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR: () => CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR,
    CLAUDE_AUTO_BACKGROUND_TASKS: () => CLAUDE_AUTO_BACKGROUND_TASKS,
    CLAUDE_AUTOCOMPACT_PCT_OVERRIDE: () => CLAUDE_AUTOCOMPACT_PCT_OVERRIDE,
    CLAUDE_ASYNC_AGENT_STALL_TIMEOUT_MS: () => CLAUDE_ASYNC_AGENT_STALL_TIMEOUT_MS,
    CLAUDE_AGENT_SDK_VERSION: () => CLAUDE_AGENT_SDK_VERSION,
    CLAUDE_AGENT_SDK_MCP_NO_PREFIX: () => CLAUDE_AGENT_SDK_MCP_NO_PREFIX,
    CLAUDE_AGENT_SDK_DISABLE_BUILTIN_AGENTS: () => CLAUDE_AGENT_SDK_DISABLE_BUILTIN_AGENTS,
    CLAUDE_AGENT_SDK_CLIENT_APP: () => CLAUDE_AGENT_SDK_CLIENT_APP,
    CLAUDE_AGENTS_SELECT: () => CLAUDE_AGENTS_SELECT,
    CLAUDE_AFTER_LAST_COMPACT: () => CLAUDE_AFTER_LAST_COMPACT,
    CLAUDE_AFK_TIMEOUT_MS: () => CLAUDE_AFK_TIMEOUT_MS,
    CLAUDE_AFK_COUNTDOWN_MS: () => CLAUDE_AFK_COUNTDOWN_MS,
    CLAUDECODE: () => CLAUDECODE,
    CLAUBBIT: () => CLAUBBIT,
    BASH_MAX_OUTPUT_LENGTH: () => BASH_MAX_OUTPUT_LENGTH,
    ANTHROPIC_CONFIG_DIR: () => ANTHROPIC_CONFIG_DIR,
    ALLOW_ANT_COMPUTER_USE_MCP: () => ALLOW_ANT_COMPUTER_USE_MCP,
    AI_AGENT: () => AI_AGENT
  });
  var ANTHROPIC_CONFIG_DIR;
  var CLAUDE_AFTER_LAST_COMPACT;
  var CLAUDE_AGENTS_SELECT;
  var CLAUDE_AGENT_SDK_CLIENT_APP;
  var CLAUDE_AGENT_SDK_VERSION;
  var CLAUDE_AUTOCOMPACT_PCT_OVERRIDE;
  var CLAUDE_BG_BACKEND;
  var CLAUDE_BG_CLAIM_AUTH;
  var CLAUDE_BG_ISOLATION;
  var CLAUDE_BG_POST_CLEAR_RESPAWN;
  var CLAUDE_BG_PTY_AUTH;
  var CLAUDE_BG_RENDEZVOUS_SOCK;
  var CLAUDE_BG_RV_AUTH;
  var CLAUDE_BG_SOCKET_TOKENS_PATH;
  var CLAUDE_BG_SOURCE;
  var CLAUDE_BRIDGE_BASE_URL;
  var CLAUDE_BRIDGE_OAUTH_TOKEN;
  var CLAUDE_BRIDGE_REATTACH_SESSION;
  var CLAUDE_BRIDGE_SESSION_INGRESS_URL;
  var CLAUDE_CHROME_PERMISSION_MODE;
  var CLAUDE_CLIENT_PRESENCE_FILE;
  var CLAUDE_CODE_ACTION;
  var CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD;
  var CLAUDE_CODE_AGENT;
  var CLAUDE_CODE_ARTIFACT;
  var CLAUDE_CODE_ARTIFACT_AUTO_OPEN;
  var CLAUDE_CODE_ARTIFACTS_API_BASE_URL;
  var CLAUDE_CODE_AUTO_COMPACT_WINDOW;
  var CLAUDE_CODE_BASE_REF;
  var CLAUDE_CODE_BASE_REFS;
  var CLAUDE_CODE_BLOCKING_LIMIT_OVERRIDE;
  var CLAUDE_CODE_CLASSIFIER_SUMMARY;
  var CLAUDE_CODE_CONTAINER_ID;
  var CLAUDE_CODE_DECSTBM;
  var CLAUDE_CODE_DEV_RAW_CHANGELOG_URL;
  var CLAUDE_CODE_DISABLE_WORKING_SYNC;
  var CLAUDE_CODE_ENTRYPOINT;
  var CLAUDE_CODE_ENVIRONMENT_KIND;
  var CLAUDE_CODE_ENVIRONMENT_RUNNER_VERSION;
  var CLAUDE_CODE_FORCE_TIP_ID;
  var CLAUDE_CODE_GIT_BASH_PATH;
  var CLAUDE_CODE_HIDE_SETTINGS_HINT;
  var CLAUDE_CODE_HOST_PLATFORM;
  var CLAUDE_CODE_IDE_HOST_OVERRIDE;
  var CLAUDE_CODE_MANAGED_SETTINGS_PATH;
  var CLAUDE_CODE_MCP_ALLOWLIST_ENV;
  var CLAUDE_CODE_MID_CONVERSATION_SYSTEM;
  var CLAUDE_CODE_OVERRIDE_DATE;
  var CLAUDE_CODE_PERFORCE_MODE;
  var CLAUDE_CODE_PLAN_MODE_INTERVIEW_PHASE;
  var CLAUDE_CODE_PLUGIN_CACHE_DIR;
  var CLAUDE_CODE_PLUGIN_SEED_DIR;
  var CLAUDE_CODE_POWERUP_ONBOARDING;
  var CLAUDE_CODE_QUESTION_PREVIEW_FORMAT;
  var CLAUDE_CODE_REMOTE_ENVIRONMENT_TYPE;
  var CLAUDE_CODE_REMOTE_MEMORY_DIR;
  var CLAUDE_CODE_REMOTE_RAW_EVENTS_FILE;
  var CLAUDE_CODE_REMOTE_SESSION_ID;
  var CLAUDE_CODE_REMOTE_SETTINGS_PATH;
  var CLAUDE_CODE_REPO_CHECKOUTS;
  var CLAUDE_CODE_RESUME_FROM_SESSION;
  var CLAUDE_CODE_RESUME_PROMPT;
  var CLAUDE_CODE_SCROLL_SPEED;
  var CLAUDE_CODE_SESSION_ID;
  var CLAUDE_CODE_SESSION_KIND;
  var CLAUDE_CODE_SESSION_NAME;
  var CLAUDE_CODE_SHELL;
  var CLAUDE_CODE_SHELL_PREFIX;
  var CLAUDE_CODE_SIMPLE_SYSTEM_PROMPT;
  var CLAUDE_CODE_STALL_TIMEOUT_MS_FOR_TESTING;
  var CLAUDE_CODE_SYSTEM_PROMPT_GB_FEATURE;
  var CLAUDE_CODE_TAGS;
  var CLAUDE_CODE_TASK_LIST_ID;
  var CLAUDE_CODE_TEST_FIXTURES_ROOT;
  var CLAUDE_CODE_TMPDIR;
  var CLAUDE_CODE_TMUX_PREFIX;
  var CLAUDE_CODE_TMUX_SESSION;
  var CLAUDE_CODE_ULTRAREVIEW_PREFLIGHT_FIXTURE;
  var CLAUDE_CODE_WORKSPACE_HOST_PATHS;
  var CLAUDE_CONFIG_DIR;
  var CLAUDE_COWORK_MEMORY_EXTRA_GUIDELINES;
  var CLAUDE_COWORK_MEMORY_GUIDELINES;
  var CLAUDE_COWORK_MEMORY_INDEX_CONTENT;
  var CLAUDE_COWORK_MEMORY_PATH_OVERRIDE;
  var CLAUDE_ENV_FILE;
  var CLAUDE_INTERNAL_ASSISTANT_TEAM_NAME;
  var CLAUDE_INTERNAL_FC_OVERRIDES;
  var CLAUDE_JOB_DIR;
  var CLAUDE_REMOTE_CONTROL_SESSION_NAME_PREFIX;
  var CLAUDE_REPL_VARIANT;
  var CLAUDE_RUNNER_FETCH_DEPTH;
  var CLAUDE_SNIP;
  var CLAUDE_SSH_LOCAL_BINARY;
  var CLAUDE_SSH_VERSION;
  var CLAUDE_STAGE_FILE_ROOT;
  var CLAUDE_TMPDIR;
  var MCP_OAUTH_CLIENT_METADATA_URL;
  var MCP_TRUNCATION_PROMPT_OVERRIDE;
  var SESSION_INGRESS_URL;
  var TEAM_MEMORY_SYNC_URL;
  var ULTRAPLAN_PROMPT_FILE;
  var VOICE_STREAM_BASE_URL;
  var AI_AGENT;
  var ALLOW_ANT_COMPUTER_USE_MCP;
  var CLAUBBIT;
  var CLAUDECODE;
  var CLAUDE_AGENT_SDK_DISABLE_BUILTIN_AGENTS;
  var CLAUDE_AGENT_SDK_MCP_NO_PREFIX;
  var CLAUDE_AUTO_BACKGROUND_TASKS;
  var CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR;
  var CLAUDE_BRIDGE_USE_CCR_V2;
  var CLAUDE_CODE_ADDITIONAL_PROTECTION;
  var CLAUDE_CODE_AUTO_MODE_EXTERNAL_PERMISSIONS;
  var CLAUDE_CODE_BRIEF;
  var CLAUDE_CODE_BRIEF_UPLOAD;
  var CLAUDE_CODE_DAEMON_COLD_START;
  var CLAUDE_CODE_DISABLE_BG_SHELL_PRESSURE_REAP;
  var CLAUDE_CODE_DONT_INHERIT_ENV;
  var CLAUDE_CODE_EMIT_SESSION_STATE_EVENTS;
  var CLAUDE_CODE_EMIT_TOOL_USE_SUMMARIES;
  var CLAUDE_CODE_EXIT_AFTER_FIRST_RENDER;
  var CLAUDE_CODE_FORCE_BRIDGE;
  var CLAUDE_CODE_FORCE_EVALUATE_MEMORY;
  var CLAUDE_CODE_FORCE_FULLSCREEN_UPSELL;
  var CLAUDE_CODE_FORCE_FULL_LOGO;
  var CLAUDE_CODE_FORCE_MEMORY_SURVEY;
  var CLAUDE_CODE_INVESTIGATE_FIRST;
  var CLAUDE_CODE_IS_COWORK;
  var CLAUDE_CODE_LOOP_PERSISTENT;
  var CLAUDE_CODE_MOCK_REMOTE_SETTINGS;
  var CLAUDE_CODE_MOCK_TRIAL;
  var CLAUDE_CODE_POST_FOR_SESSION_INGRESS_V2;
  var CLAUDE_CODE_REMOTE;
  var CLAUDE_CODE_REMOTE_HERMETIC_MODE;
  var CLAUDE_CODE_REMOTE_SEND_KEEPALIVES;
  var CLAUDE_CODE_REPL;
  var CLAUDE_CODE_RESUME_INTERRUPTED_TURN;
  var CLAUDE_CODE_SANDBOXED;
  var CLAUDE_CODE_SIMPLE;
  var CLAUDE_CODE_SUBPROCESS_ENV_SCRUB;
  var CLAUDE_CODE_SUPERVISED;
  var CLAUDE_CODE_SYNC_PLUGINS_BUFFERED_DOWNLOAD;
  var CLAUDE_CODE_SYNC_PLUGINS_DOWNLOAD_STALL_MS;
  var CLAUDE_CODE_PARKED_PERMISSION_WAIT_MS;
  var CLAUDE_CODE_SYNTAX_HIGHLIGHT;
  var CLAUDE_CODE_TEST_FORCE_DENY;
  var CLAUDE_CODE_TEST_NO_GIT_BASH;
  var CLAUDE_CODE_TEST_NO_PWSH;
  var CLAUDE_CODE_TMUX_PREFIX_CONFLICTS;
  var CLAUDE_CODE_TMUX_TRUECOLOR;
  var CLAUDE_CODE_TUI_JUST_SWITCHED;
  var CLAUDE_FORCE_DISPLAY_SURVEY;
  var CLAUDE_INTERNAL_WARM_RESUME_QA;
  var LOCAL_BRIDGE;
  var MCP_CONNECTION_NONBLOCKING;
  var TEST_ENABLE_SESSION_PERSISTENCE;
  var VCR_RECORD;
  var BASH_MAX_OUTPUT_LENGTH;
  var CLAUDE_AFK_COUNTDOWN_MS;
  var CLAUDE_AFK_TIMEOUT_MS;
  var CLAUDE_ASYNC_AGENT_STALL_TIMEOUT_MS;
  var CLAUDE_BG_STARTUP_WEDGE_MS;
  var CLAUDE_BRIDGE_REATTACH_SEQ;
  var CLAUDE_CODE_EXIT_AFTER_STOP_DELAY;
  var CLAUDE_CODE_FABLE_BRIDGE_DIALOG_TIMEOUT_MS;
  var CLAUDE_CODE_GLOB_TIMEOUT_SECONDS;
  var CLAUDE_CODE_IDLE_THRESHOLD_MINUTES;
  var CLAUDE_CODE_IDLE_TOKEN_THRESHOLD;
  var CLAUDE_CODE_PLAN_V2_AGENT_COUNT;
  var CLAUDE_CODE_PLAN_V2_EXPLORE_AGENT_COUNT;
  var CLAUDE_CODE_PLUGIN_GIT_TIMEOUT_MS;
  var CLAUDE_CODE_PWSH_PARSE_TIMEOUT_MS;
  var CLAUDE_CODE_REMOTE_SETTINGS_POLL_MS;
  var CLAUDE_CODE_RESUME_THRESHOLD_MINUTES;
  var CLAUDE_CODE_RESUME_TOKEN_THRESHOLD;
  var CLAUDE_CODE_SCRIPT_CAPS;
  var CLAUDE_CODE_SESSIONEND_HOOKS_TIMEOUT_MS;
  var CLAUDE_CODE_SSE_PORT;
  var CLAUDE_CODE_SYNC_PLUGIN_INSTALL_TIMEOUT_MS;
  var CLAUDE_CODE_SYNC_SKILLS_INSTALL_TIMEOUT_MS;
  var CLAUDE_CODE_SYNC_SKILLS_WAIT_TIMEOUT_MS;
  var CLAUDE_CODE_USER_DIALOG_TIMEOUT_MS;
  var CLAUDE_CODE_WORKER_EPOCH;
  var CLAUDE_SERVE_DRAIN_TIMEOUT_MS;
  var CLAUDE_SUBAGENT_BG_SHELL_MAX_MS;
  var MCP_CONNECT_TIMEOUT_MS;
  var MCP_OAUTH_CALLBACK_PORT;
  var MCP_REMOTE_SERVER_CONNECTION_BATCH_SIZE;
  var MCP_SERVER_CONNECTION_BATCH_SIZE;
  var MCP_TIMEOUT;
  var MCP_TOOL_TIMEOUT;
  var CLAUDE_CODE_MCP_TOOL_IDLE_TIMEOUT;
  var CLAUDE_CODE_MCP_AUTO_BACKGROUND_MS;
  var SLASH_COMMAND_TOOL_CHAR_BUDGET;
  var TASK_MAX_OUTPUT_LENGTH;
  var tRs = __lazy(() => {
    ile();
    ANTHROPIC_CONFIG_DIR = $e.str();
    CLAUDE_AFTER_LAST_COMPACT = $e.str();
    CLAUDE_AGENTS_SELECT = $e.str();
    CLAUDE_AGENT_SDK_CLIENT_APP = $e.str();
    CLAUDE_AGENT_SDK_VERSION = $e.str();
    CLAUDE_AUTOCOMPACT_PCT_OVERRIDE = $e.str();
    CLAUDE_BG_BACKEND = $e.str();
    CLAUDE_BG_CLAIM_AUTH = $e.str();
    CLAUDE_BG_ISOLATION = $e.str();
    CLAUDE_BG_POST_CLEAR_RESPAWN = $e.bool();
    CLAUDE_BG_PTY_AUTH = $e.str();
    CLAUDE_BG_RENDEZVOUS_SOCK = $e.str();
    CLAUDE_BG_RV_AUTH = $e.str();
    CLAUDE_BG_SOCKET_TOKENS_PATH = $e.str();
    CLAUDE_BG_SOURCE = $e.str();
    CLAUDE_BRIDGE_BASE_URL = $e.str();
    CLAUDE_BRIDGE_OAUTH_TOKEN = $e.str();
    CLAUDE_BRIDGE_REATTACH_SESSION = $e.str();
    CLAUDE_BRIDGE_SESSION_INGRESS_URL = $e.str();
    CLAUDE_CHROME_PERMISSION_MODE = $e.str();
    CLAUDE_CLIENT_PRESENCE_FILE = $e.str();
    CLAUDE_CODE_ACTION = $e.str();
    CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD = $e.str();
    CLAUDE_CODE_AGENT = $e.str();
    CLAUDE_CODE_ARTIFACT = $e.str();
    CLAUDE_CODE_ARTIFACT_AUTO_OPEN = $e.str();
    CLAUDE_CODE_ARTIFACTS_API_BASE_URL = $e.str();
    CLAUDE_CODE_AUTO_COMPACT_WINDOW = $e.str();
    CLAUDE_CODE_BASE_REF = $e.str();
    CLAUDE_CODE_BASE_REFS = $e.str();
    CLAUDE_CODE_BLOCKING_LIMIT_OVERRIDE = $e.str();
    CLAUDE_CODE_CLASSIFIER_SUMMARY = $e.str();
    CLAUDE_CODE_CONTAINER_ID = $e.str();
    CLAUDE_CODE_DECSTBM = $e.str();
    CLAUDE_CODE_DEV_RAW_CHANGELOG_URL = $e.str();
    CLAUDE_CODE_DISABLE_WORKING_SYNC = $e.bool();
    CLAUDE_CODE_ENTRYPOINT = $e.str();
    CLAUDE_CODE_ENVIRONMENT_KIND = $e.str();
    CLAUDE_CODE_ENVIRONMENT_RUNNER_VERSION = $e.str();
    CLAUDE_CODE_FORCE_TIP_ID = $e.str();
    CLAUDE_CODE_GIT_BASH_PATH = $e.str();
    CLAUDE_CODE_HIDE_SETTINGS_HINT = $e.str();
    CLAUDE_CODE_HOST_PLATFORM = $e.str();
    CLAUDE_CODE_IDE_HOST_OVERRIDE = $e.str();
    CLAUDE_CODE_MANAGED_SETTINGS_PATH = $e.str();
    CLAUDE_CODE_MCP_ALLOWLIST_ENV = $e.str();
    CLAUDE_CODE_MID_CONVERSATION_SYSTEM = $e.str();
    CLAUDE_CODE_OVERRIDE_DATE = $e.str();
    CLAUDE_CODE_PERFORCE_MODE = $e.str();
    CLAUDE_CODE_PLAN_MODE_INTERVIEW_PHASE = $e.str();
    CLAUDE_CODE_PLUGIN_CACHE_DIR = $e.str();
    CLAUDE_CODE_PLUGIN_SEED_DIR = $e.str();
    CLAUDE_CODE_POWERUP_ONBOARDING = $e.str();
    CLAUDE_CODE_QUESTION_PREVIEW_FORMAT = $e.str();
    CLAUDE_CODE_REMOTE_ENVIRONMENT_TYPE = $e.str();
    CLAUDE_CODE_REMOTE_MEMORY_DIR = $e.str();
    CLAUDE_CODE_REMOTE_RAW_EVENTS_FILE = $e.str();
    CLAUDE_CODE_REMOTE_SESSION_ID = $e.str();
    CLAUDE_CODE_REMOTE_SETTINGS_PATH = $e.str();
    CLAUDE_CODE_REPO_CHECKOUTS = $e.str();
    CLAUDE_CODE_RESUME_FROM_SESSION = $e.str();
    CLAUDE_CODE_RESUME_PROMPT = $e.str();
    CLAUDE_CODE_SCROLL_SPEED = $e.str();
    CLAUDE_CODE_SESSION_ID = $e.str();
    CLAUDE_CODE_SESSION_KIND = $e.str();
    CLAUDE_CODE_SESSION_NAME = $e.str();
    CLAUDE_CODE_SHELL = $e.str();
    CLAUDE_CODE_SHELL_PREFIX = $e.str();
    CLAUDE_CODE_SIMPLE_SYSTEM_PROMPT = $e.str();
    CLAUDE_CODE_STALL_TIMEOUT_MS_FOR_TESTING = $e.str();
    CLAUDE_CODE_SYSTEM_PROMPT_GB_FEATURE = $e.str();
    CLAUDE_CODE_TAGS = $e.str();
    CLAUDE_CODE_TASK_LIST_ID = $e.str();
    CLAUDE_CODE_TEST_FIXTURES_ROOT = $e.str();
    CLAUDE_CODE_TMPDIR = $e.str();
    CLAUDE_CODE_TMUX_PREFIX = $e.str();
    CLAUDE_CODE_TMUX_SESSION = $e.str();
    CLAUDE_CODE_ULTRAREVIEW_PREFLIGHT_FIXTURE = $e.str();
    CLAUDE_CODE_WORKSPACE_HOST_PATHS = $e.str();
    CLAUDE_CONFIG_DIR = $e.str();
    CLAUDE_COWORK_MEMORY_EXTRA_GUIDELINES = $e.str();
    CLAUDE_COWORK_MEMORY_GUIDELINES = $e.str();
    CLAUDE_COWORK_MEMORY_INDEX_CONTENT = $e.str();
    CLAUDE_COWORK_MEMORY_PATH_OVERRIDE = $e.str();
    CLAUDE_ENV_FILE = $e.str();
    CLAUDE_INTERNAL_ASSISTANT_TEAM_NAME = $e.str();
    CLAUDE_INTERNAL_FC_OVERRIDES = $e.str();
    CLAUDE_JOB_DIR = $e.str();
    CLAUDE_REMOTE_CONTROL_SESSION_NAME_PREFIX = $e.str();
    CLAUDE_REPL_VARIANT = $e.str();
    CLAUDE_RUNNER_FETCH_DEPTH = $e.str();
    CLAUDE_SNIP = $e.str();
    CLAUDE_SSH_LOCAL_BINARY = $e.str();
    CLAUDE_SSH_VERSION = $e.str();
    CLAUDE_STAGE_FILE_ROOT = $e.str();
    CLAUDE_TMPDIR = $e.str();
    MCP_OAUTH_CLIENT_METADATA_URL = $e.str();
    MCP_TRUNCATION_PROMPT_OVERRIDE = $e.str();
    SESSION_INGRESS_URL = $e.str();
    TEAM_MEMORY_SYNC_URL = $e.str();
    ULTRAPLAN_PROMPT_FILE = $e.str();
    VOICE_STREAM_BASE_URL = $e.str();
    AI_AGENT = $e.bool();
    ALLOW_ANT_COMPUTER_USE_MCP = $e.bool();
    CLAUBBIT = $e.bool();
    CLAUDECODE = $e.bool();
    CLAUDE_AGENT_SDK_DISABLE_BUILTIN_AGENTS = $e.bool();
    CLAUDE_AGENT_SDK_MCP_NO_PREFIX = $e.bool();
    CLAUDE_AUTO_BACKGROUND_TASKS = $e.bool();
    CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR = $e.bool();
    CLAUDE_BRIDGE_USE_CCR_V2 = $e.bool();
    CLAUDE_CODE_ADDITIONAL_PROTECTION = $e.bool();
    CLAUDE_CODE_AUTO_MODE_EXTERNAL_PERMISSIONS = $e.bool();
    CLAUDE_CODE_BRIEF = $e.bool();
    CLAUDE_CODE_BRIEF_UPLOAD = $e.bool();
    CLAUDE_CODE_DAEMON_COLD_START = $e.bool();
    CLAUDE_CODE_DISABLE_BG_SHELL_PRESSURE_REAP = $e.bool();
    CLAUDE_CODE_DONT_INHERIT_ENV = $e.bool();
    CLAUDE_CODE_EMIT_SESSION_STATE_EVENTS = $e.bool();
    CLAUDE_CODE_EMIT_TOOL_USE_SUMMARIES = $e.bool();
    CLAUDE_CODE_EXIT_AFTER_FIRST_RENDER = $e.bool();
    CLAUDE_CODE_FORCE_BRIDGE = $e.bool();
    CLAUDE_CODE_FORCE_EVALUATE_MEMORY = $e.bool();
    CLAUDE_CODE_FORCE_FULLSCREEN_UPSELL = $e.bool();
    CLAUDE_CODE_FORCE_FULL_LOGO = $e.bool();
    CLAUDE_CODE_FORCE_MEMORY_SURVEY = $e.bool();
    CLAUDE_CODE_INVESTIGATE_FIRST = $e.bool();
    CLAUDE_CODE_IS_COWORK = $e.bool();
    CLAUDE_CODE_LOOP_PERSISTENT = $e.bool();
    CLAUDE_CODE_MOCK_REMOTE_SETTINGS = $e.bool();
    CLAUDE_CODE_MOCK_TRIAL = $e.bool();
    CLAUDE_CODE_POST_FOR_SESSION_INGRESS_V2 = $e.bool();
    CLAUDE_CODE_REMOTE = $e.bool();
    CLAUDE_CODE_REMOTE_HERMETIC_MODE = $e.bool();
    CLAUDE_CODE_REMOTE_SEND_KEEPALIVES = $e.bool();
    CLAUDE_CODE_REPL = $e.bool();
    CLAUDE_CODE_RESUME_INTERRUPTED_TURN = $e.bool();
    CLAUDE_CODE_SANDBOXED = $e.bool();
    CLAUDE_CODE_SIMPLE = $e.bool();
    CLAUDE_CODE_SUBPROCESS_ENV_SCRUB = $e.bool();
    CLAUDE_CODE_SUPERVISED = $e.bool();
    CLAUDE_CODE_SYNC_PLUGINS_BUFFERED_DOWNLOAD = $e.bool();
    CLAUDE_CODE_SYNC_PLUGINS_DOWNLOAD_STALL_MS = $e.int({
      min: 1
    });
    CLAUDE_CODE_PARKED_PERMISSION_WAIT_MS = $e.int({
      min: 0
    });
    CLAUDE_CODE_SYNTAX_HIGHLIGHT = $e.bool();
    CLAUDE_CODE_TEST_FORCE_DENY = $e.bool();
    CLAUDE_CODE_TEST_NO_GIT_BASH = $e.bool();
    CLAUDE_CODE_TEST_NO_PWSH = $e.bool();
    CLAUDE_CODE_TMUX_PREFIX_CONFLICTS = $e.bool();
    CLAUDE_CODE_TMUX_TRUECOLOR = $e.bool();
    CLAUDE_CODE_TUI_JUST_SWITCHED = $e.str();
    CLAUDE_FORCE_DISPLAY_SURVEY = $e.bool();
    CLAUDE_INTERNAL_WARM_RESUME_QA = $e.bool();
    LOCAL_BRIDGE = $e.bool();
    MCP_CONNECTION_NONBLOCKING = $e.bool();
    TEST_ENABLE_SESSION_PERSISTENCE = $e.bool();
    VCR_RECORD = $e.bool();
    BASH_MAX_OUTPUT_LENGTH = $e.int();
    CLAUDE_AFK_COUNTDOWN_MS = $e.int();
    CLAUDE_AFK_TIMEOUT_MS = $e.int();
    CLAUDE_ASYNC_AGENT_STALL_TIMEOUT_MS = $e.int();
    CLAUDE_BG_STARTUP_WEDGE_MS = $e.int();
    CLAUDE_BRIDGE_REATTACH_SEQ = $e.int();
    CLAUDE_CODE_EXIT_AFTER_STOP_DELAY = $e.int();
    CLAUDE_CODE_FABLE_BRIDGE_DIALOG_TIMEOUT_MS = $e.int();
    CLAUDE_CODE_GLOB_TIMEOUT_SECONDS = $e.int();
    CLAUDE_CODE_IDLE_THRESHOLD_MINUTES = $e.int();
    CLAUDE_CODE_IDLE_TOKEN_THRESHOLD = $e.int();
    CLAUDE_CODE_PLAN_V2_AGENT_COUNT = $e.int();
    CLAUDE_CODE_PLAN_V2_EXPLORE_AGENT_COUNT = $e.int();
    CLAUDE_CODE_PLUGIN_GIT_TIMEOUT_MS = $e.int();
    CLAUDE_CODE_PWSH_PARSE_TIMEOUT_MS = $e.int();
    CLAUDE_CODE_REMOTE_SETTINGS_POLL_MS = $e.int();
    CLAUDE_CODE_RESUME_THRESHOLD_MINUTES = $e.int();
    CLAUDE_CODE_RESUME_TOKEN_THRESHOLD = $e.int();
    CLAUDE_CODE_SCRIPT_CAPS = $e.int();
    CLAUDE_CODE_SESSIONEND_HOOKS_TIMEOUT_MS = $e.int();
    CLAUDE_CODE_SSE_PORT = $e.int();
    CLAUDE_CODE_SYNC_PLUGIN_INSTALL_TIMEOUT_MS = $e.int();
    CLAUDE_CODE_SYNC_SKILLS_INSTALL_TIMEOUT_MS = $e.int();
    CLAUDE_CODE_SYNC_SKILLS_WAIT_TIMEOUT_MS = $e.int();
    CLAUDE_CODE_USER_DIALOG_TIMEOUT_MS = $e.int();
    CLAUDE_CODE_WORKER_EPOCH = $e.int();
    CLAUDE_SERVE_DRAIN_TIMEOUT_MS = $e.int();
    CLAUDE_SUBAGENT_BG_SHELL_MAX_MS = $e.int();
    MCP_CONNECT_TIMEOUT_MS = $e.int();
    MCP_OAUTH_CALLBACK_PORT = $e.int();
    MCP_REMOTE_SERVER_CONNECTION_BATCH_SIZE = $e.int();
    MCP_SERVER_CONNECTION_BATCH_SIZE = $e.int();
    MCP_TIMEOUT = $e.int();
    MCP_TOOL_TIMEOUT = $e.int();
    CLAUDE_CODE_MCP_TOOL_IDLE_TIMEOUT = $e.int();
    CLAUDE_CODE_MCP_AUTO_BACKGROUND_MS = $e.int();
    SLASH_COMMAND_TOOL_CHAR_BUDGET = $e.int();
    TASK_MAX_OUTPUT_LENGTH = $e.int();
  });
  var sMr = {};