package com.pvporbit.freetype;

import defpackage.mdj;
import kotlin.Metadata;

/* JADX INFO: loaded from: classes2.dex */
@Metadata(d1 = {"\u0000\u000e\n\u0000\n\u0002\u0010\u0011\n\u0002\u0010\u000e\n\u0002\b\u0002\"\u0016\u0010\u0000\u001a\b\u0012\u0004\u0012\u00020\u00020\u0001X\u0082\u0004¢\u0006\u0004\n\u0002\u0010\u0003¨\u0006\u0004"}, d2 = {"constTable", "", "", "[Ljava/lang/String;", "mathdisplaylib"}, k = 2, mv = {2, 2, 0}, xi = mdj.f)
public final class MTFreeTypeMathTableKt {
    private static final String[] constTable = {"int16", "ScriptPercentScaleDown", "int16", "ScriptScriptPercentScaleDown", "uint16", "DelimitedSubFormulaMinHeight", "uint16", "DisplayOperatorMinHeight", "MathValueRecord", "MathLeading", "MathValueRecord", "AxisHeight", "MathValueRecord", "AccentBaseHeight", "MathValueRecord", "FlattenedAccentBaseHeight", "MathValueRecord", "SubscriptShiftDown", "MathValueRecord", "SubscriptTopMax", "MathValueRecord", "SubscriptBaselineDropMin", "MathValueRecord", "SuperscriptShiftUp", "MathValueRecord", "SuperscriptShiftUpCramped", "MathValueRecord", "SuperscriptBottomMin", "MathValueRecord", "SuperscriptBaselineDropMax", "MathValueRecord", "SubSuperscriptGapMin", "MathValueRecord", "SuperscriptBottomMaxWithSubscript", "MathValueRecord", "SpaceAfterScript", "MathValueRecord", "UpperLimitGapMin", "MathValueRecord", "UpperLimitBaselineRiseMin", "MathValueRecord", "LowerLimitGapMin", "MathValueRecord", "LowerLimitBaselineDropMin", "MathValueRecord", "StackTopShiftUp", "MathValueRecord", "StackTopDisplayStyleShiftUp", "MathValueRecord", "StackBottomShiftDown", "MathValueRecord", "StackBottomDisplayStyleShiftDown", "MathValueRecord", "StackGapMin", "MathValueRecord", "StackDisplayStyleGapMin", "MathValueRecord", "StretchStackTopShiftUp", "MathValueRecord", "StretchStackBottomShiftDown", "MathValueRecord", "StretchStackGapAboveMin", "MathValueRecord", "StretchStackGapBelowMin", "MathValueRecord", "FractionNumeratorShiftUp", "MathValueRecord", "FractionNumeratorDisplayStyleShiftUp", "MathValueRecord", "FractionDenominatorShiftDown", "MathValueRecord", "FractionDenominatorDisplayStyleShiftDown", "MathValueRecord", "FractionNumeratorGapMin", "MathValueRecord", "FractionNumDisplayStyleGapMin", "MathValueRecord", "FractionRuleThickness", "MathValueRecord", "FractionDenominatorGapMin", "MathValueRecord", "FractionDenomDisplayStyleGapMin", "MathValueRecord", "SkewedFractionHorizontalGap", "MathValueRecord", "SkewedFractionVerticalGap", "MathValueRecord", "OverbarVerticalGap", "MathValueRecord", "OverbarRuleThickness", "MathValueRecord", "OverbarExtraAscender", "MathValueRecord", "UnderbarVerticalGap", "MathValueRecord", "UnderbarRuleThickness", "MathValueRecord", "UnderbarExtraDescender", "MathValueRecord", "RadicalVerticalGap", "MathValueRecord", "RadicalDisplayStyleVerticalGap", "MathValueRecord", "RadicalRuleThickness", "MathValueRecord", "RadicalExtraAscender", "MathValueRecord", "RadicalKernBeforeDegree", "MathValueRecord", "RadicalKernAfterDegree", "uint16", "RadicalDegreeBottomRaisePercent"};
}
