  __export(wOr, {
    OTEL_TRACES_EXPORT_INTERVAL: () => OTEL_TRACES_EXPORT_INTERVAL,
    OTEL_TRACES_EXPORTER: () => OTEL_TRACES_EXPORTER,
    OTEL_RESOURCE_ATTRIBUTES: () => OTEL_RESOURCE_ATTRIBUTES,
    OTEL_METRIC_EXPORT_INTERVAL: () => OTEL_METRIC_EXPORT_INTERVAL,
    OTEL_METRICS_EXPORTER: () => OTEL_METRICS_EXPORTER,
    OTEL_LOG_USER_PROMPTS: () => OTEL_LOG_USER_PROMPTS,
    OTEL_LOG_TOOL_DETAILS: () => OTEL_LOG_TOOL_DETAILS,
    OTEL_LOG_TOOL_CONTENT: () => OTEL_LOG_TOOL_CONTENT,
    OTEL_LOG_RAW_API_BODIES: () => OTEL_LOG_RAW_API_BODIES,
    OTEL_LOG_ASSISTANT_RESPONSES: () => OTEL_LOG_ASSISTANT_RESPONSES,
    OTEL_LOGS_EXPORT_INTERVAL: () => OTEL_LOGS_EXPORT_INTERVAL,
    OTEL_LOGS_EXPORTER: () => OTEL_LOGS_EXPORTER,
    OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: () => OTEL_EXPORTER_OTLP_TRACES_PROTOCOL,
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: () => OTEL_EXPORTER_OTLP_TRACES_ENDPOINT,
    OTEL_EXPORTER_OTLP_PROTOCOL: () => OTEL_EXPORTER_OTLP_PROTOCOL,
    OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: () => OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE,
    OTEL_EXPORTER_OTLP_METRICS_PROTOCOL: () => OTEL_EXPORTER_OTLP_METRICS_PROTOCOL,
    OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: () => OTEL_EXPORTER_OTLP_METRICS_ENDPOINT,
    OTEL_EXPORTER_OTLP_LOGS_PROTOCOL: () => OTEL_EXPORTER_OTLP_LOGS_PROTOCOL,
    OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: () => OTEL_EXPORTER_OTLP_LOGS_ENDPOINT,
    OTEL_EXPORTER_OTLP_HEADERS: () => OTEL_EXPORTER_OTLP_HEADERS,
    OTEL_EXPORTER_OTLP_ENDPOINT: () => OTEL_EXPORTER_OTLP_ENDPOINT,
    DEBUG_SDK: () => DEBUG_SDK,
    DEBUG_CLAUDE_AGENT_SDK: () => DEBUG_CLAUDE_AGENT_SDK,
    CLAUDE_PTY_RECORD: () => CLAUDE_PTY_RECORD,
    CLAUDE_DEBUG: () => CLAUDE_DEBUG,
    CLAUDE_CODE_TERMINAL_RECORDING: () => CLAUDE_CODE_TERMINAL_RECORDING,
    CLAUDE_CODE_TEE_SDK_STDOUT: () => CLAUDE_CODE_TEE_SDK_STDOUT,
    CLAUDE_CODE_SESSION_LOG: () => CLAUDE_CODE_SESSION_LOG,
    CLAUDE_CODE_PROFILE_STARTUP: () => CLAUDE_CODE_PROFILE_STARTUP,
    CLAUDE_CODE_PROFILE_QUERY: () => CLAUDE_CODE_PROFILE_QUERY,
    CLAUDE_CODE_PERFETTO_WRITE_INTERVAL_S: () => CLAUDE_CODE_PERFETTO_WRITE_INTERVAL_S,
    CLAUDE_CODE_PERFETTO_TRACE: () => CLAUDE_CODE_PERFETTO_TRACE,
    CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS: () => CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS,
    CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS: () => CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS,
    CLAUDE_CODE_OTEL_FLUSH_TIMEOUT_MS: () => CLAUDE_CODE_OTEL_FLUSH_TIMEOUT_MS,
    CLAUDE_CODE_OTEL_DIAG_STDERR: () => CLAUDE_CODE_OTEL_DIAG_STDERR,
    CLAUDE_CODE_JSONL_TRANSCRIPT: () => CLAUDE_CODE_JSONL_TRANSCRIPT,
    CLAUDE_CODE_FRAME_TIMING_SAMPLE_EVERY: () => CLAUDE_CODE_FRAME_TIMING_SAMPLE_EVERY,
    CLAUDE_CODE_FRAME_TIMING_LOG: () => CLAUDE_CODE_FRAME_TIMING_LOG,
    CLAUDE_CODE_ENHANCED_TELEMETRY_BETA: () => CLAUDE_CODE_ENHANCED_TELEMETRY_BETA,
    CLAUDE_CODE_ENABLE_TELEMETRY: () => CLAUDE_CODE_ENABLE_TELEMETRY,
    CLAUDE_CODE_DIAGNOSTICS_FILE: () => CLAUDE_CODE_DIAGNOSTICS_FILE,
    CLAUDE_CODE_DEBUG_REPAINTS: () => CLAUDE_CODE_DEBUG_REPAINTS,
    CLAUDE_CODE_DEBUG_LOG_LEVEL: () => CLAUDE_CODE_DEBUG_LOG_LEVEL,
    CLAUDE_CODE_DEBUG_LOGS_DIR: () => CLAUDE_CODE_DEBUG_LOGS_DIR,
    CLAUDE_CODE_DD_ERROR_TRACKING_FLUSH_INTERVAL_MS: () => CLAUDE_CODE_DD_ERROR_TRACKING_FLUSH_INTERVAL_MS,
    CLAUDE_CODE_DATADOG_FLUSH_INTERVAL_MS: () => CLAUDE_CODE_DATADOG_FLUSH_INTERVAL_MS,
    CLAUDE_CODE_COMMIT_LOG: () => CLAUDE_CODE_COMMIT_LOG,
    CLAUDE_CODE_BYOC_ENABLE_DATADOG: () => CLAUDE_CODE_BYOC_ENABLE_DATADOG,
    CLAUDE_CODE_BENCH_LIVE_COUNTS: () => CLAUDE_CODE_BENCH_LIVE_COUNTS,
    BETA_TRACING_ENDPOINT: () => BETA_TRACING_ENDPOINT,
    ANT_OTEL_TRACES_EXPORTER: () => ANT_OTEL_TRACES_EXPORTER,
    ANT_OTEL_RESOURCE_ATTRIBUTES: () => ANT_OTEL_RESOURCE_ATTRIBUTES,
    ANT_OTEL_METRICS_EXPORTER: () => ANT_OTEL_METRICS_EXPORTER,
    ANT_OTEL_LOGS_EXPORTER: () => ANT_OTEL_LOGS_EXPORTER,
    ANT_OTEL_EXPORTER_OTLP_PROTOCOL: () => ANT_OTEL_EXPORTER_OTLP_PROTOCOL,
    ANT_OTEL_EXPORTER_OTLP_HEADERS: () => ANT_OTEL_EXPORTER_OTLP_HEADERS,
    ANT_OTEL_EXPORTER_OTLP_ENDPOINT: () => ANT_OTEL_EXPORTER_OTLP_ENDPOINT,
    ANT_CLAUDE_CODE_METRICS_ENDPOINT: () => ANT_CLAUDE_CODE_METRICS_ENDPOINT
  });
  var CLAUDE_DEBUG;
  var CLAUDE_CODE_DEBUG_LOG_LEVEL;
  var CLAUDE_CODE_DEBUG_LOGS_DIR;
  var CLAUDE_CODE_DEBUG_REPAINTS;
  var CLAUDE_CODE_DIAGNOSTICS_FILE;
  var DEBUG_CLAUDE_AGENT_SDK;
  var DEBUG_SDK;
  var CLAUDE_CODE_PROFILE_STARTUP;
  var CLAUDE_CODE_PROFILE_QUERY;
  var CLAUDE_CODE_PERFETTO_TRACE;
  var CLAUDE_CODE_PERFETTO_WRITE_INTERVAL_S;
  var CLAUDE_CODE_FRAME_TIMING_LOG;
  var CLAUDE_CODE_FRAME_TIMING_SAMPLE_EVERY;
  var CLAUDE_CODE_COMMIT_LOG;
  var CLAUDE_CODE_SESSION_LOG;
  var CLAUDE_CODE_JSONL_TRANSCRIPT;
  var CLAUDE_PTY_RECORD;
  var CLAUDE_CODE_TERMINAL_RECORDING;
  var CLAUDE_CODE_TEE_SDK_STDOUT;
  var CLAUDE_CODE_BENCH_LIVE_COUNTS;
  var CLAUDE_CODE_ENABLE_TELEMETRY;
  var CLAUDE_CODE_ENHANCED_TELEMETRY_BETA;
  var CLAUDE_CODE_OTEL_FLUSH_TIMEOUT_MS;
  var CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS;
  var CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS;
  var CLAUDE_CODE_DATADOG_FLUSH_INTERVAL_MS;
  var CLAUDE_CODE_DD_ERROR_TRACKING_FLUSH_INTERVAL_MS;
  var CLAUDE_CODE_BYOC_ENABLE_DATADOG;
  var CLAUDE_CODE_OTEL_DIAG_STDERR;
  var OTEL_METRICS_EXPORTER;
  var OTEL_LOGS_EXPORTER;
  var OTEL_TRACES_EXPORTER;
  var OTEL_EXPORTER_OTLP_ENDPOINT;
  var OTEL_EXPORTER_OTLP_HEADERS;
  var OTEL_EXPORTER_OTLP_PROTOCOL;
  var OTEL_EXPORTER_OTLP_LOGS_ENDPOINT;
  var OTEL_EXPORTER_OTLP_LOGS_PROTOCOL;
  var OTEL_EXPORTER_OTLP_METRICS_ENDPOINT;
  var OTEL_EXPORTER_OTLP_METRICS_PROTOCOL;
  var OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE;
  var OTEL_EXPORTER_OTLP_TRACES_ENDPOINT;
  var OTEL_EXPORTER_OTLP_TRACES_PROTOCOL;
  var OTEL_METRIC_EXPORT_INTERVAL;
  var OTEL_LOGS_EXPORT_INTERVAL;
  var OTEL_TRACES_EXPORT_INTERVAL;
  var OTEL_RESOURCE_ATTRIBUTES;
  var OTEL_LOG_USER_PROMPTS;
  var OTEL_LOG_ASSISTANT_RESPONSES;
  var OTEL_LOG_TOOL_CONTENT;
  var OTEL_LOG_TOOL_DETAILS;
  var OTEL_LOG_RAW_API_BODIES;
  var ANT_OTEL_EXPORTER_OTLP_ENDPOINT;
  var ANT_OTEL_EXPORTER_OTLP_HEADERS;
  var ANT_OTEL_EXPORTER_OTLP_PROTOCOL;
  var ANT_OTEL_LOGS_EXPORTER;
  var ANT_OTEL_METRICS_EXPORTER;
  var ANT_OTEL_TRACES_EXPORTER;
  var ANT_OTEL_RESOURCE_ATTRIBUTES;
  var ANT_CLAUDE_CODE_METRICS_ENDPOINT;
  var BETA_TRACING_ENDPOINT;
  var fTs = __lazy(() => {
    ile();
    CLAUDE_DEBUG = $e.bool();
    CLAUDE_CODE_DEBUG_LOG_LEVEL = $e.str();
    CLAUDE_CODE_DEBUG_LOGS_DIR = $e.str();
    CLAUDE_CODE_DEBUG_REPAINTS = $e.bool();
    CLAUDE_CODE_DIAGNOSTICS_FILE = $e.str();
    DEBUG_CLAUDE_AGENT_SDK = $e.bool();
    DEBUG_SDK = $e.bool();
    CLAUDE_CODE_PROFILE_STARTUP = $e.bool();
    CLAUDE_CODE_PROFILE_QUERY = $e.bool();
    CLAUDE_CODE_PERFETTO_TRACE = $e.str();
    CLAUDE_CODE_PERFETTO_WRITE_INTERVAL_S = $e.int();
    CLAUDE_CODE_FRAME_TIMING_LOG = $e.str();
    CLAUDE_CODE_FRAME_TIMING_SAMPLE_EVERY = $e.int();
    CLAUDE_CODE_COMMIT_LOG = $e.str();
    CLAUDE_CODE_SESSION_LOG = $e.str();
    CLAUDE_CODE_JSONL_TRANSCRIPT = $e.str();
    CLAUDE_PTY_RECORD = $e.str();
    CLAUDE_CODE_TERMINAL_RECORDING = $e.str();
    CLAUDE_CODE_TEE_SDK_STDOUT = $e.bool();
    CLAUDE_CODE_BENCH_LIVE_COUNTS = $e.bool();
    CLAUDE_CODE_ENABLE_TELEMETRY = $e.bool();
    CLAUDE_CODE_ENHANCED_TELEMETRY_BETA = $e.bool();
    CLAUDE_CODE_OTEL_FLUSH_TIMEOUT_MS = $e.int();
    CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS = $e.int();
    CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS = $e.int();
    CLAUDE_CODE_DATADOG_FLUSH_INTERVAL_MS = $e.int();
    CLAUDE_CODE_DD_ERROR_TRACKING_FLUSH_INTERVAL_MS = $e.int();
    CLAUDE_CODE_BYOC_ENABLE_DATADOG = $e.bool();
    CLAUDE_CODE_OTEL_DIAG_STDERR = $e.bool();
    OTEL_METRICS_EXPORTER = $e.str();
    OTEL_LOGS_EXPORTER = $e.str();
    OTEL_TRACES_EXPORTER = $e.str();
    OTEL_EXPORTER_OTLP_ENDPOINT = $e.str();
    OTEL_EXPORTER_OTLP_HEADERS = $e.str();
    OTEL_EXPORTER_OTLP_PROTOCOL = $e.str();
    OTEL_EXPORTER_OTLP_LOGS_ENDPOINT = $e.str();
    OTEL_EXPORTER_OTLP_LOGS_PROTOCOL = $e.str();
    OTEL_EXPORTER_OTLP_METRICS_ENDPOINT = $e.str();
    OTEL_EXPORTER_OTLP_METRICS_PROTOCOL = $e.str();
    OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE = $e.str();
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = $e.str();
    OTEL_EXPORTER_OTLP_TRACES_PROTOCOL = $e.str();
    OTEL_METRIC_EXPORT_INTERVAL = $e.int();
    OTEL_LOGS_EXPORT_INTERVAL = $e.int();
    OTEL_TRACES_EXPORT_INTERVAL = $e.int();
    OTEL_RESOURCE_ATTRIBUTES = $e.str();
    OTEL_LOG_USER_PROMPTS = $e.bool();
    OTEL_LOG_ASSISTANT_RESPONSES = $e.triBool();
    OTEL_LOG_TOOL_CONTENT = $e.bool();
    OTEL_LOG_TOOL_DETAILS = $e.bool();
    OTEL_LOG_RAW_API_BODIES = $e.bool();
    ANT_OTEL_EXPORTER_OTLP_ENDPOINT = $e.str();
    ANT_OTEL_EXPORTER_OTLP_HEADERS = $e.str();
    ANT_OTEL_EXPORTER_OTLP_PROTOCOL = $e.str();
    ANT_OTEL_LOGS_EXPORTER = $e.str();
    ANT_OTEL_METRICS_EXPORTER = $e.str();
    ANT_OTEL_TRACES_EXPORTER = $e.str();
    ANT_OTEL_RESOURCE_ATTRIBUTES = $e.str();
    ANT_CLAUDE_CODE_METRICS_ENDPOINT = $e.str();
    BETA_TRACING_ENDPOINT = $e.str();
  });
  function eke(e, t) {
    return e.flatMap((n, r) => r ? [t(r), n] : [n]);
  }
  function Bn(e, t) {
    let n = 0;
    for (let r of e) {
      n += +!!t(r);
    }
    return n;
  }
  function Ro(e) {
    return [...new Set(e)];
  }
  var JOt = {};