  __export(nMr, {
    USE_API_CONTEXT_MANAGEMENT: () => USE_API_CONTEXT_MANAGEMENT,
    USE_API_CLEAR_TOOL_USES: () => USE_API_CLEAR_TOOL_USES,
    USE_API_CLEAR_TOOL_RESULTS: () => USE_API_CLEAR_TOOL_RESULTS,
    FORCE_VCR: () => FORCE_VCR,
    FORCE_PROMPT_CACHING_5M: () => FORCE_PROMPT_CACHING_5M,
    FORCE_CODE_TERMINAL: () => FORCE_CODE_TERMINAL,
    FORCE_AUTOUPDATE_PLUGINS: () => FORCE_AUTOUPDATE_PLUGINS,
    ENABLE_TOOL_SEARCH: () => ENABLE_TOOL_SEARCH,
    ENABLE_SESSION_PERSISTENCE: () => ENABLE_SESSION_PERSISTENCE,
    ENABLE_SESSION_BACKGROUNDING: () => ENABLE_SESSION_BACKGROUNDING,
    ENABLE_PROMPT_CACHING_1H_BEDROCK: () => ENABLE_PROMPT_CACHING_1H_BEDROCK,
    ENABLE_PROMPT_CACHING_1H: () => ENABLE_PROMPT_CACHING_1H,
    ENABLE_PID_BASED_VERSION_LOCKING: () => ENABLE_PID_BASED_VERSION_LOCKING,
    ENABLE_MCP_LARGE_OUTPUT_FILES: () => ENABLE_MCP_LARGE_OUTPUT_FILES,
    ENABLE_LSP_TOOL: () => ENABLE_LSP_TOOL,
    ENABLE_LOCKLESS_UPDATES: () => ENABLE_LOCKLESS_UPDATES,
    ENABLE_ENHANCED_TELEMETRY_BETA: () => ENABLE_ENHANCED_TELEMETRY_BETA,
    ENABLE_CLAUDEAI_MCP_SERVERS: () => ENABLE_CLAUDEAI_MCP_SERVERS,
    ENABLE_BETA_TRACING_DETAILED: () => ENABLE_BETA_TRACING_DETAILED,
    EMBEDDED_SEARCH_TOOLS: () => EMBEDDED_SEARCH_TOOLS,
    DISABLE_UPGRADE_COMMAND: () => DISABLE_UPGRADE_COMMAND,
    DISABLE_UPDATES: () => DISABLE_UPDATES,
    DISABLE_TELEMETRY: () => DISABLE_TELEMETRY,
    DISABLE_PROMPT_CACHING_SONNET: () => DISABLE_PROMPT_CACHING_SONNET,
    DISABLE_PROMPT_CACHING_OPUS: () => DISABLE_PROMPT_CACHING_OPUS,
    DISABLE_PROMPT_CACHING_MYTHOS: () => DISABLE_PROMPT_CACHING_MYTHOS,
    DISABLE_PROMPT_CACHING_HAIKU: () => DISABLE_PROMPT_CACHING_HAIKU,
    DISABLE_PROMPT_CACHING_FABLE: () => DISABLE_PROMPT_CACHING_FABLE,
    DISABLE_PROMPT_CACHING: () => DISABLE_PROMPT_CACHING,
    DISABLE_LOGOUT_COMMAND: () => DISABLE_LOGOUT_COMMAND,
    DISABLE_LOGIN_COMMAND: () => DISABLE_LOGIN_COMMAND,
    DISABLE_INTERLEAVED_THINKING: () => DISABLE_INTERLEAVED_THINKING,
    DISABLE_INSTALL_GITHUB_APP_COMMAND: () => DISABLE_INSTALL_GITHUB_APP_COMMAND,
    DISABLE_INSTALLATION_CHECKS: () => DISABLE_INSTALLATION_CHECKS,
    DISABLE_GROWTHBOOK: () => DISABLE_GROWTHBOOK,
    DISABLE_FEEDBACK_COMMAND: () => DISABLE_FEEDBACK_COMMAND,
    DISABLE_EXTRA_USAGE_COMMAND: () => DISABLE_EXTRA_USAGE_COMMAND,
    DISABLE_ERROR_REPORTING: () => DISABLE_ERROR_REPORTING,
    DISABLE_DOCTOR_COMMAND: () => DISABLE_DOCTOR_COMMAND,
    DISABLE_COST_WARNINGS: () => DISABLE_COST_WARNINGS,
    DISABLE_COMPACT: () => DISABLE_COMPACT,
    DISABLE_BUG_COMMAND: () => DISABLE_BUG_COMMAND,
    DISABLE_BRIEF_MODE_STOP_HOOK: () => DISABLE_BRIEF_MODE_STOP_HOOK,
    DISABLE_AUTO_COMPACT: () => DISABLE_AUTO_COMPACT,
    DISABLE_AUTOUPDATER: () => DISABLE_AUTOUPDATER,
    CLAUDE_PREVIEW_CLASSIFIER_FLOOR: () => CLAUDE_PREVIEW_CLASSIFIER_FLOOR,
    CLAUDE_DISABLE_ADOPT: () => CLAUDE_DISABLE_ADOPT,
    CLAUDE_CODE_WEBSEARCH_USE_CCR_PROXY: () => CLAUDE_CODE_WEBSEARCH_USE_CCR_PROXY,
    CLAUDE_CODE_WEBFETCH_USE_CCR_PROXY: () => CLAUDE_CODE_WEBFETCH_USE_CCR_PROXY,
    CLAUDE_CODE_VERIFY_PROMPT: () => CLAUDE_CODE_VERIFY_PROMPT,
    CLAUDE_CODE_USE_POWERSHELL_TOOL: () => CLAUDE_CODE_USE_POWERSHELL_TOOL,
    CLAUDE_CODE_USE_NATIVE_FILE_SEARCH: () => CLAUDE_CODE_USE_NATIVE_FILE_SEARCH,
    CLAUDE_CODE_USE_COWORK_PLUGINS: () => CLAUDE_CODE_USE_COWORK_PLUGINS,
    CLAUDE_CODE_TWO_STAGE_CLASSIFIER: () => CLAUDE_CODE_TWO_STAGE_CLASSIFIER,
    CLAUDE_CODE_TOTAL_TOKENS_REMINDER_BUDGET: () => CLAUDE_CODE_TOTAL_TOKENS_REMINDER_BUDGET,
    CLAUDE_CODE_TOTAL_TOKENS_REMINDER: () => CLAUDE_CODE_TOTAL_TOKENS_REMINDER,
    CLAUDE_CODE_TODO_REMINDER_MODE: () => CLAUDE_CODE_TODO_REMINDER_MODE,
    CLAUDE_CODE_TAG_ISMETA_MESSAGES: () => CLAUDE_CODE_TAG_ISMETA_MESSAGES,
    CLAUDE_CODE_SYNC_PLUGIN_INSTALL: () => CLAUDE_CODE_SYNC_PLUGIN_INSTALL,
    CLAUDE_CODE_SUPPRESS_SESSION_ATTRIBUTION: () => CLAUDE_CODE_SUPPRESS_SESSION_ATTRIBUTION,
    CLAUDE_CODE_SUBAGENT_CACHE_EVICT: () => CLAUDE_CODE_SUBAGENT_CACHE_EVICT,
    CLAUDE_CODE_SKIP_REPO_UPLOAD: () => CLAUDE_CODE_SKIP_REPO_UPLOAD,
    CLAUDE_CODE_SKIP_PROMPT_HISTORY: () => CLAUDE_CODE_SKIP_PROMPT_HISTORY,
    CLAUDE_CODE_SKIP_PROJECT_BACKFILL: () => CLAUDE_CODE_SKIP_PROJECT_BACKFILL,
    CLAUDE_CODE_SKIP_PLUGIN_MCP_SERVERS: () => CLAUDE_CODE_SKIP_PLUGIN_MCP_SERVERS,
    CLAUDE_CODE_SKILL_DESC_REFRAME: () => CLAUDE_CODE_SKILL_DESC_REFRAME,
    CLAUDE_CODE_PROACTIVE: () => CLAUDE_CODE_PROACTIVE,
    CLAUDE_CODE_PLUGIN_USE_ZIP_CACHE: () => CLAUDE_CODE_PLUGIN_USE_ZIP_CACHE,
    CLAUDE_CODE_PLUGIN_KEEP_MARKETPLACE_ON_FAILURE: () => CLAUDE_CODE_PLUGIN_KEEP_MARKETPLACE_ON_FAILURE,
    CLAUDE_CODE_PLUGIN_BINARY_ASSETS: () => CLAUDE_CODE_PLUGIN_BINARY_ASSETS,
    CLAUDE_CODE_PLAN_MODE_REQUIRED: () => CLAUDE_CODE_PLAN_MODE_REQUIRED,
    CLAUDE_CODE_PEWTER_OWL_TOOL: () => CLAUDE_CODE_PEWTER_OWL_TOOL,
    CLAUDE_CODE_PEWTER_OWL: () => CLAUDE_CODE_PEWTER_OWL,
    CLAUDE_CODE_PACKAGE_MANAGER_AUTO_UPDATE: () => CLAUDE_CODE_PACKAGE_MANAGER_AUTO_UPDATE,
    CLAUDE_CODE_OWNERSHIP_FRAME: () => CLAUDE_CODE_OWNERSHIP_FRAME,
    CLAUDE_CODE_NO_FLICKER: () => CLAUDE_CODE_NO_FLICKER,
    CLAUDE_CODE_NEW_INIT: () => CLAUDE_CODE_NEW_INIT,
    CLAUDE_CODE_NATIVE_CURSOR: () => CLAUDE_CODE_NATIVE_CURSOR,
    CLAUDE_CODE_KB_COHESION_FIXES: () => CLAUDE_CODE_KB_COHESION_FIXES,
    CLAUDE_CODE_INCLUDE_PARTIAL_MESSAGES: () => CLAUDE_CODE_INCLUDE_PARTIAL_MESSAGES,
    CLAUDE_CODE_IDE_SKIP_VALID_CHECK: () => CLAUDE_CODE_IDE_SKIP_VALID_CHECK,
    CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL: () => CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL,
    CLAUDE_CODE_HIDE_CWD: () => CLAUDE_CODE_HIDE_CWD,
    CLAUDE_CODE_GLOB_NO_IGNORE: () => CLAUDE_CODE_GLOB_NO_IGNORE,
    CLAUDE_CODE_GLOB_HIDDEN: () => CLAUDE_CODE_GLOB_HIDDEN,
    CLAUDE_CODE_FORK_SUBAGENT: () => CLAUDE_CODE_FORK_SUBAGENT,
    CLAUDE_CODE_FORCE_STRIKETHROUGH: () => CLAUDE_CODE_FORCE_STRIKETHROUGH,
    CLAUDE_CODE_FORCE_SESSION_PERSISTENCE: () => CLAUDE_CODE_FORCE_SESSION_PERSISTENCE,
    CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS: () => CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS,
    CLAUDE_CODE_ENABLE_XAA: () => CLAUDE_CODE_ENABLE_XAA,
    CLAUDE_CODE_ENABLE_TOKEN_USAGE_ATTACHMENT: () => CLAUDE_CODE_ENABLE_TOKEN_USAGE_ATTACHMENT,
    CLAUDE_CODE_ENABLE_TASKS: () => CLAUDE_CODE_ENABLE_TASKS,
    CLAUDE_CODE_ENABLE_SDK_FILE_CHECKPOINTING: () => CLAUDE_CODE_ENABLE_SDK_FILE_CHECKPOINTING,
    CLAUDE_CODE_ENABLE_REMOTE_RECAP: () => CLAUDE_CODE_ENABLE_REMOTE_RECAP,
    CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION: () => CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION,
    CLAUDE_CODE_ENABLE_MENU_KIND_LANES: () => CLAUDE_CODE_ENABLE_MENU_KIND_LANES,
    CLAUDE_CODE_ENABLE_LAUNCH_COMPOSER: () => CLAUDE_CODE_ENABLE_LAUNCH_COMPOSER,
    CLAUDE_CODE_ENABLE_FINE_GRAINED_TOOL_STREAMING: () => CLAUDE_CODE_ENABLE_FINE_GRAINED_TOOL_STREAMING,
    CLAUDE_CODE_ENABLE_FEEDBACK_SURVEY_FOR_OTEL: () => CLAUDE_CODE_ENABLE_FEEDBACK_SURVEY_FOR_OTEL,
    CLAUDE_CODE_ENABLE_EXPERIMENTAL_ADVISOR_TOOL: () => CLAUDE_CODE_ENABLE_EXPERIMENTAL_ADVISOR_TOOL,
    CLAUDE_CODE_ENABLE_DESIGN_SYNC: () => CLAUDE_CODE_ENABLE_DESIGN_SYNC,
    CLAUDE_CODE_ENABLE_DESIGN_MCP: () => CLAUDE_CODE_ENABLE_DESIGN_MCP,
    CLAUDE_CODE_ENABLE_CFC: () => CLAUDE_CODE_ENABLE_CFC,
    CLAUDE_CODE_ENABLE_BACKGROUND_PLUGIN_REFRESH: () => CLAUDE_CODE_ENABLE_BACKGROUND_PLUGIN_REFRESH,
    CLAUDE_CODE_ENABLE_AWAY_SUMMARY: () => CLAUDE_CODE_ENABLE_AWAY_SUMMARY,
    CLAUDE_CODE_ENABLE_APPEND_SUBAGENT_PROMPT: () => CLAUDE_CODE_ENABLE_APPEND_SUBAGENT_PROMPT,
    CLAUDE_CODE_DISABLE_VIRTUAL_SCROLL: () => CLAUDE_CODE_DISABLE_VIRTUAL_SCROLL,
    CLAUDE_CODE_DISABLE_THINKING: () => CLAUDE_CODE_DISABLE_THINKING,
    CLAUDE_CODE_DISABLE_TERMINAL_TITLE: () => CLAUDE_CODE_DISABLE_TERMINAL_TITLE,
    CLAUDE_CODE_DISABLE_REFUSAL_FALLBACK: () => CLAUDE_CODE_DISABLE_REFUSAL_FALLBACK,
    CLAUDE_CODE_DISABLE_PRECOMPACT_SKIP: () => CLAUDE_CODE_DISABLE_PRECOMPACT_SKIP,
    CLAUDE_CODE_DISABLE_POLICY_SKILLS: () => CLAUDE_CODE_DISABLE_POLICY_SKILLS,
    CLAUDE_CODE_DISABLE_OFFICIAL_MARKETPLACE_AUTOINSTALL: () => CLAUDE_CODE_DISABLE_OFFICIAL_MARKETPLACE_AUTOINSTALL,
    CLAUDE_CODE_DISABLE_NOTIFICATION_PRESENCE_CHECK: () => CLAUDE_CODE_DISABLE_NOTIFICATION_PRESENCE_CHECK,
    CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK: () => CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK,
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: () => CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC,
    CLAUDE_CODE_DISABLE_MOUSE_CLICKS: () => CLAUDE_CODE_DISABLE_MOUSE_CLICKS,
    CLAUDE_CODE_DISABLE_MOUSE: () => CLAUDE_CODE_DISABLE_MOUSE,
    CLAUDE_CODE_DISABLE_MEMORY_PERIODIC_RESYNC: () => CLAUDE_CODE_DISABLE_MEMORY_PERIODIC_RESYNC,
    CLAUDE_CODE_DISABLE_MEMORY_BULK_INFLATE: () => CLAUDE_CODE_DISABLE_MEMORY_BULK_INFLATE,
    CLAUDE_CODE_DISABLE_LAUNCH_COMPOSER: () => CLAUDE_CODE_DISABLE_LAUNCH_COMPOSER,
    CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS: () => CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS,
    CLAUDE_CODE_DISABLE_FILE_CHECKPOINTING: () => CLAUDE_CODE_DISABLE_FILE_CHECKPOINTING,
    CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY: () => CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY,
    CLAUDE_CODE_DISABLE_EXPLORE_PLAN_AGENTS: () => CLAUDE_CODE_DISABLE_EXPLORE_PLAN_AGENTS,
    CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS: () => CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS,
    CLAUDE_CODE_DISABLE_CRON: () => CLAUDE_CODE_DISABLE_CRON,
    CLAUDE_CODE_DISABLE_CLAUDE_MDS: () => CLAUDE_CODE_DISABLE_CLAUDE_MDS,
    CLAUDE_CODE_DISABLE_CLAUDE_API_SKILL: () => CLAUDE_CODE_DISABLE_CLAUDE_API_SKILL,
    CLAUDE_CODE_DISABLE_BUNDLED_SKILLS: () => CLAUDE_CODE_DISABLE_BUNDLED_SKILLS,
    CLAUDE_CODE_DISABLE_BG_EXIT_HANDOFF: () => CLAUDE_CODE_DISABLE_BG_EXIT_HANDOFF,
    CLAUDE_CODE_DISABLE_BACKGROUND_TASKS: () => CLAUDE_CODE_DISABLE_BACKGROUND_TASKS,
    CLAUDE_CODE_DISABLE_AUTO_MEMORY: () => CLAUDE_CODE_DISABLE_AUTO_MEMORY,
    CLAUDE_CODE_DISABLE_ATTACHMENTS: () => CLAUDE_CODE_DISABLE_ATTACHMENTS,
    CLAUDE_CODE_DISABLE_ARTIFACT: () => CLAUDE_CODE_DISABLE_ARTIFACT,
    CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN: () => CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN,
    CLAUDE_CODE_DISABLE_AGENT_VIEW: () => CLAUDE_CODE_DISABLE_AGENT_VIEW,
    CLAUDE_CODE_DISABLE_ADVISOR_TOOL: () => CLAUDE_CODE_DISABLE_ADVISOR_TOOL,
    CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING: () => CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING,
    CLAUDE_CODE_COLD_COMPACT: () => CLAUDE_CODE_COLD_COMPACT,
    CLAUDE_CODE_CHILD_SESSION: () => CLAUDE_CODE_CHILD_SESSION,
    CLAUDE_CODE_BUBBLEWRAP: () => CLAUDE_CODE_BUBBLEWRAP,
    CLAUDE_CODE_BG_TASKS_REPORT_RUNNING: () => CLAUDE_CODE_BG_TASKS_REPORT_RUNNING,
    CLAUDE_CODE_BASH_SANDBOX_SHOW_INDICATOR: () => CLAUDE_CODE_BASH_SANDBOX_SHOW_INDICATOR,
    CLAUDE_CODE_AUTO_CONNECT_IDE: () => CLAUDE_CODE_AUTO_CONNECT_IDE,
    CLAUDE_CODE_ARTIFACT_DIRECT_UPLOAD: () => CLAUDE_CODE_ARTIFACT_DIRECT_UPLOAD,
    CLAUDE_CODE_ALT_SCREEN_FULL_REPAINT: () => CLAUDE_CODE_ALT_SCREEN_FULL_REPAINT,
    CLAUDE_CODE_ACT_DONT_REDERIVE: () => CLAUDE_CODE_ACT_DONT_REDERIVE,
    CLAUDE_CODE_ACCESSIBILITY: () => CLAUDE_CODE_ACCESSIBILITY,
    CLAUDE_CHROME_CLASSIFIER_FLOOR: () => CLAUDE_CHROME_CLASSIFIER_FLOOR,
    CLAUDE_AX_SCREEN_READER: () => CLAUDE_AX_SCREEN_READER
  });
  var CLAUDE_AX_SCREEN_READER;
  var CLAUDE_CHROME_CLASSIFIER_FLOOR;
  var CLAUDE_PREVIEW_CLASSIFIER_FLOOR;
  var CLAUDE_CODE_ALT_SCREEN_FULL_REPAINT;
  var CLAUDE_CODE_BG_TASKS_REPORT_RUNNING;
  var CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING;
  var CLAUDE_CODE_DISABLE_ADVISOR_TOOL;
  var CLAUDE_CODE_DISABLE_AGENT_VIEW;
  var CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN;
  var CLAUDE_CODE_DISABLE_ARTIFACT;
  var CLAUDE_CODE_DISABLE_ATTACHMENTS;
  var CLAUDE_CODE_DISABLE_AUTO_MEMORY;
  var CLAUDE_CODE_DISABLE_BACKGROUND_TASKS;
  var CLAUDE_CODE_DISABLE_BG_EXIT_HANDOFF;
  var CLAUDE_CODE_DISABLE_BUNDLED_SKILLS;
  var CLAUDE_CODE_DISABLE_CLAUDE_API_SKILL;
  var CLAUDE_CODE_DISABLE_CLAUDE_MDS;
  var CLAUDE_CODE_DISABLE_CRON;
  var CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS;
  var CLAUDE_CODE_DISABLE_EXPLORE_PLAN_AGENTS;
  var CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY;
  var CLAUDE_CODE_DISABLE_FILE_CHECKPOINTING;
  var CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS;
  var CLAUDE_CODE_DISABLE_LAUNCH_COMPOSER;
  var CLAUDE_CODE_DISABLE_MEMORY_BULK_INFLATE;
  var CLAUDE_CODE_DISABLE_MEMORY_PERIODIC_RESYNC;
  var CLAUDE_CODE_DISABLE_MOUSE;
  var CLAUDE_CODE_DISABLE_MOUSE_CLICKS;
  var CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC;
  var CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK;
  var CLAUDE_CODE_DISABLE_NOTIFICATION_PRESENCE_CHECK;
  var CLAUDE_CODE_DISABLE_OFFICIAL_MARKETPLACE_AUTOINSTALL;
  var CLAUDE_CODE_DISABLE_POLICY_SKILLS;
  var CLAUDE_CODE_DISABLE_PRECOMPACT_SKIP;
  var CLAUDE_CODE_DISABLE_REFUSAL_FALLBACK;
  var CLAUDE_CODE_DISABLE_TERMINAL_TITLE;
  var CLAUDE_CODE_DISABLE_THINKING;
  var CLAUDE_CODE_DISABLE_VIRTUAL_SCROLL;
  var CLAUDE_CODE_ENABLE_APPEND_SUBAGENT_PROMPT;
  var CLAUDE_CODE_ENABLE_AWAY_SUMMARY;
  var CLAUDE_CODE_ENABLE_BACKGROUND_PLUGIN_REFRESH;
  var CLAUDE_CODE_ENABLE_CFC;
  var CLAUDE_CODE_ENABLE_DESIGN_MCP;
  var CLAUDE_CODE_ENABLE_DESIGN_SYNC;
  var CLAUDE_CODE_ENABLE_EXPERIMENTAL_ADVISOR_TOOL;
  var CLAUDE_CODE_ENABLE_FEEDBACK_SURVEY_FOR_OTEL;
  var CLAUDE_CODE_ENABLE_FINE_GRAINED_TOOL_STREAMING;
  var CLAUDE_CODE_ENABLE_LAUNCH_COMPOSER;
  var CLAUDE_CODE_ENABLE_MENU_KIND_LANES;
  var CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION;
  var CLAUDE_CODE_ENABLE_REMOTE_RECAP;
  var CLAUDE_CODE_ENABLE_SDK_FILE_CHECKPOINTING;
  var CLAUDE_CODE_ENABLE_TASKS;
  var CLAUDE_CODE_ENABLE_TOKEN_USAGE_ATTACHMENT;
  var CLAUDE_CODE_ENABLE_XAA;
  var CLAUDE_CODE_TODO_REMINDER_MODE;
  var CLAUDE_CODE_TOTAL_TOKENS_REMINDER;
  var CLAUDE_CODE_TOTAL_TOKENS_REMINDER_BUDGET;
  var CLAUDE_CODE_KB_COHESION_FIXES;
  var CLAUDE_CODE_ACCESSIBILITY;
  var CLAUDE_CODE_ACT_DONT_REDERIVE;
  var CLAUDE_CODE_ARTIFACT_DIRECT_UPLOAD;
  var CLAUDE_CODE_AUTO_CONNECT_IDE;
  var CLAUDE_CODE_BASH_SANDBOX_SHOW_INDICATOR;
  var CLAUDE_CODE_BUBBLEWRAP;
  var CLAUDE_CODE_CHILD_SESSION;
  var CLAUDE_CODE_COLD_COMPACT;
  var CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS;
  var CLAUDE_CODE_FORK_SUBAGENT;
  var CLAUDE_CODE_GLOB_HIDDEN;
  var CLAUDE_CODE_GLOB_NO_IGNORE;
  var CLAUDE_CODE_HIDE_CWD;
  var CLAUDE_CODE_FORCE_SESSION_PERSISTENCE;
  var CLAUDE_CODE_FORCE_STRIKETHROUGH;
  var CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL;
  var CLAUDE_CODE_IDE_SKIP_VALID_CHECK;
  var CLAUDE_CODE_INCLUDE_PARTIAL_MESSAGES;
  var CLAUDE_CODE_NATIVE_CURSOR;
  var CLAUDE_CODE_NEW_INIT;
  var CLAUDE_CODE_NO_FLICKER;
  var CLAUDE_CODE_OWNERSHIP_FRAME;
  var CLAUDE_CODE_PACKAGE_MANAGER_AUTO_UPDATE;
  var CLAUDE_CODE_PLAN_MODE_REQUIRED;
  var CLAUDE_CODE_PROACTIVE;
  var CLAUDE_CODE_SKILL_DESC_REFRAME;
  var CLAUDE_CODE_SKIP_PLUGIN_MCP_SERVERS;
  var CLAUDE_CODE_SKIP_PROJECT_BACKFILL;
  var CLAUDE_CODE_SKIP_PROMPT_HISTORY;
  var CLAUDE_CODE_SKIP_REPO_UPLOAD;
  var CLAUDE_CODE_SUBAGENT_CACHE_EVICT;
  var CLAUDE_CODE_SUPPRESS_SESSION_ATTRIBUTION;
  var CLAUDE_CODE_SYNC_PLUGIN_INSTALL;
  var CLAUDE_CODE_TAG_ISMETA_MESSAGES;
  var CLAUDE_CODE_TWO_STAGE_CLASSIFIER;
  var CLAUDE_CODE_USE_COWORK_PLUGINS;
  var CLAUDE_CODE_USE_NATIVE_FILE_SEARCH;
  var CLAUDE_CODE_USE_POWERSHELL_TOOL;
  var CLAUDE_CODE_WEBFETCH_USE_CCR_PROXY;
  var CLAUDE_CODE_WEBSEARCH_USE_CCR_PROXY;
  var CLAUDE_CODE_PLUGIN_KEEP_MARKETPLACE_ON_FAILURE;
  var CLAUDE_CODE_PLUGIN_BINARY_ASSETS;
  var CLAUDE_CODE_PLUGIN_USE_ZIP_CACHE;
  var CLAUDE_CODE_PEWTER_OWL;
  var CLAUDE_CODE_PEWTER_OWL_TOOL;
  var CLAUDE_CODE_VERIFY_PROMPT;
  var CLAUDE_DISABLE_ADOPT;
  var DISABLE_AUTO_COMPACT;
  var DISABLE_AUTOUPDATER;
  var DISABLE_BRIEF_MODE_STOP_HOOK;
  var DISABLE_BUG_COMMAND;
  var DISABLE_COMPACT;
  var DISABLE_COST_WARNINGS;
  var DISABLE_DOCTOR_COMMAND;
  var DISABLE_ERROR_REPORTING;
  var DISABLE_EXTRA_USAGE_COMMAND;
  var DISABLE_FEEDBACK_COMMAND;
  var DISABLE_GROWTHBOOK;
  var DISABLE_INSTALL_GITHUB_APP_COMMAND;
  var DISABLE_INSTALLATION_CHECKS;
  var DISABLE_INTERLEAVED_THINKING;
  var DISABLE_LOGIN_COMMAND;
  var DISABLE_LOGOUT_COMMAND;
  var DISABLE_PROMPT_CACHING;
  var DISABLE_PROMPT_CACHING_HAIKU;
  var DISABLE_PROMPT_CACHING_OPUS;
  var DISABLE_PROMPT_CACHING_SONNET;
  var DISABLE_PROMPT_CACHING_FABLE;
  var DISABLE_PROMPT_CACHING_MYTHOS;
  var DISABLE_TELEMETRY;
  var DISABLE_UPDATES;
  var DISABLE_UPGRADE_COMMAND;
  var ENABLE_BETA_TRACING_DETAILED;
  var ENABLE_CLAUDEAI_MCP_SERVERS;
  var ENABLE_ENHANCED_TELEMETRY_BETA;
  var ENABLE_LOCKLESS_UPDATES;
  var ENABLE_LSP_TOOL;
  var ENABLE_MCP_LARGE_OUTPUT_FILES;
  var ENABLE_PID_BASED_VERSION_LOCKING;
  var ENABLE_PROMPT_CACHING_1H;
  var ENABLE_PROMPT_CACHING_1H_BEDROCK;
  var ENABLE_SESSION_BACKGROUNDING;
  var ENABLE_SESSION_PERSISTENCE;
  var ENABLE_TOOL_SEARCH;
  var FORCE_AUTOUPDATE_PLUGINS;
  var FORCE_CODE_TERMINAL;
  var FORCE_PROMPT_CACHING_5M;
  var FORCE_VCR;
  var EMBEDDED_SEARCH_TOOLS;
  var USE_API_CLEAR_TOOL_RESULTS;
  var USE_API_CLEAR_TOOL_USES;
  var USE_API_CONTEXT_MANAGEMENT;
  var ZCs = __lazy(() => {
    ile();
    CLAUDE_AX_SCREEN_READER = $e.triBool();
    CLAUDE_CHROME_CLASSIFIER_FLOOR = $e.triBool();
    CLAUDE_PREVIEW_CLASSIFIER_FLOOR = $e.triBool();
    CLAUDE_CODE_ALT_SCREEN_FULL_REPAINT = $e.bool();
    CLAUDE_CODE_BG_TASKS_REPORT_RUNNING = $e.bool();
    CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING = $e.bool();
    CLAUDE_CODE_DISABLE_ADVISOR_TOOL = $e.bool();
    CLAUDE_CODE_DISABLE_AGENT_VIEW = $e.bool();
    CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN = $e.bool();
    CLAUDE_CODE_DISABLE_ARTIFACT = $e.bool();
    CLAUDE_CODE_DISABLE_ATTACHMENTS = $e.bool();
    CLAUDE_CODE_DISABLE_AUTO_MEMORY = $e.bool();
    CLAUDE_CODE_DISABLE_BACKGROUND_TASKS = $e.bool();
    CLAUDE_CODE_DISABLE_BG_EXIT_HANDOFF = $e.bool();
    CLAUDE_CODE_DISABLE_BUNDLED_SKILLS = $e.bool();
    CLAUDE_CODE_DISABLE_CLAUDE_API_SKILL = $e.bool();
    CLAUDE_CODE_DISABLE_CLAUDE_MDS = $e.bool();
    CLAUDE_CODE_DISABLE_CRON = $e.bool();
    CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS = $e.bool();
    CLAUDE_CODE_DISABLE_EXPLORE_PLAN_AGENTS = $e.bool();
    CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY = $e.bool();
    CLAUDE_CODE_DISABLE_FILE_CHECKPOINTING = $e.bool();
    CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS = $e.bool();
    CLAUDE_CODE_DISABLE_LAUNCH_COMPOSER = $e.bool();
    CLAUDE_CODE_DISABLE_MEMORY_BULK_INFLATE = $e.bool();
    CLAUDE_CODE_DISABLE_MEMORY_PERIODIC_RESYNC = $e.bool();
    CLAUDE_CODE_DISABLE_MOUSE = $e.triBool();
    CLAUDE_CODE_DISABLE_MOUSE_CLICKS = $e.triBool();
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = $e.bool();
    CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK = $e.bool();
    CLAUDE_CODE_DISABLE_NOTIFICATION_PRESENCE_CHECK = $e.bool();
    CLAUDE_CODE_DISABLE_OFFICIAL_MARKETPLACE_AUTOINSTALL = $e.bool();
    CLAUDE_CODE_DISABLE_POLICY_SKILLS = $e.bool();
    CLAUDE_CODE_DISABLE_PRECOMPACT_SKIP = $e.bool();
    CLAUDE_CODE_DISABLE_REFUSAL_FALLBACK = $e.bool();
    CLAUDE_CODE_DISABLE_TERMINAL_TITLE = $e.bool();
    CLAUDE_CODE_DISABLE_THINKING = $e.bool();
    CLAUDE_CODE_DISABLE_VIRTUAL_SCROLL = $e.bool();
    CLAUDE_CODE_ENABLE_APPEND_SUBAGENT_PROMPT = $e.bool();
    CLAUDE_CODE_ENABLE_AWAY_SUMMARY = $e.bool();
    CLAUDE_CODE_ENABLE_BACKGROUND_PLUGIN_REFRESH = $e.bool();
    CLAUDE_CODE_ENABLE_CFC = $e.triBool();
    CLAUDE_CODE_ENABLE_DESIGN_MCP = $e.triBool();
    CLAUDE_CODE_ENABLE_DESIGN_SYNC = $e.bool();
    CLAUDE_CODE_ENABLE_EXPERIMENTAL_ADVISOR_TOOL = $e.bool();
    CLAUDE_CODE_ENABLE_FEEDBACK_SURVEY_FOR_OTEL = $e.bool();
    CLAUDE_CODE_ENABLE_FINE_GRAINED_TOOL_STREAMING = $e.bool();
    CLAUDE_CODE_ENABLE_LAUNCH_COMPOSER = $e.bool();
    CLAUDE_CODE_ENABLE_MENU_KIND_LANES = $e.bool();
    CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION = $e.triBool();
    CLAUDE_CODE_ENABLE_REMOTE_RECAP = $e.triBool();
    CLAUDE_CODE_ENABLE_SDK_FILE_CHECKPOINTING = $e.bool();
    CLAUDE_CODE_ENABLE_TASKS = $e.bool();
    CLAUDE_CODE_ENABLE_TOKEN_USAGE_ATTACHMENT = $e.bool();
    CLAUDE_CODE_ENABLE_XAA = $e.bool();
    CLAUDE_CODE_TODO_REMINDER_MODE = $e.enum(["baseline", "off"]);
    CLAUDE_CODE_TOTAL_TOKENS_REMINDER = $e.str();
    CLAUDE_CODE_TOTAL_TOKENS_REMINDER_BUDGET = $e.int();
    CLAUDE_CODE_KB_COHESION_FIXES = $e.bool();
    CLAUDE_CODE_ACCESSIBILITY = $e.bool();
    CLAUDE_CODE_ACT_DONT_REDERIVE = $e.triBool();
    CLAUDE_CODE_ARTIFACT_DIRECT_UPLOAD = $e.bool();
    CLAUDE_CODE_AUTO_CONNECT_IDE = $e.triBool();
    CLAUDE_CODE_BASH_SANDBOX_SHOW_INDICATOR = $e.bool();
    CLAUDE_CODE_BUBBLEWRAP = $e.bool();
    CLAUDE_CODE_CHILD_SESSION = $e.bool();
    CLAUDE_CODE_COLD_COMPACT = $e.bool();
    CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = $e.bool();
    CLAUDE_CODE_FORK_SUBAGENT = $e.bool();
    CLAUDE_CODE_GLOB_HIDDEN = $e.bool();
    CLAUDE_CODE_GLOB_NO_IGNORE = $e.bool();
    CLAUDE_CODE_HIDE_CWD = $e.bool();
    CLAUDE_CODE_FORCE_SESSION_PERSISTENCE = $e.bool();
    CLAUDE_CODE_FORCE_STRIKETHROUGH = $e.bool();
    CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL = $e.bool();
    CLAUDE_CODE_IDE_SKIP_VALID_CHECK = $e.bool();
    CLAUDE_CODE_INCLUDE_PARTIAL_MESSAGES = $e.bool();
    CLAUDE_CODE_NATIVE_CURSOR = $e.bool();
    CLAUDE_CODE_NEW_INIT = $e.bool();
    CLAUDE_CODE_NO_FLICKER = $e.triBool();
    CLAUDE_CODE_OWNERSHIP_FRAME = $e.bool();
    CLAUDE_CODE_PACKAGE_MANAGER_AUTO_UPDATE = $e.bool();
    CLAUDE_CODE_PLAN_MODE_REQUIRED = $e.bool();
    CLAUDE_CODE_PROACTIVE = $e.bool();
    CLAUDE_CODE_SKILL_DESC_REFRAME = $e.bool();
    CLAUDE_CODE_SKIP_PLUGIN_MCP_SERVERS = $e.bool();
    CLAUDE_CODE_SKIP_PROJECT_BACKFILL = $e.bool();
    CLAUDE_CODE_SKIP_PROMPT_HISTORY = $e.bool();
    CLAUDE_CODE_SKIP_REPO_UPLOAD = $e.bool();
    CLAUDE_CODE_SUBAGENT_CACHE_EVICT = $e.bool();
    CLAUDE_CODE_SUPPRESS_SESSION_ATTRIBUTION = $e.bool();
    CLAUDE_CODE_SYNC_PLUGIN_INSTALL = $e.bool();
    CLAUDE_CODE_TAG_ISMETA_MESSAGES = $e.bool();
    CLAUDE_CODE_TWO_STAGE_CLASSIFIER = $e.bool();
    CLAUDE_CODE_USE_COWORK_PLUGINS = $e.bool();
    CLAUDE_CODE_USE_NATIVE_FILE_SEARCH = $e.bool();
    CLAUDE_CODE_USE_POWERSHELL_TOOL = $e.bool();
    CLAUDE_CODE_WEBFETCH_USE_CCR_PROXY = $e.bool();
    CLAUDE_CODE_WEBSEARCH_USE_CCR_PROXY = $e.bool();
    CLAUDE_CODE_PLUGIN_KEEP_MARKETPLACE_ON_FAILURE = $e.bool();
    CLAUDE_CODE_PLUGIN_BINARY_ASSETS = $e.bool();
    CLAUDE_CODE_PLUGIN_USE_ZIP_CACHE = $e.bool();
    CLAUDE_CODE_PEWTER_OWL = $e.triBool();
    CLAUDE_CODE_PEWTER_OWL_TOOL = $e.triBool();
    CLAUDE_CODE_VERIFY_PROMPT = $e.bool();
    CLAUDE_DISABLE_ADOPT = $e.bool();
    DISABLE_AUTO_COMPACT = $e.bool();
    DISABLE_AUTOUPDATER = $e.bool();
    DISABLE_BRIEF_MODE_STOP_HOOK = $e.bool();
    DISABLE_BUG_COMMAND = $e.bool();
    DISABLE_COMPACT = $e.bool();
    DISABLE_COST_WARNINGS = $e.bool();
    DISABLE_DOCTOR_COMMAND = $e.bool();
    DISABLE_ERROR_REPORTING = $e.bool();
    DISABLE_EXTRA_USAGE_COMMAND = $e.bool();
    DISABLE_FEEDBACK_COMMAND = $e.bool();
    DISABLE_GROWTHBOOK = $e.bool();
    DISABLE_INSTALL_GITHUB_APP_COMMAND = $e.bool();
    DISABLE_INSTALLATION_CHECKS = $e.bool();
    DISABLE_INTERLEAVED_THINKING = $e.bool();
    DISABLE_LOGIN_COMMAND = $e.bool();
    DISABLE_LOGOUT_COMMAND = $e.bool();
    DISABLE_PROMPT_CACHING = $e.bool();
    DISABLE_PROMPT_CACHING_HAIKU = $e.bool();
    DISABLE_PROMPT_CACHING_OPUS = $e.bool();
    DISABLE_PROMPT_CACHING_SONNET = $e.bool();
    DISABLE_PROMPT_CACHING_FABLE = $e.bool();
    DISABLE_PROMPT_CACHING_MYTHOS = $e.bool();
    DISABLE_TELEMETRY = $e.bool();
    DISABLE_UPDATES = $e.bool();
    DISABLE_UPGRADE_COMMAND = $e.bool();
    ENABLE_BETA_TRACING_DETAILED = $e.bool();
    ENABLE_CLAUDEAI_MCP_SERVERS = $e.bool();
    ENABLE_ENHANCED_TELEMETRY_BETA = $e.bool();
    ENABLE_LOCKLESS_UPDATES = $e.bool();
    ENABLE_LSP_TOOL = $e.bool();
    ENABLE_MCP_LARGE_OUTPUT_FILES = $e.bool();
    ENABLE_PID_BASED_VERSION_LOCKING = $e.bool();
    ENABLE_PROMPT_CACHING_1H = $e.bool();
    ENABLE_PROMPT_CACHING_1H_BEDROCK = $e.bool();
    ENABLE_SESSION_BACKGROUNDING = $e.bool();
    ENABLE_SESSION_PERSISTENCE = $e.bool();
    ENABLE_TOOL_SEARCH = $e.bool();
    FORCE_AUTOUPDATE_PLUGINS = $e.bool();
    FORCE_CODE_TERMINAL = $e.bool();
    FORCE_PROMPT_CACHING_5M = $e.bool();
    FORCE_VCR = $e.bool();
    EMBEDDED_SEARCH_TOOLS = $e.bool();
    USE_API_CLEAR_TOOL_RESULTS = $e.bool();
    USE_API_CLEAR_TOOL_USES = $e.bool();
    USE_API_CONTEXT_MANAGEMENT = $e.bool();
  });
  var rMr = {};
  __export(rMr, {
    ZELLIJ: () => ZELLIJ,
    ZED_TERM: () => ZED_TERM,
    XTERM_VERSION: () => XTERM_VERSION,
    XDG_RUNTIME_DIR: () => XDG_RUNTIME_DIR,
    WT_SESSION: () => WT_SESSION,
    WSL_DISTRO_NAME: () => WSL_DISTRO_NAME,
    WEBSITE_SKU: () => WEBSITE_SKU,
    WEBSITE_SITE_NAME: () => WEBSITE_SITE_NAME,
    WAYLAND_DISPLAY: () => WAYLAND_DISPLAY,
    VTE_VERSION: () => VTE_VERSION,
    VSCODE_GIT_ASKPASS_MAIN: () => VSCODE_GIT_ASKPASS_MAIN,
    VISUAL: () => VISUAL,
    VERCEL: () => VERCEL,
    UV_THREADPOOL_SIZE: () => UV_THREADPOOL_SIZE,
    USE_BUILTIN_RIPGREP: () => USE_BUILTIN_RIPGREP,
    USERPROFILE: () => USERPROFILE,
    USERNAME: () => USERNAME,
    USER: () => USER,
    TRACESTATE: () => TRACESTATE,
    TRACEPARENT: () => TRACEPARENT,
    TMUX_PANE: () => TMUX_PANE,
    TMUX: () => TMUX,
    TMPDIR: () => TMPDIR,
    TMP: () => TMP,
    TILIX_ID: () => TILIX_ID,
    TERM_PROGRAM_VERSION: () => TERM_PROGRAM_VERSION,
    TERM_PROGRAM: () => TERM_PROGRAM,
    TERMUX_VERSION: () => TERMUX_VERSION,
    TERMINATOR_UUID: () => TERMINATOR_UUID,
    TERMINAL_EMULATOR: () => TERMINAL_EMULATOR,
    TERMINAL: () => TERMINAL,
    TERM: () => TERM,
    TEMP: () => TEMP,
    SYSTEMROOT: () => SYSTEMROOT,
    STY: () => STY,
    SSL_CERT_FILE: () => SSL_CERT_FILE,
    SSH_TTY: () => SSH_TTY,
    SSH_CONNECTION: () => SSH_CONNECTION,
    SSH_CLIENT: () => SSH_CLIENT,
    SSH_AUTH_SOCK: () => SSH_AUTH_SOCK,
    SPACE_CREATOR_USER_ID: () => SPACE_CREATOR_USER_ID,
    SHELL: () => SHELL,
    SESSIONNAME: () => SESSIONNAME,
    SAFEUSER: () => SAFEUSER,
    RUNNER_OS: () => RUNNER_OS,
    RUNNER_ENVIRONMENT: () => RUNNER_ENVIRONMENT,
    REPL_SLUG: () => REPL_SLUG,
    REPL_ID: () => REPL_ID,
    RENDER: () => RENDER,
    PWD: () => PWD,
    PROJECT_DOMAIN: () => PROJECT_DOMAIN,
    PREFIX: () => PREFIX,
    PLAYWRIGHT_BROWSERS_PATH: () => PLAYWRIGHT_BROWSERS_PATH,
    PATH: () => PATH,
    NO_COLOR: () => NO_COLOR,
    NODE_OPTIONS: () => NODE_OPTIONS,
    NODE_EXTRA_CA_CERTS: () => NODE_EXTRA_CA_CERTS,
    NETLIFY: () => NETLIFY,
    MSYSTEM: () => MSYSTEM,
    LOCALAPPDATA: () => LOCALAPPDATA,
    LC_TERMINAL: () => LC_TERMINAL,
    LANG: () => LANG,
    K_SERVICE: () => K_SERVICE,
    KUBERNETES_SERVICE_HOST: () => KUBERNETES_SERVICE_HOST,
    KONSOLE_VERSION: () => KONSOLE_VERSION,
    KITTY_WINDOW_ID: () => KITTY_WINDOW_ID,
    JAVA_TOOL_OPTIONS: () => JAVA_TOOL_OPTIONS,
    JAVA_HOME: () => JAVA_HOME,
    ITERM_SESSION_ID: () => ITERM_SESSION_ID,
    IS_SANDBOX: () => IS_SANDBOX,
    IS_DEMO: () => IS_DEMO,
    HOME: () => HOME,
    GOOGLE_CLOUD_WORKSTATIONS: () => GOOGLE_CLOUD_WORKSTATIONS,
    GOOGLE_CLOUD_PROJECT: () => GOOGLE_CLOUD_PROJECT,
    GOOGLE_APPLICATION_CREDENTIALS: () => GOOGLE_APPLICATION_CREDENTIALS,
    GNOME_TERMINAL_SERVICE: () => GNOME_TERMINAL_SERVICE,
    GIT_TERMINAL_PROMPT: () => GIT_TERMINAL_PROMPT,
    GIT_SSH_COMMAND: () => GIT_SSH_COMMAND,
    GIT_CONFIG_COUNT: () => GIT_CONFIG_COUNT,
    GIT_ASKPASS: () => GIT_ASKPASS,
    GITPOD_WORKSPACE_ID: () => GITPOD_WORKSPACE_ID,
    GITLAB_CI: () => GITLAB_CI,
    GITHUB_WORKSPACE: () => GITHUB_WORKSPACE,
    GITHUB_TOKEN: () => GITHUB_TOKEN,
    GITHUB_ENV: () => GITHUB_ENV,
    GITHUB_ENTERPRISE_TOKEN: () => GITHUB_ENTERPRISE_TOKEN,
    GITHUB_ACTIONS: () => GITHUB_ACTIONS,
    GH_TOKEN: () => GH_TOKEN,
    GH_HOST: () => GH_HOST,
    GH_ENTERPRISE_TOKEN: () => GH_ENTERPRISE_TOKEN,
    GCM_INTERACTIVE: () => GCM_INTERACTIVE,
    GCLOUD_PROJECT: () => GCLOUD_PROJECT,
    FORCE_COLOR: () => FORCE_COLOR,
    EDITOR: () => EDITOR,
    DYNO: () => DYNO,
    DO_NOT_TRACK: () => DO_NOT_TRACK,
    DISPLAY: () => DISPLAY,
    DENO_DEPLOYMENT_ID: () => DENO_DEPLOYMENT_ID,
    DEMO_VERSION: () => DEMO_VERSION,
    DAYTONA_WS_ID: () => DAYTONA_WS_ID,
    DATABASE_URL: () => DATABASE_URL,
    CURSOR_TRACE_ID: () => CURSOR_TRACE_ID,
    COMSPEC: () => COMSPEC,
    COLORTERM: () => COLORTERM,
    CODESPACES: () => CODESPACES,
    CODER_WORKSPACE_NAME: () => CODER_WORKSPACE_NAME,
    CODER: () => CODER,
    CLOUDSDK_CONFIG: () => CLOUDSDK_CONFIG,
    CIRCLECI: () => CIRCLECI,
    CI: () => CI_export,
    CF_PAGES: () => CF_PAGES,
    BUN_INSTALL: () => BUN_INSTALL,
    BUILDKITE: () => BUILDKITE,
    BROWSER: () => BROWSER,
    AZURE_FUNCTIONS_ENVIRONMENT: () => AZURE_FUNCTIONS_ENVIRONMENT,
    AWS_LAMBDA_FUNCTION_NAME: () => AWS_LAMBDA_FUNCTION_NAME,
    AWS_EXECUTION_ENV: () => AWS_EXECUTION_ENV,
    APP_URL: () => APP_URL,
    APPDATA: () => APPDATA,
    ALACRITTY_LOG: () => ALACRITTY_LOG
  });
  var HOME;
  var PATH;
  var PWD;
  var PREFIX;
  var TMPDIR;
  var TMP;
  var TEMP;
  var SHELL;
  var COMSPEC;
  var SYSTEMROOT;
  var EDITOR;
  var VISUAL;
  var BROWSER;
  var DISPLAY;
  var WAYLAND_DISPLAY;
  var LANG;
  var USER;
  var USERNAME;
  var USERPROFILE;
  var APPDATA;
  var LOCALAPPDATA;
  var SAFEUSER;
  var XDG_RUNTIME_DIR;
  var NODE_OPTIONS;
  var NODE_EXTRA_CA_CERTS;
  var SSL_CERT_FILE;
  var UV_THREADPOOL_SIZE;
  var JAVA_HOME;
  var JAVA_TOOL_OPTIONS;
  var NO_COLOR;
  var FORCE_COLOR;
  var COLORTERM;
  var DO_NOT_TRACK;
  var TERM;
  var TERM_PROGRAM;
  var TERM_PROGRAM_VERSION;
  var LC_TERMINAL;
  var TERMINAL;
  var TERMINAL_EMULATOR;
  var TERMINATOR_UUID;
  var TERMUX_VERSION;
  var TILIX_ID;
  var ITERM_SESSION_ID;
  var KITTY_WINDOW_ID;
  var KONSOLE_VERSION;
  var XTERM_VERSION;
  var GNOME_TERMINAL_SERVICE;
  var VTE_VERSION;
  var ALACRITTY_LOG;
  var WT_SESSION;
  var SESSIONNAME;
  var STY;
  var TMUX;
  var TMUX_PANE;
  var ZELLIJ;
  var ZED_TERM;
  var WSL_DISTRO_NAME;
  var MSYSTEM;
  var VSCODE_GIT_ASKPASS_MAIN;
  var CURSOR_TRACE_ID;
  var SSH_CLIENT;
  var SSH_CONNECTION;
  var SSH_TTY;
  var SSH_AUTH_SOCK;
  var GIT_SSH_COMMAND;
  var GIT_TERMINAL_PROMPT;
  var GIT_ASKPASS;
  var GCM_INTERACTIVE;
  var GIT_CONFIG_COUNT;
  var GH_TOKEN;
  var GH_HOST;
  var GH_ENTERPRISE_TOKEN;
  var GITHUB_TOKEN;
  var GITHUB_ENTERPRISE_TOKEN;
  var GITHUB_ENV;
  var GITHUB_WORKSPACE;
  var GITHUB_ACTIONS;
  var CI_export;
  var CIRCLECI;
  var BUILDKITE;
  var GITLAB_CI;
  var RUNNER_OS;
  var RUNNER_ENVIRONMENT;
  var CODESPACES;
  var CODER;
  var CODER_WORKSPACE_NAME;
  var GITPOD_WORKSPACE_ID;
  var GOOGLE_CLOUD_WORKSTATIONS;
  var DAYTONA_WS_ID;
  var REPL_ID;
  var REPL_SLUG;
  var PROJECT_DOMAIN;
  var VERCEL;
  var RENDER;
  var NETLIFY;
  var DYNO;
  var CF_PAGES;
  var DENO_DEPLOYMENT_ID;
  var AWS_LAMBDA_FUNCTION_NAME;
  var AWS_EXECUTION_ENV;
  var K_SERVICE;
  var GOOGLE_CLOUD_PROJECT;
  var GCLOUD_PROJECT;
  var GOOGLE_APPLICATION_CREDENTIALS;
  var CLOUDSDK_CONFIG;
  var WEBSITE_SITE_NAME;
  var WEBSITE_SKU;
  var AZURE_FUNCTIONS_ENVIRONMENT;
  var APP_URL;
  var SPACE_CREATOR_USER_ID;
  var KUBERNETES_SERVICE_HOST;
  var BUN_INSTALL;
  var DATABASE_URL;
  var PLAYWRIGHT_BROWSERS_PATH;
  var USE_BUILTIN_RIPGREP;
  var IS_SANDBOX;
  var IS_DEMO;
  var DEMO_VERSION;
  var TRACEPARENT;
  var TRACESTATE;
  var eRs = __lazy(() => {
    ile();
    HOME = $e.str();
    PATH = $e.str();
    PWD = $e.str();
    PREFIX = $e.str();
    TMPDIR = $e.str();
    TMP = $e.str();
    TEMP = $e.str();
    SHELL = $e.str();
    COMSPEC = $e.str();
    SYSTEMROOT = $e.str();
    EDITOR = $e.str();
    VISUAL = $e.str();
    BROWSER = $e.str();
    DISPLAY = $e.str();
    WAYLAND_DISPLAY = $e.str();
    LANG = $e.str();
    USER = $e.str();
    USERNAME = $e.str();
    USERPROFILE = $e.str();
    APPDATA = $e.str();
    LOCALAPPDATA = $e.str();
    SAFEUSER = $e.str();
    XDG_RUNTIME_DIR = $e.str();
    NODE_OPTIONS = $e.str();
    NODE_EXTRA_CA_CERTS = $e.str();
    SSL_CERT_FILE = $e.str();
    UV_THREADPOOL_SIZE = $e.str();
    JAVA_HOME = $e.str();
    JAVA_TOOL_OPTIONS = $e.str();
    NO_COLOR = $e.str();
    FORCE_COLOR = $e.str();
    COLORTERM = $e.str();
    DO_NOT_TRACK = $e.str();
    TERM = $e.str();
    TERM_PROGRAM = $e.str();
    TERM_PROGRAM_VERSION = $e.str();
    LC_TERMINAL = $e.str();
    TERMINAL = $e.str();
    TERMINAL_EMULATOR = $e.str();
    TERMINATOR_UUID = $e.str();
    TERMUX_VERSION = $e.str();
    TILIX_ID = $e.str();
    ITERM_SESSION_ID = $e.str();
    KITTY_WINDOW_ID = $e.str();
    KONSOLE_VERSION = $e.str();
    XTERM_VERSION = $e.str();
    GNOME_TERMINAL_SERVICE = $e.str();
    VTE_VERSION = $e.str();
    ALACRITTY_LOG = $e.str();
    WT_SESSION = $e.str();
    SESSIONNAME = $e.str();
    STY = $e.str();
    TMUX = $e.str();
    TMUX_PANE = $e.str();
    ZELLIJ = $e.str();
    ZED_TERM = $e.str();
    WSL_DISTRO_NAME = $e.str();
    MSYSTEM = $e.str();
    VSCODE_GIT_ASKPASS_MAIN = $e.str();
    CURSOR_TRACE_ID = $e.str();
    SSH_CLIENT = $e.str();
    SSH_CONNECTION = $e.str();
    SSH_TTY = $e.str();
    SSH_AUTH_SOCK = $e.str();
    GIT_SSH_COMMAND = $e.str();
    GIT_TERMINAL_PROMPT = $e.str();
    GIT_ASKPASS = $e.str();
    GCM_INTERACTIVE = $e.str();
    GIT_CONFIG_COUNT = $e.str();
    GH_TOKEN = $e.str();
    GH_HOST = $e.str();
    GH_ENTERPRISE_TOKEN = $e.str();
    GITHUB_TOKEN = $e.str();
    GITHUB_ENTERPRISE_TOKEN = $e.str();
    GITHUB_ENV = $e.str();
    GITHUB_WORKSPACE = $e.str();
    GITHUB_ACTIONS = $e.str();
    CI_export = $e.str();
    CIRCLECI = $e.str();
    BUILDKITE = $e.str();
    GITLAB_CI = $e.str();
    RUNNER_OS = $e.str();
    RUNNER_ENVIRONMENT = $e.str();
    CODESPACES = $e.str();
    CODER = $e.str();
    CODER_WORKSPACE_NAME = $e.str();
    GITPOD_WORKSPACE_ID = $e.str();
    GOOGLE_CLOUD_WORKSTATIONS = $e.str();
    DAYTONA_WS_ID = $e.str();
    REPL_ID = $e.str();
    REPL_SLUG = $e.str();
    PROJECT_DOMAIN = $e.str();
    VERCEL = $e.str();
    RENDER = $e.str();
    NETLIFY = $e.str();
    DYNO = $e.str();
    CF_PAGES = $e.str();
    DENO_DEPLOYMENT_ID = $e.str();
    AWS_LAMBDA_FUNCTION_NAME = $e.str();
    AWS_EXECUTION_ENV = $e.str();
    K_SERVICE = $e.str();
    GOOGLE_CLOUD_PROJECT = $e.str();
    GCLOUD_PROJECT = $e.str();
    GOOGLE_APPLICATION_CREDENTIALS = $e.str();
    CLOUDSDK_CONFIG = $e.str();
    WEBSITE_SITE_NAME = $e.str();
    WEBSITE_SKU = $e.str();
    AZURE_FUNCTIONS_ENVIRONMENT = $e.str();
    APP_URL = $e.str();
    SPACE_CREATOR_USER_ID = $e.str();
    KUBERNETES_SERVICE_HOST = $e.str();
    BUN_INSTALL = $e.str();
    DATABASE_URL = $e.str();
    PLAYWRIGHT_BROWSERS_PATH = $e.str();
    USE_BUILTIN_RIPGREP = $e.str();
    IS_SANDBOX = $e.str();
    IS_DEMO = $e.str();
    DEMO_VERSION = $e.str();
    TRACEPARENT = $e.str();
    TRACESTATE = $e.str();
  });
  var oMr = {};